export interface BlogPost {
  slug: string;
  publishedAt: string;
  /**
   * Date of the last substantive content revision (ISO date). Omit until the
   * post is genuinely revised — `dateModified` falls back to `publishedAt`, and
   * bumping the date without changing the content is a worthless freshness
   * signal that search engines can detect.
   */
  updatedAt?: string;
  readingTime: number;
  titles: Record<string, string>;
  excerpts: Record<string, string>;
  keywords: string[];
  /**
   * Optional cover image path relative to /public (e.g. "/images/blog/foo.png").
   * Backward-compatible: older posts omit it and simply render no cover.
   */
  coverImage?: string;
  /**
   * Optional academic / source citations. When present they are rendered as a
   * "References" section under the article and emitted in the BlogPosting
   * JSON-LD `citation` field (strengthens E-E-A-T for research-backed posts).
   */
  citations?: { title: string; source: string; url: string }[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "what-is-swipe-fatigue",
    publishedAt: "2026-04-10",
    readingTime: 5,
    titles: {
      tr: "Swipe Yorgunluğu Nedir ve Neden Herkes Bundan Şikayetçi?",
      en: "What is Swipe Fatigue and Why is Everyone Tired of It?",
      de: "Was ist Swipe-Müdigkeit und warum hat jeder genug davon?",
      fr: "Qu'est-ce que la fatigue du swipe et pourquoi tout le monde en a marre ?",
      es: "¿Qué es el cansancio del swipe y por qué todos están hartos?",
      ar: "ما هو إرهاق التمرير ولماذا سئم منه الجميع؟",
      ru: "Усталость от свайпов: что это и почему её чувствуют все?",
      pt: "O que é a fadiga do swipe e por que todo mundo está cansado?",
      it: "Che cos'è la swipe fatigue e perché ne sono stanchi tutti?",
      ja: "スワイプ疲れとは？ なぜみんな限界を感じているのか",
      ko: "스와이프 피로란 무엇이고, 왜 모두가 지쳤을까?",
      zh: "什么是滑动疲劳？为什么大家都累了",
      nl: "Wat is swipemoeheid en waarom is iedereen het zat?",
      pl: "Zmęczenie swipe'owaniem: co to jest i dlaczego ma je każdy?",
      sv: "Vad är swipe-trötthet och varför är alla trötta på det?",
      hi: "स्वाइप थकान क्या है और सब इससे परेशान क्यों हैं?",
    },
    excerpts: {
      tr: "Dating uygulamalarında sürekli sola-sağa kaydırma yorgunluğu yaşıyorsanız yalnız değilsiniz. Swipe yorgunluğu nedir, neden oluşur ve Qulo bu sorunu nasıl çözer?",
      en: "If you're tired of endlessly swiping left and right on dating apps, you're not alone. What is swipe fatigue, why does it happen, and how does Qulo solve it?",
      de: "Wenn Sie es leid sind, endlos auf Dating-Apps zu wischen, sind Sie nicht allein. Was ist Swipe-Müdigkeit, warum entsteht sie und wie löst Qulo das Problem?",
      fr: "Marre de swiper sans fin sur les apps de rencontre ? Vous n'êtes pas seul. Qu'est-ce que la fatigue du swipe, d'où vient-elle et comment Qulo la résout ?",
      es: "Si estás cansado de deslizar sin fin en las apps de citas, no estás solo. ¿Qué es el cansancio del swipe, por qué aparece y cómo lo resuelve Qulo?",
      ar: "إذا سئمت التمرير يمينًا ويسارًا بلا نهاية في تطبيقات المواعدة، فأنت لست وحدك. ما هو إرهاق التمرير، ولماذا يحدث، وكيف يعالجه Qulo؟",
      ru: "Если вы устали бесконечно листать анкеты в приложениях для знакомств, вы не одиноки. Что такое усталость от свайпов, почему она возникает и как её решает Qulo?",
      pt: "Se você está cansado de deslizar sem parar nos apps de namoro, não está sozinho. O que é a fadiga do swipe, por que ela acontece e como o Qulo a resolve?",
      it: "Se sei stanco di scorrere profili all'infinito sulle app di incontri, non sei il solo. Che cos'è la swipe fatigue, perché nasce e come la risolve Qulo?",
      ja: "マッチングアプリで延々とスワイプし続けるのに疲れたなら、それはあなただけではありません。スワイプ疲れとは何か、なぜ起きるのか、そして Qulo はそれをどう解くのか。",
      ko: "데이팅 앱에서 끝없이 좌우로 넘기는 데 지쳤다면 당신만 그런 게 아닙니다. 스와이프 피로란 무엇이고, 왜 생기며, Qulo는 이를 어떻게 푸는지 살펴봅니다.",
      zh: "如果你厌倦了在交友软件上没完没了地左右滑动，你不是一个人。什么是滑动疲劳，它为什么会出现，Qulo 又是怎么解决的？",
      nl: "Ben je het eindeloze swipen op datingapps zat? Je bent niet de enige. Wat is swipemoeheid, waarom ontstaat het en hoe lost Qulo het op?",
      pl: "Masz dość bezustannego przesuwania profili w aplikacjach randkowych? Nie tylko ty. Czym jest zmęczenie swipe'owaniem, skąd się bierze i jak rozwiązuje je Qulo?",
      sv: "Är du trött på att swipa i all oändlighet på dejtingappar? Du är inte ensam. Vad är swipe-trötthet, varför uppstår den och hur löser Qulo det?",
      hi: "अगर आप डेटिंग ऐप्स पर लगातार दाएँ-बाएँ स्वाइप करते-करते थक चुके हैं, तो आप अकेले नहीं हैं। स्वाइप थकान क्या है, क्यों होती है और Qulo इसे कैसे हल करता है?",
    },
    keywords: ["swipe fatigue", "dating app burnout", "swipe yorgunluğu", "dating app tükenmişlik"],
  },
  {
    slug: "quiz-dating-future-of-matching",
    publishedAt: "2026-04-12",
    readingTime: 6,
    titles: {
      tr: "Quiz Dating: Eşleşmenin Geleceği Sorularda mı?",
      en: "Quiz Dating: Is the Future of Matching in Questions?",
      de: "Quiz-Dating: Liegt die Zukunft des Matchings in Fragen?",
      fr: "Quiz Dating : L'avenir du matching repose-t-il sur les questions ?",
      es: "Quiz Dating: ¿El futuro del matching está en las preguntas?",
      ar: "المواعدة بالأسئلة: هل يكمن مستقبل التطابق في السؤال؟",
      ru: "Квиз-дейтинг: будущее знакомств — в вопросах?",
      pt: "Quiz dating: o futuro dos matches está nas perguntas?",
      it: "Quiz dating: il futuro degli abbinamenti sta nelle domande?",
      ja: "クイズデーティング──マッチングの未来は問いの中に？",
      ko: "퀴즈 데이팅: 매칭의 미래는 질문에 있을까?",
      zh: "问答式交友：配对的未来在问题里吗？",
      nl: "Quizdaten: ligt de toekomst van matchen in vragen?",
      pl: "Randki przez pytania: czy tu leży przyszłość dopasowania?",
      sv: "Frågebaserad dejting: ligger matchningens framtid i frågorna?",
      hi: "क्विज़ डेटिंग: क्या मैच का भविष्य सवालों में है?",
    },
    excerpts: {
      tr: "Swipe tabanlı eşleşmeler yüzeysel kalırken, soru-cevap tabanlı dating yeni bir trend olarak yükseliyor. Quiz dating nedir ve neden daha derin bağlantılar kurmanızı sağlar?",
      en: "While swipe-based matching remains superficial, question-based dating is rising as a new trend. What is quiz dating and why does it lead to deeper connections?",
      de: "Während Swipe-basiertes Matching oberflächlich bleibt, steigt fragenbasiertes Dating als neuer Trend auf. Was ist Quiz-Dating und warum führt es zu tieferen Verbindungen?",
      fr: "Le matching par swipe reste superficiel, tandis que le dating par questions s'impose. Qu'est-ce que le quiz dating et pourquoi crée-t-il des liens plus profonds ?",
      es: "El matching por swipe se queda en la superficie, mientras las citas basadas en preguntas se abren paso. ¿Qué es el quiz dating y por qué crea vínculos más profundos?",
      ar: "بينما يبقى التطابق القائم على السحب سطحيًا، تصعد المواعدة القائمة على الأسئلة بوصفها اتجاهًا جديدًا. ما هي المواعدة بالأسئلة ولماذا تقود إلى روابط أعمق؟",
      ru: "Пока подбор по свайпам остаётся поверхностным, знакомства через вопросы становятся новым трендом. Что такое квиз-дейтинг и почему он даёт более глубокие связи?",
      pt: "O match por swipe continua superficial, enquanto o namoro baseado em perguntas vira tendência. O que é quiz dating e por que ele gera vínculos mais profundos?",
      it: "Il match per swipe resta superficiale, mentre gli incontri basati sulle domande diventano tendenza. Che cos'è il quiz dating e perché porta a legami più profondi?",
      ja: "スワイプによるマッチングが表面的なままである一方、質問から始まる出会いが新しい潮流になりつつあります。クイズデーティングとは何か、なぜ深い関係につながるのか。",
      ko: "스와이프 기반 매칭이 피상적인 데 머무는 사이, 질문으로 시작하는 만남이 새로운 흐름이 되고 있습니다. 퀴즈 데이팅이란 무엇이고 왜 더 깊은 관계로 이어질까요?",
      zh: "以滑动为主的配对停留在表面，而以问题开场的交友正成为新趋势。什么是问答式交友，它为什么能带来更深的连接？",
      nl: "Matchen via swipes blijft oppervlakkig, terwijl daten op basis van vragen een nieuwe trend wordt. Wat is quizdaten en waarom leidt het tot diepere connecties?",
      pl: "Dopasowanie przez swipe'y pozostaje powierzchowne, a randkowanie przez pytania staje się nowym trendem. Czym jest quiz dating i dlaczego daje głębsze więzi?",
      sv: "Medan matchning via swipes förblir ytlig växer frågebaserad dejting fram som en ny trend. Vad är quizdejting och varför leder det till djupare kontakt?",
      hi: "स्वाइप से होने वाला मिलान सतही ही रहता है, जबकि सवालों पर टिकी डेटिंग नया चलन बन रही है। क्विज़ डेटिंग क्या है और यह गहरे रिश्ते क्यों बनाती है?",
    },
    keywords: ["quiz dating", "question based dating", "soru cevap dating", "quiz dating app"],
  },
  {
    slug: "online-dating-safety-tips",
    publishedAt: "2026-04-14",
    readingTime: 7,
    titles: {
      tr: "Online Dating Güvenlik Rehberi: 10 Altın Kural",
      en: "Online Dating Safety Guide: 10 Golden Rules",
      de: "Online-Dating-Sicherheitsratgeber: 10 goldene Regeln",
      fr: "Guide de sécurité du dating en ligne : 10 règles d'or",
      es: "Guía de seguridad en citas online: 10 reglas de oro",
      ar: "دليل السلامة في المواعدة عبر الإنترنت: 10 قواعد ذهبية",
      ru: "Безопасность онлайн-знакомств: 10 золотых правил",
      pt: "Guia de segurança no namoro online: 10 regras de ouro",
      it: "Guida alla sicurezza negli incontri online: 10 regole d'oro",
      ja: "オンラインデートの安全ガイド：10の黄金ルール",
      ko: "온라인 데이팅 안전 가이드: 10가지 황금률",
      zh: "网络交友安全指南：十条黄金法则",
      nl: "Veilig online daten: 10 gouden regels",
      pl: "Bezpieczne randki online: 10 złotych zasad",
      sv: "Säkerhetsguide för nätdejting: 10 gyllene regler",
      hi: "ऑनलाइन डेटिंग सुरक्षा गाइड: 10 सुनहरे नियम",
    },
    excerpts: {
      tr: "Online tanışma güvenli olabilir — doğru adımları atarsanız. İşte dating uygulamalarında kendinizi korumanız için bilmeniz gereken 10 altın kural.",
      en: "Online dating can be safe — if you take the right steps. Here are 10 golden rules you need to know to protect yourself on dating apps.",
      de: "Online-Dating kann sicher sein — wenn Sie die richtigen Schritte unternehmen. Hier sind 10 goldene Regeln, mit denen Sie sich in Dating-Apps schützen.",
      fr: "Les rencontres en ligne peuvent être sûres — si vous prenez les bonnes mesures. Voici 10 règles d'or pour vous protéger sur les apps de rencontre.",
      es: "Las citas en línea pueden ser seguras — si tomas las medidas correctas. Estas son las 10 reglas de oro que necesitas para protegerte en las apps de citas.",
      ar: "المواعدة عبر الإنترنت يمكن أن تكون آمنة — إذا اتخذت الخطوات الصحيحة. إليك 10 قواعد ذهبية تحتاج إلى معرفتها لحماية نفسك في تطبيقات المواعدة.",
      ru: "Онлайн-знакомства могут быть безопасными — если делать правильные шаги. Вот 10 золотых правил, которые помогут защитить себя в приложениях для знакомств.",
      pt: "O namoro online pode ser seguro — se você der os passos certos. Aqui estão as 10 regras de ouro para se proteger nos apps de relacionamento.",
      it: "Gli incontri online possono essere sicuri — se fai le mosse giuste. Ecco le 10 regole d'oro da conoscere per proteggerti sulle app di incontri.",
      ja: "オンラインデートは安全にできます——正しい手順を踏めば。マッチングアプリで自分を守るために知っておきたい10の黄金ルールをまとめました。",
      ko: "온라인 데이팅은 안전할 수 있습니다 — 올바른 절차를 밟는다면요. 데이팅 앱에서 스스로를 지키기 위해 알아야 할 10가지 황금률을 정리했습니다.",
      zh: "网络交友可以是安全的——前提是你走对每一步。这里是在交友软件上保护自己必须知道的十条黄金法则。",
      nl: "Online daten kan veilig zijn — als je de juiste stappen zet. Dit zijn de 10 gouden regels om jezelf op datingapps te beschermen.",
      pl: "Randki online mogą być bezpieczne — jeśli zrobisz właściwe kroki. Oto 10 złotych zasad, które warto znać, by chronić się w aplikacjach randkowych.",
      sv: "Nätdejting kan vara tryggt — om du tar rätt steg. Här är de 10 gyllene regler du behöver kunna för att skydda dig på dejtingappar.",
      hi: "ऑनलाइन डेटिंग सुरक्षित हो सकती है — बशर्ते आप सही क़दम उठाएँ। डेटिंग ऐप्स पर खुद को बचाने के लिए ये 10 सुनहरे नियम जान लीजिए।",
    },
    keywords: ["online dating safety", "dating app security", "online dating güvenlik", "dating güvenli mi"],
  },
  {
    slug: "dating-app-burnout-signs",
    publishedAt: "2026-04-15",
    readingTime: 5,
    titles: {
      tr: "Dating Uygulama Tükenmişliğinin 5 Belirtisi (Ve Ne Yapmalısınız)",
      en: "5 Signs You Have Dating App Burnout (And What to Do About It)",
      de: "5 Anzeichen für Dating-App-Burnout (Und was Sie dagegen tun können)",
      fr: "5 signes de burnout des apps de rencontre (Et que faire)",
      es: "5 señales de agotamiento por apps de citas (Y qué hacer al respecto)",
      ar: "5 علامات على الإرهاق من تطبيقات المواعدة (وما العمل)",
      ru: "Выгорание от приложений для знакомств: 5 признаков и что делать",
      pt: "5 sinais de esgotamento por apps de namoro (e o que fazer)",
      it: "5 segnali di burnout da app di incontri (e cosa fare)",
      ja: "マッチングアプリ疲れの5つの兆候（そしてどうするか）",
      ko: "데이팅 앱 번아웃의 5가지 신호 (그리고 해야 할 일)",
      zh: "交友软件倦怠的 5 个信号（以及该怎么办）",
      nl: "5 signalen van dating-app-burn-out (en wat je eraan doet)",
      pl: "5 sygnałów wypalenia aplikacjami randkowymi (i co z tym zrobić)",
      sv: "5 tecken på utmattning av dejtingappar (och vad du kan göra)",
      hi: "डेटिंग ऐप बर्नआउट के 5 संकेत (और क्या करें)",
    },
    excerpts: {
      tr: "Dating uygulamalarından tükenmişlik mi hissediyorsunuz? İşte dating app burnout'un 5 belirtisi ve bu döngüden çıkmanın yolları.",
      en: "Feeling burned out from dating apps? Here are 5 signs of dating app burnout and ways to break free from the cycle.",
      de: "Fühlen Sie sich von Dating-Apps ausgebrannt? Hier sind 5 Anzeichen für Dating-App-Burnout und Wege aus dem Kreislauf.",
      fr: "Vous vous sentez épuisé par les apps de rencontre ? Voici 5 signes de burnout et des moyens d'en sortir.",
      es: "¿Te sientes agotado por las apps de citas? Aquí hay 5 señales de agotamiento y formas de romper el ciclo.",
      ar: "هل تشعر بالإرهاق من تطبيقات المواعدة؟ إليك 5 علامات على هذا الإرهاق وطرقًا للخروج من الحلقة المفرغة.",
      ru: "Чувствуете выгорание от приложений для знакомств? Вот 5 признаков выгорания и способы выбраться из этого круга.",
      pt: "Sentindo-se esgotado pelos apps de namoro? Aqui estão 5 sinais de esgotamento e maneiras de sair desse ciclo.",
      it: "Ti senti svuotato dalle app di incontri? Ecco 5 segnali di burnout e i modi per uscire dal circolo.",
      ja: "マッチングアプリに疲れきっていませんか。アプリ疲れの5つの兆候と、その悪循環から抜け出す方法をまとめました。",
      ko: "데이팅 앱 때문에 지쳐 있나요? 데이팅 앱 번아웃의 5가지 신호와 그 굴레에서 벗어나는 방법을 정리했습니다.",
      zh: "被交友软件耗空了？这里是交友软件倦怠的 5 个信号，以及跳出这个循环的方法。",
      nl: "Voel je je opgebrand door datingapps? Dit zijn 5 signalen van dating-app-burn-out en manieren om uit die cirkel te stappen.",
      pl: "Czujesz się wypalony aplikacjami randkowymi? Oto 5 sygnałów wypalenia i sposoby na wyjście z tego kręgu.",
      sv: "Känner du dig utmattad av dejtingappar? Här är 5 tecken på utmattning och sätt att ta sig ur cirkeln.",
      hi: "डेटिंग ऐप्स से थक चुके हैं? यहाँ डेटिंग ऐप बर्नआउट के 5 संकेत हैं और इस चक्र से बाहर निकलने के तरीक़े भी।",
    },
    keywords: ["dating app burnout", "dating app tükenmişlik", "tired of dating apps", "dating app fatigue", "dating burnout signs"],
  },
  {
    slug: "dating-apps-without-swiping",
    publishedAt: "2026-04-16",
    readingTime: 8,
    titles: {
      tr: "Swipe Olmadan Dating: 2026 Tam Rehberi",
      en: "Dating Apps Without Swiping: A Complete Guide for 2026",
      de: "Dating-Apps ohne Swipen: Ein vollständiger Leitfaden für 2026",
      fr: "Apps de rencontre sans swipe : Guide complet 2026",
      es: "Apps de citas sin deslizar: Guía completa 2026",
      ar: "المواعدة بلا سحب: دليل 2026 الكامل",
      ru: "Знакомства без свайпов: полный гид на 2026 год",
      pt: "Apps de relacionamento sem swipe: guia completo de 2026",
      it: "App di incontri senza swipe: la guida completa 2026",
      ja: "スワイプしないマッチングアプリ：2026年版 完全ガイド",
      ko: "스와이프 없는 데이팅 앱: 2026 완전 가이드",
      zh: "不用滑动的约会应用：2026 完全指南",
      nl: "Datingapps zonder swipen: de complete gids voor 2026",
      pl: "Aplikacje randkowe bez swipe'a: pełny przewodnik 2026",
      sv: "Dejtingappar utan swipe: den kompletta guiden för 2026",
      hi: "बिना स्वाइप वाले डेटिंग ऐप: 2026 की पूरी गाइड",
    },
    excerpts: {
      tr: "Swipe mekanizmasından bıktıysanız alternatifiniz var. Soru tabanlı, yapay zeka destekli ve etkileşim odaklı dating uygulamalarının tam rehberi.",
      en: "Tired of the swipe mechanic? You have alternatives. A complete guide to question-based, AI-powered, and interaction-focused dating apps.",
      de: "Genug vom Wischen? Es gibt Alternativen. Ein vollständiger Leitfaden zu Dating-Apps, die auf Fragen, KI und echter Interaktion aufbauen.",
      fr: "Marre de swiper ? Vous avez des alternatives. Un guide complet des apps de rencontre fondées sur les questions, l'IA et l'interaction réelle.",
      es: "¿Cansado de deslizar? Tienes alternativas. Una guía completa de las apps de citas basadas en preguntas, en IA y en la interacción real.",
      ar: "سئمت آلية السحب؟ لديك بدائل. دليل كامل لتطبيقات المواعدة القائمة على الأسئلة والمدعومة بالذكاء الاصطناعي والقائمة على التفاعل.",
      ru: "Устали от механики свайпа? У вас есть альтернативы. Полный гид по приложениям для знакомств на основе вопросов, ИИ и живого взаимодействия.",
      pt: "Cansado do mecanismo de swipe? Existem alternativas. Um guia completo dos apps de relacionamento baseados em perguntas, em IA e em interação real.",
      it: "Stanco del meccanismo dello swipe? Le alternative esistono. Una guida completa alle app di incontri basate su domande, IA e interazione reale.",
      ja: "スワイプという仕組みに飽きたなら、選択肢はあります。質問ベース、AI活用、対話重視のマッチングアプリを網羅したガイドです。",
      ko: "스와이프 방식에 질렸다면 대안이 있습니다. 질문 기반, 인공지능 기반, 상호작용 중심 데이팅 앱을 정리한 완전 가이드입니다.",
      zh: "厌倦了滑动这套机制？你有别的选择。这是一份关于问题驱动、人工智能驱动与互动优先的约会应用的完全指南。",
      nl: "Klaar met het swipemechanisme? Er zijn alternatieven. Een complete gids voor datingapps op basis van vragen, AI en echte interactie.",
      pl: "Masz dość mechaniki swipe'a? Są alternatywy. Pełny przewodnik po aplikacjach randkowych opartych na pytaniach, sztucznej inteligencji i realnej interakcji.",
      sv: "Trött på swipe-mekaniken? Det finns alternativ. En komplett guide till dejtingappar byggda på frågor, AI och verklig interaktion.",
      hi: "स्वाइप वाली बनावट से ऊब गए हैं? विकल्प मौजूद हैं। सवालों पर टिकी, एआई से चलने वाली और बातचीत केंद्रित डेटिंग ऐप्स की पूरी गाइड।",
    },
    keywords: ["dating app without swiping", "no swipe dating app", "alternative dating apps", "swipe olmadan dating", "dating apps 2026"],
  },
  {
    slug: "quiz-dating-for-introverts",
    publishedAt: "2026-04-16",
    readingTime: 6,
    titles: {
      tr: "İçe Dönükler İçin Quiz Dating: Neden Mükemmel Bir Eşleşme?",
      en: "Why Introverts Are Choosing Quiz Dating Over Swipe Apps",
      de: "Warum Introvertierte Quiz-Dating gegenüber Swipe-Apps bevorzugen",
      fr: "Pourquoi les introvertis préfèrent le quiz dating aux apps de swipe",
      es: "Por qué los introvertidos eligen el quiz dating sobre las apps de swipe",
      ar: "لماذا يختار المنطوون المواعدة بالأسئلة بدل تطبيقات السحب؟",
      ru: "Почему интроверты выбирают квиз-дейтинг вместо свайпов",
      pt: "Por que os introvertidos preferem quiz dating ao swipe",
      it: "Perché gli introversi preferiscono il quiz dating allo swipe",
      ja: "内向的な人がスワイプよりクイズ・デーティングを選ぶ理由",
      ko: "내향적인 사람이 스와이프 대신 퀴즈 데이팅을 고르는 이유",
      zh: "内向者为什么放弃滑动，选择答题式约会",
      nl: "Waarom introverten quizdating verkiezen boven swipen",
      pl: "Dlaczego introwertycy wybierają pytania zamiast swipe'ów",
      sv: "Därför väljer introverta quizdejting framför swipe-appar",
      hi: "अंतर्मुखी लोग स्वाइप छोड़कर क्विज़ डेटिंग क्यों चुन रहे हैं",
    },
    excerpts: {
      tr: "İçe dönük biri olarak dating uygulamaları sizi bunaltıyor mu? Quiz dating'in neden içe dönükler için ideal olduğunu ve Qulo'nun nasıl fark yarattığını keşfedin.",
      en: "Do dating apps overwhelm you as an introvert? Discover why quiz dating is ideal for introverts and how Qulo makes a difference.",
      de: "Überfordern Dating-Apps Sie als introvertierten Menschen? Entdecken Sie, warum Quiz-Dating ideal für Introvertierte ist und welchen Unterschied Qulo macht.",
      fr: "Les apps de rencontre vous submergent en tant qu'introverti ? Découvrez pourquoi le quiz dating est idéal pour les introvertis et ce que Qulo change.",
      es: "¿Las apps de citas te abruman como introvertido? Descubre por qué el quiz dating es ideal para los introvertidos y qué cambia Qulo.",
      ar: "هل تُرهقك تطبيقات المواعدة بوصفك شخصًا منطويًا؟ اكتشف لماذا تُعدّ المواعدة بالأسئلة مثالية للمنطوين، وكيف يصنع Qulo الفارق.",
      ru: "Приложения для знакомств перегружают вас как интроверта? Разберём, почему квиз-дейтинг идеален для интровертов и что здесь меняет Qulo.",
      pt: "Os apps de namoro te sobrecarregam como introvertido? Veja por que o quiz dating é ideal para introvertidos e como o Qulo faz diferença.",
      it: "Le app di incontri ti travolgono da introverso? Scopri perché il quiz dating è ideale per gli introversi e come Qulo fa la differenza.",
      ja: "内向的なあなたにとって、マッチングアプリは負担が大きすぎませんか。クイズ・デーティングが内向的な人に向いている理由と、Qulo が変えるところを解説します。",
      ko: "내향적인 사람에게 데이팅 앱은 너무 벅차지 않나요? 퀴즈 데이팅이 내향적인 사람에게 이상적인 이유와 Qulo가 만드는 차이를 살펴봅니다.",
      zh: "作为内向者，约会应用是不是让你不堪重负？看看答题式约会为什么最适合内向的人，以及 Qulo 带来了什么不同。",
      nl: "Overweldigen datingapps je als introvert? Ontdek waarom quizdating ideaal is voor introverten en welk verschil Qulo maakt.",
      pl: "Aplikacje randkowe przytłaczają cię jako introwertyka? Zobacz, dlaczego randkowanie przez pytania jest idealne dla introwertyków i co zmienia Qulo.",
      sv: "Blir dejtingappar för mycket för dig som introvert? Se varför quizdejting passar introverta så bra och vilken skillnad Qulo gör.",
      hi: "अंतर्मुखी होने के नाते डेटिंग ऐप्स आपको थका देते हैं? जानिए क्विज़ डेटिंग अंतर्मुखी लोगों के लिए आदर्श क्यों है और Qulo क्या फ़र्क़ लाता है।",
    },
    keywords: ["dating app for introverts", "introvert dating", "quiz dating introverts", "içe dönükler için dating", "best dating app introverts"],
  },
  {
    slug: "science-behind-question-based-matching",
    publishedAt: "2026-04-16",
    readingTime: 7,
    titles: {
      tr: "Soru Tabanlı Eşleşmenin Arkasındaki Bilim: Neden Sorular Fotoğraflardan Daha İyi?",
      en: "The Science Behind Question-Based Matching: Why Questions Beat Photos",
      de: "Die Wissenschaft hinter fragenbasiertem Matching: Warum Fragen besser sind als Fotos",
      fr: "La science du matching par questions : Pourquoi les questions battent les photos",
      es: "La ciencia detrás del matching por preguntas: Por qué las preguntas ganan a las fotos",
      ar: "علم التطابق القائم على الأسئلة: لماذا تقول الأسئلة أكثر من الصور؟",
      ru: "Наука подбора через вопросы: почему вопросы говорят больше фото",
      pt: "A ciência do match por perguntas: por que dizem mais que fotos",
      it: "La scienza del match per domande: perché dicono più delle foto",
      ja: "質問によるマッチングの科学──写真より問いが多くを語る理由",
      ko: "질문 기반 매칭의 과학: 사진보다 질문이 더 많이 말하는 이유",
      zh: "以问题匹配的科学：为什么问题比照片说得更多",
      nl: "Waarom vragen meer zeggen dan foto's: de wetenschap erachter",
      pl: "Nauka o dopasowaniu przez pytania: mówią więcej niż zdjęcia",
      sv: "Varför frågor säger mer än foton: vetenskapen bakom matchning",
      hi: "सवालों पर टिकी मैचिंग का विज्ञान: सवाल तस्वीरों से ज़्यादा क्यों बताते हैं",
    },
    excerpts: {
      tr: "Psikoloji araştırmaları, soruların yüzeysel çekicilikten çok daha güçlü bağlantılar kurduğunu gösteriyor. İşte soru tabanlı eşleşmenin bilimsel temelleri.",
      en: "Psychology research shows that questions build much stronger connections than superficial attraction. Here's the scientific foundation of question-based matching.",
      de: "Psychologische Forschung zeigt: Fragen bauen stärkere Verbindungen auf als oberflächliche Anziehung. Hier sind die wissenschaftlichen Grundlagen dahinter.",
      fr: "La recherche en psychologie montre que les questions créent des liens bien plus solides que l'attraction superficielle. Voici ses bases scientifiques.",
      es: "La investigación psicológica muestra que las preguntas crean vínculos mucho más fuertes que la atracción superficial. Estas son sus bases científicas.",
      ar: "تُظهر أبحاث علم النفس أن الأسئلة تبني روابط أقوى بكثير من الانجذاب السطحي. إليك الأساس العلمي للتطابق القائم على الأسئلة.",
      ru: "Психологические исследования показывают, что вопросы создают куда более прочные связи, чем поверхностное влечение. Вот научная основа подбора через вопросы.",
      pt: "A pesquisa em psicologia mostra que perguntas criam vínculos muito mais fortes do que a atração superficial. Esta é a base científica do match por perguntas.",
      it: "La ricerca psicologica mostra che le domande creano legami molto più forti dell'attrazione superficiale. Ecco le basi scientifiche del match per domande.",
      ja: "心理学の研究は、問いが表面的な惹かれ方よりはるかに強い結びつきを生むことを示しています。質問によるマッチングの科学的な土台を紹介します。",
      ko: "심리학 연구는 질문이 피상적인 끌림보다 훨씬 단단한 관계를 만든다는 것을 보여 줍니다. 질문 기반 매칭의 과학적 토대를 정리했습니다.",
      zh: "心理学研究显示，问题建立的联系远比表面的吸引更牢固。这里是以问题匹配背后的科学依据。",
      nl: "Psychologisch onderzoek laat zien dat vragen veel sterkere banden opleveren dan oppervlakkige aantrekking. Dit is de wetenschappelijke basis eronder.",
      pl: "Badania psychologiczne pokazują, że pytania budują znacznie silniejsze więzi niż powierzchowna atrakcyjność. Oto naukowe podstawy dopasowania przez pytania.",
      sv: "Psykologisk forskning visar att frågor skapar mycket starkare band än ytlig attraktion. Här är den vetenskapliga grunden för frågebaserad matchning.",
      hi: "मनोविज्ञान के शोध दिखाते हैं कि सवाल सतही आकर्षण से कहीं मज़बूत रिश्ते बनाते हैं। यहाँ सवालों पर टिकी मैचिंग का वैज्ञानिक आधार है।",
    },
    keywords: ["question based matching science", "compatibility science dating", "psychology of dating", "36 questions dating", "dating bilimi"],
  },
  {
    slug: "what-actually-predicts-compatibility",
    publishedAt: "2026-07-18",
    readingTime: 9,
    titles: {
      tr: "Aşkı 'Tipiniz' Belirlemez: Uyumluluğu Gerçekte Ne Öngörür?",
      en: "Your 'Type' Doesn't Predict Love: What Actually Predicts Compatibility",
      de: "Dein „Typ“ sagt keine Liebe voraus: Was wirklich über Kompatibilität entscheidet",
      fr: "Votre « type » ne prédit pas l'amour : ce qui prédit vraiment la compatibilité",
      es: "Tu «tipo» no predice el amor: qué predice de verdad la compatibilidad",
      ar: "\"نمطك المفضّل\" لا يتنبّأ بالحب: ما الذي يتنبّأ فعلاً بالتوافق",
      ru: "Ваш «тип» не предсказывает любовь: что на самом деле предсказывает совместимость",
      pt: "Seu \"tipo\" não prevê o amor: o que realmente prevê a compatibilidade",
      it: "Il tuo «tipo» non predice l'amore: cosa predice davvero la compatibilità",
      ja: "「好みのタイプ」は恋を予測しない――本当に相性を決めるものとは",
      ko: "당신의 '이상형'은 사랑을 예측하지 못한다: 진짜로 궁합을 결정하는 것",
      zh: "你的「理想型」预测不了爱情：真正决定契合度的是什么",
      nl: "Je \"type\" voorspelt geen liefde: wat compatibiliteit echt voorspelt",
      pl: "Twój „typ” nie przewiduje miłości: co naprawdę przewiduje zgodność",
      sv: "Din \"typ\" förutsäger inte kärlek: vad som faktiskt förutsäger kompatibilitet",
      hi: "आपका 'टाइप' प्यार की भविष्यवाणी नहीं करता: असल में अनुकूलता का पता किससे चलता है",
    },
    excerpts: {
      tr: "Onlarca yıllık ilişki bilimi net: ne istediğinizi sandığınız 'tip', kiminle bağ kuracağınızı öngörmüyor. Peki uyumluluğu gerçekte ne belirliyor — ve bu neden çoğu dating uygulamasının baştan yanlış kurulduğu anlamına geliyor?",
      en: "Decades of relationship science are clear: the 'type' you think you want doesn't predict who you'll actually connect with. So what really predicts compatibility — and why does it mean most dating apps are built backwards?",
      de: "Jahrzehnte der Beziehungsforschung sind eindeutig: Der „Typ“, von dem du glaubst, ihn zu wollen, sagt nicht voraus, mit wem du dich tatsächlich verbindest. Was sagt Kompatibilität also wirklich voraus — und warum bedeutet das, dass die meisten Dating-Apps verkehrt herum gebaut sind?",
      fr: "Des décennies de science des relations sont claires : le « type » que vous croyez désirer ne prédit pas avec qui vous vous connecterez vraiment. Alors qu'est-ce qui prédit réellement la compatibilité — et pourquoi cela signifie-t-il que la plupart des applications de rencontre sont construites à l'envers ?",
      es: "Décadas de ciencia de las relaciones lo dejan claro: el «tipo» que crees querer no predice con quién conectarás en realidad. Entonces, ¿qué predice de verdad la compatibilidad? ¿Y por qué eso significa que la mayoría de las apps de citas están construidas al revés?",
      ar: "عقودٌ من علم العلاقات تقول بوضوح: \"النمط\" الذي تظنّ أنك تريده لا يتنبّأ بمن ستنسجم معه فعلاً. فما الذي يتنبّأ حقاً بالتوافق — ولماذا يعني ذلك أن معظم تطبيقات المواعدة مبنيّة بالمقلوب؟",
      ru: "Десятилетия науки об отношениях говорят однозначно: «тип», который вы, как вам кажется, хотите, не предсказывает, с кем вы на самом деле сблизитесь. Так что же действительно предсказывает совместимость — и почему из этого следует, что большинство приложений для знакомств устроены задом наперёд?",
      pt: "Décadas de ciência dos relacionamentos são claras: o \"tipo\" que você acha que quer não prevê com quem você vai realmente se conectar. Então o que de fato prevê a compatibilidade — e por que isso significa que a maioria dos apps de namoro foi construída de trás para frente?",
      it: "Decenni di scienza delle relazioni parlano chiaro: il «tipo» che credi di volere non predice con chi entrerai davvero in sintonia. Allora cosa predice realmente la compatibilità — e perché questo significa che la maggior parte delle app di dating è costruita al contrario?",
      ja: "数十年にわたる恋愛心理学の結論ははっきりしています。あなたが求めていると思い込んでいる「タイプ」は、実際に惹かれ合う相手を予測しません。では、本当に相性を決めるものは何か――そしてなぜ、それはほとんどのマッチングアプリが逆向きに作られていることを意味するのでしょうか。",
      ko: "수십 년간의 관계 심리학이 내린 결론은 분명합니다. 당신이 원한다고 믿는 '이상형'은 실제로 마음이 통할 상대를 예측하지 못합니다. 그렇다면 진짜로 궁합을 결정하는 것은 무엇이며, 왜 그것은 대부분의 데이팅 앱이 거꾸로 설계되어 있음을 뜻할까요?",
      zh: "数十年的关系科学结论明确：你以为自己想要的那种「理想型」，并不能预测你真正会与谁产生共鸣。那么，究竟是什么真正决定了契合度——又为什么这意味着大多数交友软件的设计方向从一开始就反了？",
      nl: "Decennia aan relatiewetenschap zijn duidelijk: het \"type\" waarvan je denkt dat je het wilt, voorspelt niet met wie je echt een klik krijgt. Dus wat voorspelt compatibiliteit werkelijk — en waarom betekent dat dat de meeste datingapps verkeerd om zijn gebouwd?",
      pl: "Dziesięciolecia nauki o relacjach mówią jasno: „typ”, którego — jak ci się wydaje — pragniesz, nie przewiduje, z kim naprawdę się zwiążesz. Co więc naprawdę przewiduje zgodność — i dlaczego oznacza to, że większość aplikacji randkowych jest zbudowana na odwrót?",
      sv: "Decennier av relationsforskning är tydliga: den \"typ\" du tror att du vill ha förutsäger inte vem du faktiskt får kontakt med. Så vad förutsäger egentligen kompatibilitet — och varför innebär det att de flesta dejtingappar är byggda bakvänt?",
      hi: "रिश्तों पर दशकों के शोध की बात साफ है: जिस 'टाइप' को आप चाहते हैं, वह यह तय नहीं करता कि आप असल में किससे जुड़ेंगे। तो फिर अनुकूलता की भविष्यवाणी सचमुच किससे होती है — और इसका मतलब यह क्यों है कि ज़्यादातर डेटिंग ऐप उल्टे बने हुए हैं?",
    },
    keywords: [
      "what predicts compatibility",
      "does your type matter",
      "ideal partner preferences",
      "can you predict attraction",
      "why dating apps dont work",
      "uyumluluk bilimi",
      "aşkı ne belirler",
      "eş seçimi psikolojisi",
    ],
    citations: [
      {
        title:
          "Machine learning uncovers the most robust self-report predictors of relationship quality across 43 longitudinal couples studies",
        source: "Joel, Eastwick et al. — PNAS (2020)",
        url: "https://www.pnas.org/doi/10.1073/pnas.1917036117",
      },
      {
        title:
          "Sex differences in mate preferences revisited: Do people know what they initially desire in a romantic partner?",
        source: "Eastwick & Finkel — Journal of Personality and Social Psychology (2008)",
        url: "https://faculty.wcas.northwestern.edu/eli-finkel/documents/EastwickFinkel2008_JPSP.pdf",
      },
      {
        title: "Online Dating: A Critical Analysis From the Perspective of Psychological Science",
        source: "Finkel, Eastwick, Karney, Reis & Sprecher — Psychological Science in the Public Interest (2012)",
        url: "https://journals.sagepub.com/doi/10.1177/1529100612436522",
      },
      {
        title: "From Looking for Love to Swiping the Field: Online Dating in the U.S.",
        source: "Pew Research Center (2023)",
        url: "https://www.pewresearch.org/internet/2023/02/02/from-looking-for-love-to-swiping-the-field-online-dating-in-the-u-s/",
      },
    ],
  },
  {
    slug: "psychology-of-the-first-message",
    publishedAt: "2026-07-20",
    updatedAt: "2026-09-03",
    readingTime: 8,
    coverImage: "/images/blog/psychology-of-the-first-message.png",
    titles: {
      tr: "“Selam” Neden Cevapsız Kalır: Yanıt Alan İlk Mesajın Psikolojisi",
      en: "Why “Hey” Gets Ignored: The Psychology of a First Message That Gets a Reply",
      de: "Warum „Hey“ ignoriert wird: Die Psychologie einer ersten Nachricht, die eine Antwort bekommt",
      fr: "Pourquoi « Hey » reste sans réponse : la psychologie d'un premier message qui fait mouche",
      es: "Por qué un \"hey\" se ignora: la psicología del primer mensaje que sí recibe respuesta",
      ar: "لماذا يُتجاهَل \"مرحبًا\"؟ سيكولوجية الرسالة الأولى التي تحصل على رد",
      ru: "Почему «привет» остаётся без ответа: психология первого сообщения, на которое отвечают",
      pt: "Por que \"oi\" é ignorado: a psicologia da primeira mensagem que recebe resposta",
      it: "Perché \"hey\" viene ignorato: la psicologia di un primo messaggio che ottiene risposta",
      ja: "なぜ「やあ」は無視されるのか──返信がもらえるファーストメッセージの心理学",
      ko: "\"안녕\"이 무시당하는 이유: 답장을 받는 첫 메시지의 심리학",
      zh: "为什么「嗨」会被无视：能收到回复的第一条消息背后的心理学",
      nl: "Waarom 'Hey' wordt genegeerd: de psychologie van een eerste bericht dat wél antwoord krijgt",
      pl: "Dlaczego „hej” jest ignorowane: psychologia pierwszej wiadomości, która dostaje odpowiedź",
      sv: "Därför ignoreras \"hej\": psykologin bakom ett första meddelande som får svar",
      hi: "\"Hey\" को क्यों नज़रअंदाज़ किया जाता है: जवाब पाने वाले पहले मैसेज का मनोविज्ञान",
    },
    excerpts: {
      tr: "Kuru bir selam hiçbir şey istemez, bu yüzden karşılığında da hiçbir şey almaz. Harvard’ın konuşma araştırmaları neyin gerçekten yanıt getirdiğini gösteriyor — ve Qulo bu soruyu her eşleşmenin içine yerleştiriyor.",
      en: "A bare greeting asks for nothing, so it gets nothing back. Harvard’s conversation research shows what actually earns a reply — and how Qulo builds that question into every match.",
      de: "Eine bloße Begrüßung verlangt nichts und bekommt deshalb nichts zurück. Harvards Gesprächsforschung zeigt, was wirklich eine Antwort bringt — und wie Qulo genau diese Frage in jedes Match einbaut.",
      fr: "Une simple salutation ne demande rien, et ne reçoit donc rien en retour. Les recherches de Harvard sur la conversation montrent ce qui déclenche vraiment une réponse — et comment Qulo intègre cette question à chaque match.",
      es: "Un saludo pelado no pide nada, así que no recibe nada. La investigación sobre conversación de Harvard muestra qué sí consigue respuesta — y cómo Qulo integra esa pregunta en cada match.",
      ar: "التحية المجردة لا تطلب شيئًا، ولذلك لا تحصل على شيء. تُظهر أبحاث المحادثة في هارفارد ما الذي يستدعي الرد فعلاً — وكيف يدمج Qulo هذا السؤال في كل تطابق.",
      ru: "Голое приветствие ни о чём не просит — и ничего не получает в ответ. Гарвардские исследования разговоров показывают, что на самом деле приносит ответ, а Qulo встраивает этот вопрос в каждый мэтч.",
      pt: "Um cumprimento seco não pede nada e, por isso, não recebe nada. A pesquisa sobre conversas de Harvard mostra o que de fato gera resposta — e como o Qulo incorpora essa pergunta em cada match.",
      it: "Un saluto secco non chiede nulla, e infatti non ottiene nulla. Le ricerche di Harvard sulla conversazione mostrano che cosa fa davvero arrivare una risposta — e come Qulo integra quella domanda in ogni match.",
      ja: "素っ気ない挨拶は何も求めないから、何も返ってきません。何が返信を引き出すのかをHarvardの会話研究が示します。そして、Quloがその質問をすべてのマッチに組み込んでいる仕組みも解説します。",
      ko: "밋밋한 인사말은 아무것도 요구하지 않기에 아무것도 얻지 못합니다. 무엇이 실제로 답장을 부르는지 하버드의 대화 연구가 보여줍니다. 그리고 Qulo는 그 질문을 모든 매칭에 심어 둡니다.",
      zh: "干巴巴的问候什么也不索取，所以什么也得不到。哈佛的对话研究揭示了究竟什么才能换来回复——以及 Qulo 如何把那个问题内置到每一次配对中。",
      nl: "Een kale begroeting vraagt niets en krijgt dus niets terug. Het gespreksonderzoek van Harvard laat zien wat wél antwoord oplevert — en hoe Qulo die vraag in elke match inbouwt.",
      pl: "Suche powitanie o nic nie prosi, więc nic nie dostaje. Harwardzkie badania nad rozmową pokazują, co naprawdę przynosi odpowiedź — i jak Qulo wbudowuje to pytanie w każde dopasowanie.",
      sv: "En naken hälsning ber inte om något och får därför inget tillbaka. Harvards samtalsforskning visar vad som faktiskt ger svar — och hur Qulo bygger in den frågan i varje matchning.",
      hi: "सूखा-सा अभिवादन कुछ माँगता ही नहीं, इसलिए बदले में कुछ मिलता भी नहीं। Harvard का बातचीत पर शोध बताता है कि जवाब असल में किससे मिलता है — और Qulo उस सवाल को हर मैच में कैसे शामिल करता है।",
    },
    keywords: [
      "first message dating app",
      "best opening lines online dating",
      "how to start a conversation on a dating app",
      "why questions get more replies",
      "dating app opener psychology",
      "ilk mesaj ne yazmalı",
      "sohbet başlatma psikolojisi",
    ],
    citations: [
      {
        title: "It Doesn't Hurt to Ask: Question-Asking Increases Liking",
        source:
          "Huang, Yeomans, Brooks, Minson & Gino — Journal of Personality and Social Psychology (2017)",
        url: "https://www.hbs.edu/ris/Publication%20Files/Huang%20et%20al%202017_6945bc5e-3b3e-4c0a-addd-254c9e603c60.pdf",
      },
      {
        title: "Taking turns: Reciprocal self-disclosure promotes liking in initial interactions",
        source:
          "Sprecher, Treger, Wondra, Hilaire & Wallpe — Journal of Experimental Social Psychology (2013)",
        url: "https://www.sciencedirect.com/science/article/abs/pii/S002210311300070X",
      },
    ],
  },
  {
    slug: "the-question-deficit",
    publishedAt: "2026-09-01",
    updatedAt: "2026-09-03",
    readingTime: 6,
    titles: {
      tr: "Soru Açığı: Neden İkiniz de Karşınızdakini İlgisiz Sanarak Ayrıldınız",
      en: "The Question Deficit: Why You Both Left Thinking the Other One Wasn't Curious",
      de: "Das Fragedefizit: Warum ihr beide dachtet, die andere Person sei nicht neugierig",
      fr: "Le déficit de questions : pourquoi vous êtes repartis tous les deux en pensant que l'autre n'était pas curieux",
      es: "El déficit de preguntas: por qué los dos os fuisteis pensando que el otro no tenía curiosidad",
      ar: "عجز الأسئلة: لماذا غادر كلاكما وهو يظن أن الآخر لم يكن فضوليًا",
      ru: "Дефицит вопросов: почему вы оба ушли с мыслью, что другому неинтересно",
      pt: "O déficit de perguntas: por que vocês dois saíram achando que o outro não tinha curiosidade",
      it: "Il deficit di domande: perché ve ne siete andati entrambi pensando che l'altro non fosse curioso",
      ja: "質問の欠乏──なぜ二人とも「相手は自分に興味がなかった」と思って帰るのか",
      ko: "질문 결핍: 왜 두 사람 모두 상대가 나에게 관심이 없었다고 생각하며 돌아갔을까",
      zh: "提问赤字：为什么你们俩都以为对方对自己毫无兴趣",
      nl: "Het vragentekort: waarom jullie allebei dachten dat de ander niet nieuwsgierig was",
      pl: "Deficyt pytań: dlaczego oboje wyszliście z przekonaniem, że druga osoba nie była ciekawa",
      sv: "Frågeunderskottet: varför ni båda gick därifrån och trodde att den andra inte var nyfiken",
      hi: "सवालों की कमी: आप दोनों यह सोचकर क्यों लौटे कि सामने वाले को कोई दिलचस्पी नहीं थी",
    },
    excerpts: {
      tr: "Karşınızdakinin size karşı meraklı olmadığını düşünerek ayrıldınız. O da tam olarak aynı şeyi düşünerek ayrıldı. İkiniz de samimisiniz — hepimiz sandığımızdan az soru soruyoruz ve ikinci buluşmayı getiren şey, karşınızdakinin az önce söylediğinden doğan takip sorusu.",
      en: "You left thinking the other person wasn’t curious about you. They left thinking exactly the same about you. Both of you are sincere — we all ask fewer questions than we believe we do, and what earns a second date is the follow-up: the question built out of what the other person just said.",
      de: "Du bist gegangen und dachtest, die andere Person sei nicht neugierig auf dich. Sie ist gegangen und dachte genau dasselbe über dich. Ihr seid beide aufrichtig — wir alle fragen weniger, als wir glauben, und über ein zweites Date entscheidet die Nachfrage: die Frage, die aus dem entsteht, was gerade gesagt wurde.",
      fr: "Vous êtes reparti en pensant que l’autre n’était pas curieux de vous. L’autre est reparti en pensant exactement la même chose. Vous êtes tous les deux sincères — nous posons tous moins de questions que nous ne le croyons, et ce qui décroche un deuxième rendez-vous, c’est la relance : la question qui naît de ce que l’autre vient de dire.",
      es: "Te fuiste pensando que la otra persona no sentía curiosidad por ti. Ella se fue pensando exactamente lo mismo de ti. Los dos sois sinceros — todos preguntamos menos de lo que creemos, y lo que consigue una segunda cita es la pregunta que nace de lo que el otro acaba de decir.",
      ar: "غادرتَ وأنت تظن أن الطرف الآخر لم يكن فضوليًا تجاهك، وغادر هو وهو يظن الشيء نفسه تمامًا عنك. كلاكما صادق — فنحن جميعًا نسأل أقل مما نتصور، وما يفتح الباب لموعد ثانٍ هو سؤال المتابعة: السؤال الذي يولد مما قاله الطرف الآخر للتو.",
      ru: "Вы ушли с мыслью, что собеседнику было неинтересно. Он ушёл ровно с той же мыслью о вас. Вы оба искренни — мы все спрашиваем меньше, чем нам кажется, а второе свидание приносит уточняющий вопрос: тот, что рождается из только что сказанного.",
      pt: "Você saiu achando que a outra pessoa não tinha curiosidade sobre você. Ela saiu achando exatamente a mesma coisa a seu respeito. Os dois são sinceros — todos perguntamos menos do que imaginamos, e o que garante um segundo encontro é a pergunta que nasce do que o outro acabou de dizer.",
      it: "Te ne sei andato pensando che l’altra persona non fosse curiosa di te. Lei se n’è andata pensando esattamente lo stesso. Siete entrambi sinceri — tutti facciamo meno domande di quante crediamo, e ciò che porta a un secondo appuntamento è la domanda che nasce da quello che l’altro ha appena detto.",
      ja: "あなたは「相手は自分に興味がなかった」と思って帰りました。相手もまったく同じことを思って帰りました。どちらの気持ちも本心です——私たちは自分で思っているほど質問できておらず、次に会えるかどうかを分けるのは、相手がいま話したことから生まれる掘り下げの質問です。",
      ko: "당신은 상대가 나에게 관심이 없다고 생각하며 자리를 떴습니다. 상대도 당신에 대해 똑같이 생각하며 자리를 떴습니다. 양쪽 모두 진심입니다 — 우리는 스스로 생각하는 것보다 질문을 적게 하고, 다음 만남을 만드는 것은 상대가 방금 한 말에서 이어지는 후속 질문입니다.",
      zh: "你离开时以为对方对你毫无兴趣。对方离开时，想的一模一样。两个人都出自真心——我们提问的次数总比自己以为的少，而真正带来下一次见面的，是顺着对方刚说的话继续追问的那一句。",
      nl: "Jij ging weg met het idee dat de ander niet nieuwsgierig naar je was. De ander ging weg met precies dezelfde gedachte. Jullie zijn allebei oprecht — we stellen allemaal minder vragen dan we denken, en wat een tweede date oplevert is de vervolgvraag: de vraag die voortkomt uit wat er net gezegd is.",
      pl: "Wyszedłeś z przekonaniem, że druga osoba nie była ciebie ciekawa. Ona wyszła dokładnie z tym samym przekonaniem o tobie. Oboje jesteście szczerzy — wszyscy zadajemy mniej pytań, niż nam się wydaje, a o kolejną randkę decyduje pytanie, które wynika z tego, co przed chwilą usłyszeliśmy.",
      sv: "Du gick därifrån och trodde att den andra inte var nyfiken på dig. Den andra gick därifrån och trodde exakt samma sak om dig. Ni är båda uppriktiga — vi frågar alla mindre än vi tror, och det som ger en andra dejt är följdfrågan: frågan som växer ur det som nyss sagts.",
      hi: "आप यह सोचकर लौटे कि सामने वाले को आपमें कोई दिलचस्पी नहीं थी। सामने वाला भी ठीक यही सोचकर लौटा। आप दोनों सच्चे हैं — हम सब अपनी सोच से कम सवाल पूछते हैं, और अगली मुलाकात उसी सवाल से मिलती है जो सामने वाले की अभी कही बात से निकलता है।",
    },
    keywords: [
      "question deficit",
      "my date didn't ask me anything",
      "why doesn't he ask me questions",
      "dating conversation gap",
      "liking gap dating",
      "buluşmada soru sormak",
      "karşımdaki bana soru sormadı",
      "soru açığı",
    ],
    citations: [
      {
        title: "It Doesn't Hurt to Ask: Question-Asking Increases Liking",
        source:
          "Huang, Yeomans, Brooks, Minson & Gino — Journal of Personality and Social Psychology 113(3), 430-452 (2017)",
        url: "https://www.hbs.edu/ris/Publication%20Files/Huang%20et%20al%202017_6945bc5e-3b3e-4c0a-addd-254c9e603c60.pdf",
      },
      {
        title: "Taking turns: Reciprocal self-disclosure promotes liking in initial interactions",
        source:
          "Sprecher, Treger, Wondra, Hilaire & Wallpe — Journal of Experimental Social Psychology (2013)",
        url: "https://www.sciencedirect.com/science/article/abs/pii/S002210311300070X",
      },
      {
        title:
          "The Experimental Generation of Interpersonal Closeness: A Procedure and Some Preliminary Findings",
        source:
          "Aron, Melinat, Aron, Vallone & Bator — Personality and Social Psychology Bulletin 23(4), 363-377 (1997)",
        url: "https://journals.sagepub.com/doi/10.1177/0146167297234003",
      },
    ],
  },
];
