/**
 * Example questions shown on /[locale]/questions.
 *
 * GENERATED by `npm run import:questions` from the app's own question library
 * (`qulo-server/src/data/seed/questions_<locale>.json`). Do not edit by hand —
 * re-run the script. Each locale's set is authored for that market rather than
 * translated, which is the whole reason this is imported instead of written.
 *
 * Two per category, four distinct answer options each.
 */
export interface ExampleQuestion {
  category: string;
  question: string;
  answers: string[];
}

/** Category order on the page. */
export const QUESTION_CATEGORIES = [
  "personality",
  "lifestyle",
  "travel",
  "food",
  "music",
  "film",
  "hobby",
  "humor",
  "sports",
  "technology",
  "fun"
] as const;

export const EXAMPLE_QUESTIONS: Record<string, ExampleQuestion[]> = {
  tr: [
    {
      category: "personality",
      question: "İlk buluşmada karşındaki kişi seni nereye götürse en çok etkilenirsin?",
      answers: ["Gizli bir kafeye","Kitapçıya","Çatıda film izlemeye","Gece müzesine"],
    },
    {
      category: "personality",
      question: "Seninle bir gün geçirecek olsam, planı kim yapsın?",
      answers: ["Ben sürpriz yaparım","Sen karar ver","Birlikte planlayalım","Akışına bırakalım"],
    },
    {
      category: "lifestyle",
      question: "Hayatta en çok neye değer verirsin?",
      answers: ["Özgürlük","Güvenlik","Tutku","Huzur"],
    },
    {
      category: "lifestyle",
      question: "İdeal hafta sonun nasıl geçer?",
      answers: ["Evde Netflix ve pijama","Dışarıda aktif bir gün","Arkadaşlarla buluşma","Doğada vakit geçirme"],
    },
    {
      category: "travel",
      question: "Kendini bir mevsimle tanımlasan hangisi olurdun?",
      answers: ["İlkbahar — yenilenme","Yaz — enerji","Sonbahar — huzur","Kış — derinlik"],
    },
    {
      category: "travel",
      question: "10 yıl sonra kendini nerede görüyorsun?",
      answers: ["Dünyayı geziyorum","Ailemi kurmuşum","Kendi işimin başındayım","Hiç bilmiyorum, sürpriz olsun"],
    },
    {
      category: "food",
      question: "Seninle yemek yapacak olsam hangi mutfağı deneyelim?",
      answers: ["İtalyan","Japon","Meksika","Türk kahvaltısı"],
    },
    {
      category: "food",
      question: "Acılı sever misin?",
      answers: ["Ne kadar acı o kadar iyi","Biraz olsun","Hiç sevmem","Isırgan acısı tamam, biber acısı hayır"],
    },
    {
      category: "music",
      question: "Partide seni nerede buluruz?",
      answers: ["Dans pistinde","Mutfakta sohbette","Balkonda hava alırken","DJ'e şarkı ısmarlarken"],
    },
    {
      category: "music",
      question: "Sabahçı mısın gececi mi?",
      answers: ["Kesinlikle sabahçı","Gece kuşuyum","İkisi arası","Uyku düzenim yok"],
    },
    {
      category: "film",
      question: "Hayatının filmi çekilse türü ne olurdu?",
      answers: ["Romantik komedi","Dram","Macera","Bilim kurgu"],
    },
    {
      category: "film",
      question: "Film türü olarak neyi tercih edersin?",
      answers: ["Romantik komedi","Aksiyon/Macera","Gerilim/Korku","Dram"],
    },
    {
      category: "hobby",
      question: "Bir hobi edinecek olsan ne olurdu?",
      answers: ["Fotoğrafçılık","Resim yapma","Bir müzik aleti","Yazarlık"],
    },
    {
      category: "hobby",
      question: "Haftasonları en çok ne yaparsın?",
      answers: ["Spor","Sanat","Sosyalleşme","Dinlenme"],
    },
    {
      category: "humor",
      question: "Bir gün boyunca sadece 3 kelime kullanabilsen hangileri olurdu?",
      answers: ["Evet, hayır, belki","Seviyorum, acıktım, uyuyacağım","Tamam, olur, gel","Neden, nasıl, nereye"],
    },
    {
      category: "humor",
      question: "Bir günlüğüne karşı cins olsan ilk ne yapardın?",
      answers: ["Aynaya bakardım","Flört ederdim","Hayatın ne kadar farklı olduğunu görürdüm","Alışveriş yapardım"],
    },
    {
      category: "sports",
      question: "Sıkıldığında ne yaparsın?",
      answers: ["İnternette dolaşırım","Birini ararım","Yeni bir şey denerim","Uyurum"],
    },
    {
      category: "sports",
      question: "Hayatta risk almayı sever misin?",
      answers: ["Evet, adrenalini severim","Hesaplı risk alırım","Güvenli olanı tercih ederim","Duruma göre değişir"],
    },
    {
      category: "technology",
      question: "iPhone mu Android mi?",
      answers: ["iPhone kesinlikle","Android, özgürlük","Hangisi elime geçerse","Telefonla ilgilenmem o kadar"],
    },
    {
      category: "technology",
      question: "Yapay zeka hakkında ne düşünürsün?",
      answers: ["Gelecek AI'da","Biraz korkutucu","Faydalı ama kontrol şart","Çok ilgilenmiyorum"],
    },
    {
      category: "fun",
      question: "Bir süper gücün olsa hangisini seçerdin?",
      answers: ["Zihin okuma","Zamanda yolculuk","Görünmezlik","Uçabilmek"],
    },
    {
      category: "fun",
      question: "Bir hayvan olsan ne olurdun?",
      answers: ["Kedi — bağımsız","Köpek — sadık","Kartal — özgür","Yunus — eğlenceli"],
    },
  ],
  en: [
    {
      category: "personality",
      question: "What would impress you most on a first date?",
      answers: ["A hidden speakeasy","A bookstore visit","Rooftop movie night","A night museum tour"],
    },
    {
      category: "personality",
      question: "How do you recharge after a long week?",
      answers: ["Solo Netflix marathon","Going out with friends","A long hike","Cooking something fancy"],
    },
    {
      category: "lifestyle",
      question: "What do you value most in life?",
      answers: ["Freedom","Security","Passion","Peace"],
    },
    {
      category: "lifestyle",
      question: "How do you start your morning?",
      answers: ["Coffee before anything","Workout first thing","Snooze the alarm 5 times","Scroll my phone in bed"],
    },
    {
      category: "travel",
      question: "If you could live in one city for a year?",
      answers: ["New York","Barcelona","Tokyo","Bali"],
    },
    {
      category: "travel",
      question: "Beach vacation or mountain retreat?",
      answers: ["Beach all the way","Mountains for sure","Beach by day, mountains nearby","Wherever has good Wi-Fi"],
    },
    {
      category: "food",
      question: "If we were cooking together, what cuisine should we try?",
      answers: ["Italian","Japanese","Mexican","Thai"],
    },
    {
      category: "food",
      question: "What's your breakfast personality?",
      answers: ["Full English fry-up","Avocado toast vibes","Just coffee, no food","Leftover pizza champion"],
    },
    {
      category: "music",
      question: "What genre is your soul made of?",
      answers: ["R&B smooth vibes","Rock energy","Hip-hop beats","Indie melancholy"],
    },
    {
      category: "music",
      question: "What's your concert vibe?",
      answers: ["Front row, screaming lyrics","Vibing in the back with a drink","VIP section if possible","I prefer intimate venues"],
    },
    {
      category: "film",
      question: "What's your go-to movie genre?",
      answers: ["Action/thriller","Romantic comedy","Sci-fi/fantasy","Drama/indie"],
    },
    {
      category: "film",
      question: "What's the perfect movie night setup?",
      answers: ["Projector, blankets, popcorn","Cinema with the big screen","Laptop in bed","Drive-in theater vibes"],
    },
    {
      category: "hobby",
      question: "What hobby have you always wanted to try?",
      answers: ["Pottery making","Learning an instrument","Scuba diving","Photography"],
    },
    {
      category: "hobby",
      question: "How do you spend a creative afternoon?",
      answers: ["Drawing or painting","Writing something","Taking photos","Rearranging my space"],
    },
    {
      category: "humor",
      question: "What's the most embarrassing song on your playlist?",
      answers: ["A Disney soundtrack","A boyband classic","Something from a commercial","I'm not embarrassed by any of them"],
    },
    {
      category: "humor",
      question: "What's the worst pickup line that would actually work on you?",
      answers: ["Are you a parking ticket? Because you've got fine written all over you","Do you have a map? I keep getting lost in your eyes","Are you Wi-Fi? Because I'm feeling a connection","None, be normal please"],
    },
    {
      category: "sports",
      question: "What sport do you follow most?",
      answers: ["Soccer/football","Basketball","Tennis","I don't follow sports"],
    },
    {
      category: "sports",
      question: "What's your ideal workout?",
      answers: ["Lifting heavy weights","Running outdoors","Yoga and stretching","Group fitness classes"],
    },
    {
      category: "technology",
      question: "iPhone or Android?",
      answers: ["iPhone, no question","Android freedom","I switch between both","Whatever works, I don't care"],
    },
    {
      category: "technology",
      question: "How do you feel about AI?",
      answers: ["Excited, it's the future","A bit nervous honestly","Fascinated but cautious","I already use it daily"],
    },
    {
      category: "fun",
      question: "If you had one superpower, what would it be?",
      answers: ["Mind reading","Time travel","Invisibility","Flying"],
    },
    {
      category: "fun",
      question: "If you won the lottery tomorrow?",
      answers: ["Travel the world first","Buy a house immediately","Invest it all","Throw the biggest party ever"],
    },
  ],
  de: [
    {
      category: "personality",
      question: "Was beeindruckt dich am meisten beim ersten Date?",
      answers: ["Ein verstecktes Speakeasy","Ein Spaziergang am Rhein","Eine Rooftop-Bar bei Nacht","Ein Besuch im Antiquariat"],
    },
    {
      category: "personality",
      question: "Wie lädst du nach einer anstrengenden Woche deine Batterien auf?",
      answers: ["Netflix-Marathon alleine","Ausgehen mit Freunden","Eine lange Wanderung","Etwas Schönes kochen"],
    },
    {
      category: "lifestyle",
      question: "Perfekter Sonntagmorgen?",
      answers: ["Brötchen vom Bäcker holen","Ausschlafen bis Mittag","Joggen im Park","Frühstück im Café"],
    },
    {
      category: "lifestyle",
      question: "Wie sieht dein idealer Feierabend aus?",
      answers: ["Sport treiben","Auf der Couch chillen","Freunde treffen","Ein neues Rezept ausprobieren"],
    },
    {
      category: "travel",
      question: "Welche deutsche Stadt würdest du für ein Wochenend-Date wählen?",
      answers: ["Berlin – Party und Kultur","München – Biergarten und Gemütlichkeit","Hamburg – Hafen und Flair","Köln – Dom und Karneval"],
    },
    {
      category: "travel",
      question: "Dein Traumurlaub mit jemandem Besonderen?",
      answers: ["Roadtrip durch die Alpen","Strandurlaub auf Mallorca","Kulturtrip in Wien","Abenteuer in Südostasien"],
    },
    {
      category: "food",
      question: "Welches Street Food liebst du am meisten?",
      answers: ["Currywurst vom Imbiss","Döner Kebab","Flammkuchen","Brezel mit Obatzda"],
    },
    {
      category: "food",
      question: "Dein Go-to-Comfort-Food?",
      answers: ["Schnitzel mit Pommes","Käsespätzle","Pizza vom Lieblingsitaliener","Omas Eintopf"],
    },
    {
      category: "music",
      question: "Welches Festival würdest du sofort besuchen?",
      answers: ["Rock am Ring","Tomorrowland","Wacken Open Air","Splash! Festival"],
    },
    {
      category: "music",
      question: "Welches Lied bringt dich sofort zum Tanzen?",
      answers: ["99 Luftballons","Ein guter Techno-Beat","80er Disco-Klassiker","Aktueller Chart-Hit"],
    },
    {
      category: "film",
      question: "Welcher deutsche Film ist dein Guilty Pleasure?",
      answers: ["Fack ju Göhte","Good Bye, Lenin!","Der Schuh des Manitu","Das Leben der Anderen"],
    },
    {
      category: "film",
      question: "Welches Film-Genre für einen Kuschelabend?",
      answers: ["Romantische Komödie","Thriller mit Spannung","Sci-Fi-Abenteuer","Dokumentation über die Welt"],
    },
    {
      category: "hobby",
      question: "Welches Hobby würdest du mit deinem Date teilen?",
      answers: ["Gemeinsam kochen","Brettspielabend","Zusammen wandern","Konzerte besuchen"],
    },
    {
      category: "hobby",
      question: "Welches Hobby hättest du gern, traust dich aber nicht?",
      answers: ["Fallschirmspringen","Stand-up-Comedy","Ein Instrument lernen","Malen oder Zeichnen"],
    },
    {
      category: "humor",
      question: "Welcher Humor-Typ bist du?",
      answers: ["Trockener Sarkasmus","Slapstick und Albernheit","Wortspiele und Kalauer","Schwarzer Humor"],
    },
    {
      category: "humor",
      question: "Was bringt dich garantiert zum Lachen?",
      answers: ["Spontane Wortwitze","Sarkastische Kommentare","Alberne Grimassen","Selbstironie"],
    },
    {
      category: "sports",
      question: "Welche Sportart findest du beim Date am coolsten?",
      answers: ["Bouldern zusammen","Kajak auf der Spree","Eislaufen","Beachvolleyball"],
    },
    {
      category: "sports",
      question: "Welche Sportart treibst du am liebsten?",
      answers: ["Fußball – Klassiker","Laufen und Fitness","Klettern und Bouldern","Ski oder Snowboard"],
    },
    {
      category: "technology",
      question: "Wie wichtig ist dir Technik im Alltag?",
      answers: ["Ohne Smartphone bin ich verloren","Ich nutze es, aber nicht exzessiv","Am liebsten Digital Detox","Ich liebe Gadgets und Neues"],
    },
    {
      category: "technology",
      question: "Apple oder Android?",
      answers: ["Apple – natürlich","Android – mehr Freiheit","Ist mir egal","Ich wechsle ständig"],
    },
    {
      category: "fun",
      question: "Welche Superkraft hättest du gern für einen Tag?",
      answers: ["Gedanken lesen","Fliegen können","Zeitreisen","Unsichtbar werden"],
    },
    {
      category: "fun",
      question: "Wenn du ein Tier wärst, welches?",
      answers: ["Ein Adler – frei und stark","Eine Katze – unabhängig","Ein Delfin – verspielt","Ein Wolf – loyal im Rudel"],
    },
  ],
  fr: [
    {
      category: "personality",
      question: "Qu'est-ce qui t'impressionnerait le plus lors d'un premier rendez-vous ?",
      answers: ["Un bar caché dans Paris","Une visite dans une librairie","Un pique-nique au bord de la Seine","Une balade dans le Marais"],
    },
    {
      category: "personality",
      question: "Comment tu recharges tes batteries après une longue semaine ?",
      answers: ["Marathon de séries","Sortie avec les potes","Randonnée en forêt","Cuisiner un bon plat"],
    },
    {
      category: "lifestyle",
      question: "C'est quoi ton dimanche idéal ?",
      answers: ["Brunch et marché aux puces","Canapé et série","Sport en plein air","Cuisiner toute la journée"],
    },
    {
      category: "lifestyle",
      question: "Quelle priorité a ta carrière dans ta vie ?",
      answers: ["C'est ma priorité numéro un","Important mais pas tout","Je préfère l'équilibre","Je vis pour profiter"],
    },
    {
      category: "travel",
      question: "Quel type de voyage tu préfères ?",
      answers: ["Sac à dos en Asie","Resort tout inclus","Road trip en Provence","Tour culturel en Europe"],
    },
    {
      category: "travel",
      question: "Mer ou montagne pour les vacances ?",
      answers: ["Côte d'Azur","Les Alpes","Un lac tranquille","Ville côtière bretonne"],
    },
    {
      category: "food",
      question: "Quel est ton plat réconfortant ?",
      answers: ["Croque-monsieur","Raclette","Gratin dauphinois","Crêpes au Nutella"],
    },
    {
      category: "food",
      question: "Quel dessert te rend le plus heureuse ?",
      answers: ["Crème brûlée","Tarte Tatin","Macaron Ladurée","Fondant au chocolat"],
    },
    {
      category: "music",
      question: "Quel genre musical te définit ?",
      answers: ["Rap français","Chanson française","Électro","Variété française"],
    },
    {
      category: "music",
      question: "Quelle chanson tu mettrais pour danser en couple ?",
      answers: ["Une chanson d'Edith Piaf","Un slow de Francis Cabrel","Quelque chose de Stromae","Du zouk"],
    },
    {
      category: "film",
      question: "Quel type de film tu préfères pour une soirée ciné ?",
      answers: ["Comédie romantique","Thriller","Film d'auteur français","Animation Pixar"],
    },
    {
      category: "film",
      question: "Quelle série te tient accrochée en ce moment ?",
      answers: ["Un drame coréen","Thriller Netflix","Comédie légère","Docu intéressant"],
    },
    {
      category: "hobby",
      question: "Quel hobby tu aimerais apprendre en couple ?",
      answers: ["Danse salsa","Cuisine du monde","Escalade","Photographie"],
    },
    {
      category: "hobby",
      question: "Quel hobby secret tu as ?",
      answers: ["Écrire de la poésie","Peindre ou dessiner","Faire du DIY","Chanter quand personne n'écoute"],
    },
    {
      category: "humor",
      question: "Quelle serait ton excuse la plus créative pour arriver en retard à un date ?",
      answers: ["Je me suis perdu en regardant des memes","Mon chat a caché mes clés","Le GPS m'a emmené dans une autre ville","Je choisissais la playlist parfaite"],
    },
    {
      category: "humor",
      question: "Que ferais-tu si ton date se pointe avec des fleurs fanées ?",
      answers: ["Je rigole et trouve ça adorable","Je fais semblant de pas voir","Je lui apprends à choisir des fleurs","Je les mets dans l'eau en espérant"],
    },
    {
      category: "sports",
      question: "Quel sport te passionne ?",
      answers: ["Football","Tennis","Escalade","Running"],
    },
    {
      category: "sports",
      question: "Quelle activité physique te motive le plus ?",
      answers: ["Pilates","Danse","Natation","Randonnée"],
    },
    {
      category: "technology",
      question: "Comment tu utilises ton téléphone en couple ?",
      answers: ["Messages constants","Appels importants uniquement","Partage de memes et reels","Le minimum possible"],
    },
    {
      category: "technology",
      question: "Tu mets combien de temps pour répondre à un message de quelqu'un qui te plaît ?",
      answers: ["Instantanément","J'attends pour pas paraître trop intense","Quand j'y pense","Ça dépend de mon humeur"],
    },
    {
      category: "fun",
      question: "Quel superpouvoir tu choisirais ?",
      answers: ["Téléportation","Lire dans les pensées","Voler","Voyager dans le temps"],
    },
    {
      category: "fun",
      question: "Si tu étais un personnage de série française, lequel serais-tu ?",
      answers: ["La protagoniste dramatique","La méchante avec du style","La meilleure amie drôle","La mystérieuse qui arrive à la fin"],
    },
  ],
  es: [
    {
      category: "personality",
      question: "¿Qué harías en una primera cita perfecta?",
      answers: ["Cena en un restaurante escondido","Paseo por el centro histórico","Noche de cine al aire libre","Tomar churros con chocolate"],
    },
    {
      category: "personality",
      question: "¿Cómo recargas energía después de una semana larga?",
      answers: ["Maratón de series","Salir con amigos de cañas","Una ruta de senderismo","Cocinar algo especial"],
    },
    {
      category: "lifestyle",
      question: "¿Cómo es tu domingo ideal?",
      answers: ["Brunch y mercadillo","Sofá y serie","Deporte al aire libre","Cocinar todo el día"],
    },
    {
      category: "lifestyle",
      question: "¿Qué prioridad tiene tu carrera en tu vida?",
      answers: ["Es lo primero","Importante pero no todo","Prefiero equilibrio","Vivo para disfrutar"],
    },
    {
      category: "travel",
      question: "¿Qué tipo de viaje prefieres?",
      answers: ["Mochilero por Sudamérica","Resort todo incluido","Road trip por España","Ruta cultural por Europa"],
    },
    {
      category: "travel",
      question: "¿Playa o montaña para las vacaciones?",
      answers: ["Playa caribeña","Sierra Nevada","Un lago tranquilo","Ciudad costera"],
    },
    {
      category: "food",
      question: "¿Cuál es tu comida reconfortante?",
      answers: ["Tortilla de patatas","Tacos al pastor","Paella valenciana","Empanadas argentinas"],
    },
    {
      category: "food",
      question: "¿Qué postre te hace más feliz?",
      answers: ["Churros con chocolate","Flan casero","Tres leches","Helado artesanal"],
    },
    {
      category: "music",
      question: "¿Qué género musical te define?",
      answers: ["Reggaetón","Flamenco","Rock en español","Salsa y bachata"],
    },
    {
      category: "music",
      question: "¿Qué canción pondrías para bailar en pareja?",
      answers: ["Bachata de Romeo Santos","Flamenco pop","Un bolero clásico","Reggaetón suave"],
    },
    {
      category: "film",
      question: "¿Qué tipo de películas prefieres en una cita?",
      answers: ["Comedia romántica","Thriller de suspenso","Drama profundo","Animación de Pixar"],
    },
    {
      category: "film",
      question: "¿Qué serie te tiene enganchada ahora?",
      answers: ["Un drama coreano","Thriller de Netflix","Comedia ligera","Documental interesante"],
    },
    {
      category: "hobby",
      question: "¿Qué hobby te gustaría aprender en pareja?",
      answers: ["Baile de salsa","Cocina internacional","Escalada","Fotografía"],
    },
    {
      category: "hobby",
      question: "¿Qué hobby secreto tienes?",
      answers: ["Escribir poesía","Pintar o dibujar","Hacer manualidades","Cantar cuando nadie escucha"],
    },
    {
      category: "humor",
      question: "¿Cuál sería tu excusa más creativa para llegar tarde a una cita?",
      answers: ["Me perdí mirando memes","Mi gato escondió mis llaves","El GPS me llevó a otra ciudad","Estaba eligiendo la playlist perfecta"],
    },
    {
      category: "humor",
      question: "¿Qué harías si tu cita se presenta con flores marchitas?",
      answers: ["Me reiría y lo encontraría adorable","Fingiría que no las vi","Le enseñaría a elegir flores","Las pondría en agua con esperanza"],
    },
    {
      category: "sports",
      question: "¿Qué deporte te apasiona?",
      answers: ["Fútbol","Pádel","Surf","Running"],
    },
    {
      category: "sports",
      question: "¿Qué actividad física te motiva más?",
      answers: ["Pilates","Baile","Natación","Senderismo"],
    },
    {
      category: "technology",
      question: "¿Cómo usas tu móvil en una relación?",
      answers: ["Mensajes constantes","Solo llamadas importantes","Compartir memes y reels","Lo mínimo posible"],
    },
    {
      category: "technology",
      question: "¿Cuánto tardas en responder un mensaje de alguien que te gusta?",
      answers: ["Al instante","Espero un rato para no parecer intensa","Cuando me acuerdo","Depende de mi humor"],
    },
    {
      category: "fun",
      question: "¿Qué superpoder elegirías?",
      answers: ["Teletransportación","Leer la mente","Volar","Viajar en el tiempo"],
    },
    {
      category: "fun",
      question: "Si fueras un personaje de telenovela, ¿cuál serías?",
      answers: ["La protagonista dramática","La villana con estilo","La mejor amiga graciosa","La misteriosa que llega al final"],
    },
  ],
  ar: [
    {
      category: "personality",
      question: "ماذا يثير إعجابك في أول موعد؟",
      answers: ["مقهى مخفي في حي قديم","جولة في سوق تقليدي","عشاء على سطح بإطلالة","مشي على الكورنيش"],
    },
    {
      category: "personality",
      question: "كيف تعيد شحن طاقتك بعد أسبوع طويل؟",
      answers: ["ماراثون مسلسلات","خروج مع الأصدقاء","رحلة للطبيعة","طبخ شيء مميز"],
    },
    {
      category: "lifestyle",
      question: "كيف يومك المثالي يوم الجمعة؟",
      answers: ["فطور متأخر وسوق شعبي","كنبة ومسلسل","رياضة في الهواء الطلق","طبخ طوال اليوم"],
    },
    {
      category: "lifestyle",
      question: "ما أهمية عملك في حياتك؟",
      answers: ["هو الأولوية الأولى","مهم لكن مو كل شيء","أفضل التوازن","أعيش لأستمتع"],
    },
    {
      category: "travel",
      question: "أي نوع سفر تفضل؟",
      answers: ["باكباكر في جنوب شرق آسيا","منتجع شامل","رحلة بالسيارة في المغرب","جولة ثقافية في أوروبا"],
    },
    {
      category: "travel",
      question: "بحر أم جبل للإجازة؟",
      answers: ["شاطئ استوائي","جبال لبنان","بحيرة هادئة","مدينة ساحلية"],
    },
    {
      category: "food",
      question: "ما هو أكلك المفضل للراحة؟",
      answers: ["شاورما","كبسة","كشري","منسف"],
    },
    {
      category: "food",
      question: "أي حلو يسعدك أكثر؟",
      answers: ["كنافة نابلسية","أم علي","بقلاوة","آيس كريم يدوي"],
    },
    {
      category: "music",
      question: "أي نوع موسيقى يعبر عنك؟",
      answers: ["راب عربي","طرب كلاسيكي","بوب عربي","خليجي"],
    },
    {
      category: "music",
      question: "أي أغنية تحطينها للرقص مع شريكك؟",
      answers: ["أغنية فيروز","أغنية عمرو دياب","أغنية نانسي عجرم","أغنية خليجية حماسية"],
    },
    {
      category: "film",
      question: "أي نوع أفلام تفضل في موعد؟",
      answers: ["كوميديا رومانسية","إثارة وتشويق","دراما عميقة","أنيميشن بيكسار"],
    },
    {
      category: "film",
      question: "أي مسلسل يشدك الحين؟",
      answers: ["دراما كورية","إثارة نتفلكس","كوميديا خفيفة","وثائقي مثير"],
    },
    {
      category: "hobby",
      question: "أي هواية تحب تتعلمها مع شريكك؟",
      answers: ["رقص السالسا","طبخ عالمي","تسلق","تصوير"],
    },
    {
      category: "hobby",
      question: "ما هوايتك السرية؟",
      answers: ["كتابة شعر","رسم","أشغال يدوية","غناء لما محد يسمع"],
    },
    {
      category: "humor",
      question: "ما أكثر عذر إبداعي للتأخر عن موعد؟",
      answers: ["ضعت وأنا أشوف ميمز","قطتي خبت مفاتيحي","الخرائط وداني مدينة ثانية","كنت أختار البلايلست المثالية"],
    },
    {
      category: "humor",
      question: "ماذا تفعلين لو موعدك جاب ورد ذابل؟",
      answers: ["أضحك وأحسه لطيف","أتظاهر إني ما شفته","أعلمه يختار ورد","أحطه بالماء وإن شاء الله يعيش"],
    },
    {
      category: "sports",
      question: "أي رياضة تعشقها؟",
      answers: ["كرة قدم","بادل","سباحة","جري"],
    },
    {
      category: "sports",
      question: "أي نشاط بدني يحفزك أكثر؟",
      answers: ["بيلاتس","رقص","سباحة","مشي في الطبيعة"],
    },
    {
      category: "technology",
      question: "كيف تستخدم جوالك في العلاقة؟",
      answers: ["رسائل مستمرة","مكالمات مهمة فقط","مشاركة ميمز وريلز","أقل استخدام ممكن"],
    },
    {
      category: "technology",
      question: "كم تأخذين وقت ترد على رسالة من شخص يعجبك؟",
      answers: ["فوراً","أنتظر شوي عشان ما أبان متحمسة","لما أتذكر","حسب مزاجي"],
    },
    {
      category: "fun",
      question: "أي قوة خارقة تختار؟",
      answers: ["الانتقال الآني","قراءة الأفكار","الطيران","السفر عبر الزمن"],
    },
    {
      category: "fun",
      question: "لو كنتِ شخصية في مسلسل عربي، مين تكونين؟",
      answers: ["البطلة الدرامية","الشريرة الأنيقة","الصاحبة المضحكة","الغامضة اللي تظهر آخر شيء"],
    },
  ],
  ru: [
    {
      category: "personality",
      question: "Что впечатлит тебя больше всего на первом свидании?",
      answers: ["Скрытый бар-спикизи","Прогулка по книжному магазину","Кино на крыше","Ночная экскурсия в музей"],
    },
    {
      category: "personality",
      question: "Как ты восстанавливаешься после тяжёлой недели?",
      answers: ["Марафон сериалов в одиночестве","Тусовка с друзьями","Долгая прогулка на природе","Готовлю что-нибудь изысканное"],
    },
    {
      category: "lifestyle",
      question: "Утренний ритуал — какой он у тебя?",
      answers: ["Спорт и завтрак","Кофе и новости","Максимально быстрые сборы","Медитация и благодарность"],
    },
    {
      category: "lifestyle",
      question: "Город или деревня?",
      answers: ["Город — мне нужен ритм","Деревня — тишина и природа","Пригород — золотая середина","Город сейчас, деревня потом"],
    },
    {
      category: "travel",
      question: "Куда ты хочешь поехать больше всего?",
      answers: ["Япония","Италия","Исландия","Бразилия"],
    },
    {
      category: "travel",
      question: "Какой тип отпуска тебе ближе?",
      answers: ["Пляж и релакс","Городской туризм","Горы и природа","Культурное погружение"],
    },
    {
      category: "food",
      question: "Какая кухня — твоя любимая?",
      answers: ["Итальянская","Японская","Мексиканская","Грузинская"],
    },
    {
      category: "food",
      question: "Как ты относишься к острой еде?",
      answers: ["Чем острее — тем лучше","Немного перчика — да","Только мягкое","Зависит от блюда"],
    },
    {
      category: "music",
      question: "Какой жанр музыки ты слушаешь чаще всего?",
      answers: ["Поп","Рок","Хип-хоп/Рэп","Электронная"],
    },
    {
      category: "music",
      question: "Караоке — какую песню споёшь?",
      answers: ["Классику 90-х","Современный хит","Рок-балладу","Я не пою — танцую"],
    },
    {
      category: "film",
      question: "Какой жанр фильмов ты предпочитаешь?",
      answers: ["Комедия","Триллер","Романтика","Фантастика"],
    },
    {
      category: "film",
      question: "Кино или сериал?",
      answers: ["Кино — за два часа вся история","Сериал — люблю погружаться","Зависит от настроения","Документалки — я интеллектуал"],
    },
    {
      category: "hobby",
      question: "Какое хобби ты бы хотел попробовать?",
      answers: ["Рисование","Серфинг","Гончарное дело","Фотографию"],
    },
    {
      category: "hobby",
      question: "Как ты проводишь свободное время?",
      answers: ["Читаю книги","Играю в игры","Творю что-нибудь","Гуляю и исследую"],
    },
    {
      category: "humor",
      question: "Какой мем описывает твою жизнь?",
      answers: ["Это нормально (с огнём вокруг)","Девушка с математикой в голове","Кот за столом","Ты не ты, когда голоден"],
    },
    {
      category: "humor",
      question: "Худшая тема для разговора на первом свидании?",
      answers: ["Бывшие","Политика","Сколько зарабатываешь","Планы на свадьбу"],
    },
    {
      category: "sports",
      question: "Какой вид спорта тебе нравится больше всего?",
      answers: ["Футбол","Баскетбол","Теннис","Я за йогу"],
    },
    {
      category: "sports",
      question: "Бег по утрам — ты за или против?",
      answers: ["За — бегаю регулярно","Хочу начать, но лень","Только если кто-то гонится","Бег — это для утренних людей"],
    },
    {
      category: "technology",
      question: "Apple или Android?",
      answers: ["Apple — без вариантов","Android — свобода выбора","Мне всё равно","У меня оба"],
    },
    {
      category: "technology",
      question: "Как ты относишься к искусственному интеллекту?",
      answers: ["Это будущее","Немного пугает","Уже пользуюсь каждый день","Пусть роботы работают, а я отдыхаю"],
    },
    {
      category: "fun",
      question: "Если бы ты был животным, кем бы был?",
      answers: ["Кот — независимый","Собака — верный друг","Орёл — свобода","Дельфин — умный и весёлый"],
    },
    {
      category: "fun",
      question: "Что самое смелое, что ты делал?",
      answers: ["Прыжок с парашютом","Переезд в новый город","Заговорил с незнакомцем, который понравился","Уволился без плана"],
    },
  ],
  pt: [
    {
      category: "personality",
      question: "O que te impressionaria mais num primeiro encontro?",
      answers: ["Um bar secreto no centro","Visita a um sebo","Piquenique na praia ao pôr do sol","Passeio pelo bairro histórico"],
    },
    {
      category: "personality",
      question: "Como você recarrega as energias depois de uma semana puxada?",
      answers: ["Maratona de séries","Sair com os amigos","Trilha na natureza","Cozinhar algo especial"],
    },
    {
      category: "lifestyle",
      question: "Como é seu domingo ideal?",
      answers: ["Brunch e feira","Sofá e série","Esporte ao ar livre","Cozinhar o dia todo"],
    },
    {
      category: "lifestyle",
      question: "Qual prioridade sua carreira tem na sua vida?",
      answers: ["É a primeira","Importante mas não tudo","Prefiro equilíbrio","Vivo pra curtir"],
    },
    {
      category: "travel",
      question: "Que tipo de viagem você prefere?",
      answers: ["Mochilão pela América do Sul","Resort all inclusive","Road trip pelo Nordeste","Rota cultural pela Europa"],
    },
    {
      category: "travel",
      question: "Praia ou montanha nas férias?",
      answers: ["Praia nordestina","Serra gaúcha","Lago tranquilo","Cidade litorânea"],
    },
    {
      category: "food",
      question: "Qual sua comida de conforto?",
      answers: ["Feijoada completa","Coxinha","Pão de queijo quentinho","Açaí na tigela"],
    },
    {
      category: "food",
      question: "Qual sobremesa te faz mais feliz?",
      answers: ["Brigadeiro","Pudim de leite","Açaí caprichado","Bolo de cenoura com chocolate"],
    },
    {
      category: "music",
      question: "Qual gênero musical te define?",
      answers: ["Sertanejo","Funk","MPB","Pagode"],
    },
    {
      category: "music",
      question: "Qual música você colocaria pra dançar em casal?",
      answers: ["Forró pé de serra","Pagode romântico","Sertanejo universitário","MPB suave"],
    },
    {
      category: "film",
      question: "Que tipo de filme você prefere num encontro?",
      answers: ["Comédia romântica","Thriller de suspense","Drama profundo","Animação da Pixar"],
    },
    {
      category: "film",
      question: "Qual série te prende agora?",
      answers: ["K-drama","Thriller da Netflix","Comédia leve","Documentário interessante"],
    },
    {
      category: "hobby",
      question: "Qual hobby você gostaria de aprender em casal?",
      answers: ["Dança de forró","Culinária internacional","Escalada","Fotografia"],
    },
    {
      category: "hobby",
      question: "Qual hobby secreto você tem?",
      answers: ["Escrever poesia","Pintar ou desenhar","Fazer artesanato","Cantar quando ninguém ouve"],
    },
    {
      category: "humor",
      question: "Qual seria sua desculpa mais criativa pra chegar atrasado num date?",
      answers: ["Me perdi vendo memes","Meu gato escondeu minhas chaves","O GPS me levou pra outra cidade","Tava escolhendo a playlist perfeita"],
    },
    {
      category: "humor",
      question: "O que você faria se seu date aparecesse com flores murchas?",
      answers: ["Ria e acharia fofo","Fingiria que não vi","Ensinaria a escolher flores","Colocaria na água com esperança"],
    },
    {
      category: "sports",
      question: "Qual esporte te apaixona?",
      answers: ["Futebol","Surfe","Vôlei de praia","Corrida"],
    },
    {
      category: "sports",
      question: "Qual atividade física te motiva mais?",
      answers: ["Pilates","Dança","Natação","Caminhada na natureza"],
    },
    {
      category: "technology",
      question: "Como você usa o celular no relacionamento?",
      answers: ["Mensagens constantes","Só ligações importantes","Compartilhar memes e reels","O mínimo possível"],
    },
    {
      category: "technology",
      question: "Quanto tempo você demora pra responder quem te interessa?",
      answers: ["Na hora","Espero um pouco pra não parecer ansiosa","Quando lembro","Depende do meu humor"],
    },
    {
      category: "fun",
      question: "Qual superpoder você escolheria?",
      answers: ["Teletransporte","Ler mentes","Voar","Viajar no tempo"],
    },
    {
      category: "fun",
      question: "Se fosse uma personagem de novela, qual seria?",
      answers: ["A protagonista dramática","A vilã com estilo","A melhor amiga engraçada","A misteriosa que chega no final"],
    },
  ],
  it: [
    {
      category: "personality",
      question: "Cosa ti colpirebbe di più al primo appuntamento?",
      answers: ["Un bar segreto nascosto","Una passeggiata in libreria","Cinema sul tetto","Visita notturna al museo"],
    },
    {
      category: "personality",
      question: "Come ti ricarichi dopo una settimana pesante?",
      answers: ["Maratona di serie TV da solo","Uscire con gli amici","Una lunga passeggiata nella natura","Cucinare qualcosa di speciale"],
    },
    {
      category: "lifestyle",
      question: "Rituale mattutino — quale è il tuo?",
      answers: ["Sport e colazione","Caffè e notizie","Mi preparo il più veloce possibile","Meditazione e gratitudine"],
    },
    {
      category: "lifestyle",
      question: "Città o campagna?",
      answers: ["Città — ho bisogno del ritmo","Campagna — silenzio e natura","Periferia — via di mezzo","Città ora, campagna dopo"],
    },
    {
      category: "travel",
      question: "Dove vorresti andare più di tutto?",
      answers: ["Giappone","Islanda","Brasile","Australia"],
    },
    {
      category: "travel",
      question: "Che tipo di vacanza preferisci?",
      answers: ["Spiaggia e relax","Turismo urbano","Montagna e natura","Immersione culturale"],
    },
    {
      category: "food",
      question: "Qual è la tua cucina preferita?",
      answers: ["Italiana ovviamente","Giapponese","Messicana","Francese"],
    },
    {
      category: "food",
      question: "Come ti comporti con il cibo piccante?",
      answers: ["Più piccante è, meglio è","Un po' di peperoncino — sì","Solo cose delicate","Dipende dal piatto"],
    },
    {
      category: "music",
      question: "Quale genere musicale ascolti di più?",
      answers: ["Pop","Rock","Hip-hop/Rap","Elettronica"],
    },
    {
      category: "music",
      question: "Karaoke — quale canzone canti?",
      answers: ["Un classico italiano","Hit internazionale","Ballata rock","Non canto — ballo"],
    },
    {
      category: "film",
      question: "Quale genere di film preferisci?",
      answers: ["Commedia","Thriller","Romantico","Fantascienza"],
    },
    {
      category: "film",
      question: "Film o serie TV?",
      answers: ["Film — tutta la storia in due ore","Serie — amo immergermi","Dipende dall'umore","Documentari — sono intellettuale"],
    },
    {
      category: "hobby",
      question: "Quale hobby vorresti provare?",
      answers: ["Dipingere","Surf","Ceramica","Fotografia"],
    },
    {
      category: "hobby",
      question: "Come passi il tempo libero?",
      answers: ["Leggo libri","Gioco ai videogiochi","Creo qualcosa","Passeggio e esploro"],
    },
    {
      category: "humor",
      question: "Quale meme descrive la tua vita?",
      answers: ["Questo va bene (con il fuoco intorno)","Ragazza con i calcoli in testa","Gatto al tavolo","Non sei tu quando hai fame"],
    },
    {
      category: "humor",
      question: "Peggior argomento al primo appuntamento?",
      answers: ["Ex","Politica","Quanto guadagni","Piani per il matrimonio"],
    },
    {
      category: "sports",
      question: "Quale sport ti piace di più?",
      answers: ["Calcio","Tennis","Nuoto","Io sto con lo yoga"],
    },
    {
      category: "sports",
      question: "Corsa mattutina — sei pro o contro?",
      answers: ["Pro — corro regolarmente","Vorrei iniziare, ma pigrizia","Solo se qualcuno mi insegue","La corsa è per le persone mattiniere"],
    },
    {
      category: "technology",
      question: "Apple o Android?",
      answers: ["Apple — senza dubbio","Android — libertà di scelta","Non mi importa","Li ho entrambi"],
    },
    {
      category: "technology",
      question: "Come ti rapporti con l'intelligenza artificiale?",
      answers: ["È il futuro","Mi spaventa un po'","La uso già ogni giorno","Che i robot lavorino, io mi riposo"],
    },
    {
      category: "fun",
      question: "Se fossi un animale, quale saresti?",
      answers: ["Gatto — indipendente","Cane — amico fedele","Aquila — libertà","Delfino — intelligente e giocoso"],
    },
    {
      category: "fun",
      question: "Qual è la cosa più coraggiosa che hai fatto?",
      answers: ["Paracadutismo","Trasferirmi in una nuova città","Parlare a uno sconosciuto che mi piaceva","Lasciare il lavoro senza un piano"],
    },
  ],
  ja: [
    {
      category: "personality",
      question: "初デートで一番印象に残ることは？",
      answers: ["隠れ家バーに連れて行ってくれる","下北沢で古本屋巡り","東京タワーの夜景","美術館デート"],
    },
    {
      category: "personality",
      question: "疲れた週末のリフレッシュ方法は？",
      answers: ["アニメ一気見","友達と居酒屋","温泉でゆっくり","カフェで読書"],
    },
    {
      category: "lifestyle",
      question: "理想の日曜日の朝は？",
      answers: ["コンビニでおにぎり買って公園","昼まで寝る","朝ランニング","モーニングのあるカフェ"],
    },
    {
      category: "lifestyle",
      question: "仕事終わりの過ごし方は？",
      answers: ["ジムで筋トレ","ソファでゴロゴロ","友達と飲みに行く","新しいレシピに挑戦"],
    },
    {
      category: "travel",
      question: "デートで行きたい日本の場所は？",
      answers: ["京都 – 着物で散策","沖縄 – ビーチリゾート","北海道 – 美食の旅","鎌倉 – 江ノ電デート"],
    },
    {
      category: "travel",
      question: "特別な人との理想の旅行先は？",
      answers: ["パリ – 愛の街","ハワイ – 南国パラダイス","ニューヨーク – 大都会","バリ島 – 熱帯の楽園"],
    },
    {
      category: "food",
      question: "一番好きなストリートフードは？",
      answers: ["たこ焼き","焼き鳥","クレープ","たい焼き"],
    },
    {
      category: "food",
      question: "元気が出るご飯は？",
      answers: ["ラーメン一択","焼肉","お寿司","お母さんの手料理"],
    },
    {
      category: "music",
      question: "フェスに行くならどれ？",
      answers: ["フジロック","サマソニ","ROCK IN JAPAN","コーチェラに行きたい"],
    },
    {
      category: "music",
      question: "すぐ踊り出す曲は？",
      answers: ["YOASOBI – 夜に駆ける","テクノビート","80年代シティポップ","最新J-POP"],
    },
    {
      category: "film",
      question: "好きなジブリ映画は？",
      answers: ["千と千尋の神隠し","もののけ姫","天空の城ラピュタ","となりのトトロ"],
    },
    {
      category: "film",
      question: "おうちデートで観るジャンルは？",
      answers: ["ラブコメ","サスペンス","SF映画","ドキュメンタリー"],
    },
    {
      category: "hobby",
      question: "デートで共有したい趣味は？",
      answers: ["一緒に料理する","ゲーム対戦","散歩やハイキング","カラオケ"],
    },
    {
      category: "hobby",
      question: "やってみたいけど勇気がない趣味は？",
      answers: ["スカイダイビング","お笑いライブに出る","楽器を始める","絵を描く"],
    },
    {
      category: "humor",
      question: "どんなユーモアが好き？",
      answers: ["シュールなボケ","ツッコミ芸","ダジャレ","ブラックユーモア"],
    },
    {
      category: "humor",
      question: "絶対笑っちゃうことは？",
      answers: ["予想外のボケ","的確なツッコミ","変顔","自虐ネタ"],
    },
    {
      category: "sports",
      question: "デートでやりたいスポーツは？",
      answers: ["ボルダリング","サーフィン体験","卓球","ビーチバレー"],
    },
    {
      category: "sports",
      question: "よくやるスポーツは？",
      answers: ["サッカー","ランニングと筋トレ","テニス","スキー・スノーボード"],
    },
    {
      category: "technology",
      question: "テクノロジーとの付き合い方は？",
      answers: ["スマホなしでは生きられない","使うけど依存はしない","デジタルデトックスしたい","ガジェット大好き"],
    },
    {
      category: "technology",
      question: "iPhone派？Android派？",
      answers: ["iPhone – もちろん","Android – 自由度が高い","どっちでもいい","よく変える"],
    },
    {
      category: "fun",
      question: "一日だけ超能力を持てるなら？",
      answers: ["テレパシー","空を飛ぶ","タイムトラベル","透明になれる"],
    },
    {
      category: "fun",
      question: "もし動物に生まれ変わるなら？",
      answers: ["鷹 – 自由に空を飛ぶ","猫 – 気ままな生活","イルカ – 海で遊ぶ","柴犬 – 愛される存在"],
    },
  ],
  ko: [
    {
      category: "personality",
      question: "첫 데이트에서 가장 감동받을 장소는?",
      answers: ["숨겨진 스피크이지 바","서점 데이트","옥상 영화관","야간 미술관 투어"],
    },
    {
      category: "personality",
      question: "힘든 한 주 후에 어떻게 충전해?",
      answers: ["혼자 넷플릭스 정주행","친구들이랑 나가기","자연 속 긴 산책","맛있는 거 요리하기"],
    },
    {
      category: "lifestyle",
      question: "아침 루틴은?",
      answers: ["운동과 아침식사","커피와 뉴스","최대한 빨리 준비","명상과 감사"],
    },
    {
      category: "lifestyle",
      question: "도시 vs 시골?",
      answers: ["도시 — 빠른 리듬이 필요해","시골 — 조용함과 자연","외곽 — 딱 좋은 중간","지금은 도시, 나중에 시골"],
    },
    {
      category: "travel",
      question: "가장 가고 싶은 여행지는?",
      answers: ["일본","이탈리아","아이슬란드","브라질"],
    },
    {
      category: "travel",
      question: "어떤 타입의 휴가를 좋아해?",
      answers: ["해변에서 릴렉스","도시 관광","산과 자연","문화 체험"],
    },
    {
      category: "food",
      question: "가장 좋아하는 음식 종류는?",
      answers: ["한식","일식","이탈리안","멕시칸"],
    },
    {
      category: "food",
      question: "매운 음식 어때?",
      answers: ["매울수록 좋아","약간의 맵기는 OK","맵지 않은 것만","음식에 따라 달라"],
    },
    {
      category: "music",
      question: "가장 많이 듣는 음악 장르는?",
      answers: ["K-pop","힙합/R&B","밴드/록","인디"],
    },
    {
      category: "music",
      question: "노래방 — 어떤 노래 불러?",
      answers: ["90년대 가요","최신 히트곡","발라드","안 불러 — 춤만 춰"],
    },
    {
      category: "film",
      question: "좋아하는 영화 장르는?",
      answers: ["코미디","스릴러","로맨스","SF"],
    },
    {
      category: "film",
      question: "영화 vs 드라마?",
      answers: ["영화 — 2시간에 완결","드라마 — 몰입감이 좋아","기분에 따라","다큐 — 나는 지식인"],
    },
    {
      category: "hobby",
      question: "해보고 싶은 취미는?",
      answers: ["그림 그리기","서핑","도예","사진 촬영"],
    },
    {
      category: "hobby",
      question: "여가 시간에 뭐 해?",
      answers: ["독서","게임","뭔가 만들기","산책하고 탐험"],
    },
    {
      category: "humor",
      question: "내 인생을 설명하는 밈은?",
      answers: ["괜찮아 (불 속에서)","머릿속 수학 여자","테이블 앞 고양이","배고프면 너답지 않아"],
    },
    {
      category: "humor",
      question: "첫 데이트에서 최악의 대화 주제는?",
      answers: ["전 애인","정치","연봉","결혼 계획"],
    },
    {
      category: "sports",
      question: "가장 좋아하는 스포츠는?",
      answers: ["축구","야구","테니스","요가"],
    },
    {
      category: "sports",
      question: "아침 러닝 — 찬성? 반대?",
      answers: ["찬성 — 꾸준히 뛰어","하고 싶은데 귀찮아","누가 쫓아올 때만","아침형은 아니라서"],
    },
    {
      category: "technology",
      question: "아이폰 vs 안드로이드?",
      answers: ["아이폰 — 무조건","안드로이드 — 자유로운 선택","상관없어","둘 다 있어"],
    },
    {
      category: "technology",
      question: "AI에 대해 어떻게 생각해?",
      answers: ["미래야","좀 무서워","매일 쓰고 있어","로봇이 일하면 나는 쉰다"],
    },
    {
      category: "fun",
      question: "동물이 된다면 뭐가 될래?",
      answers: ["고양이 — 독립적","강아지 — 충실한 친구","독수리 — 자유","돌고래 — 똑똑하고 장난기"],
    },
    {
      category: "fun",
      question: "지금까지 한 가장 용감한 일은?",
      answers: ["스카이다이빙","새로운 도시로 이사","좋아하는 사람에게 먼저 말 걸기","계획 없이 퇴사"],
    },
  ],
  zh: [
    {
      category: "personality",
      question: "第一次约会，什么最让你印象深刻？",
      answers: ["一家隐藏的酒吧","去书店逛逛","外滩夜景散步","美术馆约会"],
    },
    {
      category: "personality",
      question: "累了一周怎么给自己充电？",
      answers: ["追剧马拉松","和朋友出去嗨","爬山徒步","做顿好吃的"],
    },
    {
      category: "lifestyle",
      question: "完美的周日早晨？",
      answers: ["去买豆浆油条","睡到中午","晨跑","咖啡店吃早午餐"],
    },
    {
      category: "lifestyle",
      question: "下班后怎么过？",
      answers: ["去健身房","窝在沙发上","和朋友出去","试个新食谱"],
    },
    {
      category: "travel",
      question: "约会想去中国哪个城市？",
      answers: ["成都——火锅和熊猫","杭州——西湖浪漫","厦门——文艺小清新","大理——风花雪月"],
    },
    {
      category: "travel",
      question: "和特别的人的梦想旅行？",
      answers: ["巴黎——爱情之都","马尔代夫——水上屋","瑞士——雪山","巴厘岛——热带天堂"],
    },
    {
      category: "food",
      question: "最爱的街边小吃？",
      answers: ["煎饼果子","烤串","臭豆腐","麻辣烫"],
    },
    {
      category: "food",
      question: "你的comfort food是什么？",
      answers: ["妈妈做的红烧肉","火锅","一碗热汤面","炒饭"],
    },
    {
      category: "music",
      question: "想去哪个音乐节？",
      answers: ["草莓音乐节","迷笛音乐节","电音节","出国去Coachella"],
    },
    {
      category: "music",
      question: "什么歌让你立刻想跳舞？",
      answers: ["抖音神曲","电子音乐","复古迪斯科","最新流行歌"],
    },
    {
      category: "film",
      question: "你的guilty pleasure中国电影？",
      answers: ["大话西游","功夫","夏洛特烦恼","你好，李焕英"],
    },
    {
      category: "film",
      question: "窝在家看什么类型的片？",
      answers: ["浪漫喜剧","悬疑惊悚","科幻片","纪录片"],
    },
    {
      category: "hobby",
      question: "约会想分享什么爱好？",
      answers: ["一起做饭","桌游之夜","一起爬山","去看演出"],
    },
    {
      category: "hobby",
      question: "想尝试但没勇气的爱好？",
      answers: ["跳伞","尝试脱口秀","学乐器","画画"],
    },
    {
      category: "humor",
      question: "你属于哪种幽默风格？",
      answers: ["冷幽默","无厘头搞笑","谐音梗","黑色幽默"],
    },
    {
      category: "humor",
      question: "什么一定能让你笑？",
      answers: ["突然的冷笑话","精准的吐槽","搞怪表情","自嘲"],
    },
    {
      category: "sports",
      question: "约会想一起做什么运动？",
      answers: ["攀岩","滑冰","乒乓球","骑行"],
    },
    {
      category: "sports",
      question: "最常做的运动？",
      answers: ["篮球","跑步健身","羽毛球","游泳"],
    },
    {
      category: "technology",
      question: "科技在你生活中有多重要？",
      answers: ["没手机活不了","用但不依赖","想数字排毒","数码产品发烧友"],
    },
    {
      category: "technology",
      question: "苹果还是安卓？",
      answers: ["苹果——当然","安卓——自由度高","都行","经常换"],
    },
    {
      category: "fun",
      question: "一天超能力，你选什么？",
      answers: ["读心术","飞行","时间旅行","隐身"],
    },
    {
      category: "fun",
      question: "如果变成动物，你是？",
      answers: ["鹰——自由翱翔","猫——独立自在","海豚——活泼爱玩","熊猫——慵懒可爱"],
    },
  ],
  nl: [
    {
      category: "personality",
      question: "Wat zou je het meest imponeren op een eerste date?",
      answers: ["Een geheime cocktailbar","Een bezoek aan een boekwinkel","Film kijken op een dakterras","Een nachtelijke museumtour"],
    },
    {
      category: "personality",
      question: "Hoe laad jij je op na een drukke week?",
      answers: ["Netflix-marathon in m'n eentje","Uitgaan met vrienden","Een lange wandeling","Iets lekkers koken"],
    },
    {
      category: "lifestyle",
      question: "Stad of platteland?",
      answers: ["Stad — ik hou van de drukte","Platteland — rust en ruimte","Aan de rand van de stad","Maakt niet uit als ik gelukkig ben"],
    },
    {
      category: "lifestyle",
      question: "Hoe ziet jouw ideale weekend eruit?",
      answers: ["Uitgaan en feesten","Relaxen en series kijken","Outdoor avontuur","Quality time met familie"],
    },
    {
      category: "travel",
      question: "Strand of bergen?",
      answers: ["Strand — zon en zee","Bergen — natuur en avontuur","Stad — cultuur en eten","Een mix van alles"],
    },
    {
      category: "travel",
      question: "Hoe reis je het liefst?",
      answers: ["Vliegen — snel en ver","Trein — het landschap zien","Roadtrip — vrijheid","Backpacken — avontuurlijk"],
    },
    {
      category: "food",
      question: "Wat is jouw comfort food?",
      answers: ["Pizza","Pasta","Stamppot","Frietjes met mayo"],
    },
    {
      category: "food",
      question: "Koken of bestellen?",
      answers: ["Zelf koken, altijd","Bestellen is mijn specialiteit","Samen koken is het leukst","Hangt af van mijn energie"],
    },
    {
      category: "music",
      question: "Welk muziekgenre draai jij het meest?",
      answers: ["Pop","Hip-hop/R&B","Rock/Indie","Elektronisch"],
    },
    {
      category: "music",
      question: "Concert of festival?",
      answers: ["Intiem concert","Groot festival","Huiskamerconcert","Ik luister liever thuis"],
    },
    {
      category: "film",
      question: "Welk filmgenre past het best bij jou?",
      answers: ["Romantische komedie","Actie en avontuur","Thriller of horror","Documentaire"],
    },
    {
      category: "film",
      question: "Netflix and chill of bioscoop-date?",
      answers: ["Netflix op de bank","Bioscoop met popcorn","Openluchtbioscoop","Film maakt niet uit, het gezelschap wel"],
    },
    {
      category: "hobby",
      question: "Hoe breng je het liefst je vrije tijd door?",
      answers: ["Lezen","Gamen","Sporten","Creatief bezig zijn"],
    },
    {
      category: "hobby",
      question: "Welke hobby zou je willen oppakken?",
      answers: ["Surfen","Schilderen","Een instrument leren","Fotografie"],
    },
    {
      category: "humor",
      question: "Welk type humor heb jij?",
      answers: ["Droge humor","Slapstick","Sarcasme","Woordgrappen"],
    },
    {
      category: "humor",
      question: "Kun je tegen zelfspot?",
      answers: ["Ja, ik lach het hardst om mezelf","Soms, als het niet te ver gaat","Niet echt, ik ben gevoelig","Ik maak er een sport van"],
    },
    {
      category: "sports",
      question: "Welke sport kijk je het liefst?",
      answers: ["Voetbal","Formule 1","Tennis","Ik kijk geen sport"],
    },
    {
      category: "sports",
      question: "Gym, hardlopen of zwemmen?",
      answers: ["Gym — ijzer pompen","Hardlopen — buiten zijn","Zwemmen — rustig en effectief","Geen van deze"],
    },
    {
      category: "technology",
      question: "iPhone of Android?",
      answers: ["iPhone, altijd","Android, meer vrijheid","Maakt me niet uit","Ik wissel regelmatig"],
    },
    {
      category: "technology",
      question: "Hoe tech-savvy ben jij?",
      answers: ["Heel erg — ik hou van gadgets","Gemiddeld — ik kan me redden","Niet zo — ik vraag altijd hulp","Ik werk in tech"],
    },
    {
      category: "fun",
      question: "Als je één superkracht kon hebben, welke?",
      answers: ["Vliegen","Gedachten lezen","Tijdreizen","Onzichtbaarheid"],
    },
    {
      category: "fun",
      question: "Je wint de loterij. Wat doe je als eerste?",
      answers: ["Wereldreis boeken","Huis kopen","Alles investeren","Een feest geven voor iedereen"],
    },
  ],
  pl: [
    {
      category: "personality",
      question: "Co najbardziej zaimponowałoby Ci na pierwszej randce?",
      answers: ["Ukryty bar z koktajlami","Wizyta w księgarni","Kino na dachu","Nocna wycieczka po muzeum"],
    },
    {
      category: "personality",
      question: "Jak ładujesz baterie po ciężkim tygodniu?",
      answers: ["Maraton seriali w samotności","Wyjście ze znajomymi","Długi spacer","Gotowanie czegoś wyrafinowanego"],
    },
    {
      category: "lifestyle",
      question: "Miasto czy wieś?",
      answers: ["Miasto — kocham gwar","Wieś — cisza i przestrzeń","Przedmieścia","Nie ważne, byle być szczęśliwym"],
    },
    {
      category: "lifestyle",
      question: "Jak wygląda Twój idealny weekend?",
      answers: ["Imprezy i wyjścia","Relaks i seriale","Przygoda na świeżym powietrzu","Quality time z rodziną"],
    },
    {
      category: "travel",
      question: "Plaża czy góry?",
      answers: ["Plaża — słońce i morze","Góry — natura i przygoda","Miasto — kultura i jedzenie","Mix wszystkiego"],
    },
    {
      category: "travel",
      question: "Jak najchętniej podróżujesz?",
      answers: ["Samolotem — szybko i daleko","Pociągiem — widoki","Road trip — wolność","Backpacking — przygoda"],
    },
    {
      category: "food",
      question: "Jakie jest Twoje comfort food?",
      answers: ["Pizza","Pierogi","Schabowy z ziemniakami","Rosół babci"],
    },
    {
      category: "food",
      question: "Gotować czy zamawiać?",
      answers: ["Gotować, zawsze","Zamawianie to moja specjalność","Wspólne gotowanie jest najlepsze","Zależy od mojej energii"],
    },
    {
      category: "music",
      question: "Jaki gatunek muzyczny słuchasz najczęściej?",
      answers: ["Pop","Hip-hop/R&B","Rock/Indie","Elektroniczna"],
    },
    {
      category: "music",
      question: "Koncert czy festiwal?",
      answers: ["Kameralny koncert","Duży festiwal","Koncert domowy","Wolę słuchać w domu"],
    },
    {
      category: "film",
      question: "Jaki gatunek filmowy najbardziej do Ciebie pasuje?",
      answers: ["Komedia romantyczna","Akcja i przygoda","Thriller lub horror","Dokument"],
    },
    {
      category: "film",
      question: "Netflix i kanapa czy kino na randce?",
      answers: ["Netflix na kanapie","Kino z popcornem","Kino letnie na świeżym powietrzu","Film nie ważny, towarzystwo ważne"],
    },
    {
      category: "hobby",
      question: "Jak najchętniej spędzasz wolny czas?",
      answers: ["Czytanie","Granie","Sport","Kreatywne zajęcia"],
    },
    {
      category: "hobby",
      question: "Jakie hobby chciałbyś/chciałabyś rozpocząć?",
      answers: ["Surfing","Malowanie","Nauka gry na instrumencie","Fotografia"],
    },
    {
      category: "humor",
      question: "Jaki typ humoru masz?",
      answers: ["Suchy humor","Slapstick","Sarkazm","Gry słowne"],
    },
    {
      category: "humor",
      question: "Zniesiesz żarty z siebie?",
      answers: ["Tak, sam/a śmieję się z siebie najgłośniej","Czasem, jeśli nie za daleko","Nie bardzo, jestem wrażliwy/a","Robię z tego sport"],
    },
    {
      category: "sports",
      question: "Jaki sport najchętniej oglądasz?",
      answers: ["Piłka nożna","Formuła 1","Tenis","Nie oglądam sportu"],
    },
    {
      category: "sports",
      question: "Siłownia, bieganie czy pływanie?",
      answers: ["Siłownia — ciężary","Bieganie — na zewnątrz","Pływanie — spokojnie i efektywnie","Żadne z tych"],
    },
    {
      category: "technology",
      question: "iPhone czy Android?",
      answers: ["iPhone, zawsze","Android, więcej wolności","Nie ma znaczenia","Zmieniam regularnie"],
    },
    {
      category: "technology",
      question: "Jak bardzo jesteś tech-savvy?",
      answers: ["Bardzo — kocham gadżety","Średnio — daję sobie radę","Nie bardzo — proszę o pomoc","Pracuję w tech"],
    },
    {
      category: "fun",
      question: "Gdybyś mógł/mogła mieć jedną supermoc, jaką?",
      answers: ["Latanie","Czytanie myśli","Podróże w czasie","Niewidzialność"],
    },
    {
      category: "fun",
      question: "Wygrywasz na loterii. Co robisz najpierw?",
      answers: ["Rezerwuję podróż dookoła świata","Kupuję dom","Inwestuję wszystko","Organizuję imprezę dla wszystkich"],
    },
  ],
  sv: [
    {
      category: "personality",
      question: "Vad skulle imponera mest på dig på en första dejt?",
      answers: ["En hemlig cocktailbar","Ett besök i en bokhandel","Utomhusbio på ett tak","En nattlig museitur"],
    },
    {
      category: "personality",
      question: "Hur laddar du batterierna efter en tung vecka?",
      answers: ["Netflix-maraton ensam","Ut med vännerna","En lång promenad","Laga något gott"],
    },
    {
      category: "lifestyle",
      question: "Stad eller landsbygd?",
      answers: ["Stad — jag älskar pulsen","Landsbygd — lugn och ro","Förort","Spelar ingen roll bara jag är glad"],
    },
    {
      category: "lifestyle",
      question: "Hur ser din perfekta helg ut?",
      answers: ["Fest och uteliv","Slappa och kolla serier","Utomhusäventyr","Quality time med familjen"],
    },
    {
      category: "travel",
      question: "Strand eller berg?",
      answers: ["Strand — sol och hav","Berg — natur och äventyr","Stad — kultur och mat","En mix av allt"],
    },
    {
      category: "travel",
      question: "Hur reser du helst?",
      answers: ["Flyga — snabbt och långt","Tåg — se landskapet","Roadtrip — frihet","Backpacka — äventyr"],
    },
    {
      category: "food",
      question: "Vad är din comfort food?",
      answers: ["Pizza","Köttbullar med potatismos","Pasta","Pannkakor"],
    },
    {
      category: "food",
      question: "Laga mat eller beställa?",
      answers: ["Laga mat, alltid","Beställa är min specialitet","Laga mat ihop är bäst","Beror på min energi"],
    },
    {
      category: "music",
      question: "Vilken musikgenre lyssnar du mest på?",
      answers: ["Pop","Hip-hop/R&B","Rock/Indie","Elektronisk"],
    },
    {
      category: "music",
      question: "Konsert eller festival?",
      answers: ["Intim konsert","Stor festival","Husrumsscen","Lyssnar hellre hemma"],
    },
    {
      category: "film",
      question: "Vilken filmgenre passar dig bäst?",
      answers: ["Romantisk komedi","Action och äventyr","Thriller eller skräck","Dokumentär"],
    },
    {
      category: "film",
      question: "Netflix och myskvällar eller biodejt?",
      answers: ["Netflix i soffan","Bio med popcorn","Utomhusbio","Filmen spelar ingen roll, sällskapet gör det"],
    },
    {
      category: "hobby",
      question: "Hur spenderar du helst din fritid?",
      answers: ["Läsa","Spela","Sport","Kreativa saker"],
    },
    {
      category: "hobby",
      question: "Vilken hobby vill du börja med?",
      answers: ["Surfa","Måla","Lära sig ett instrument","Fotografi"],
    },
    {
      category: "humor",
      question: "Vilken typ av humor har du?",
      answers: ["Torr humor","Slapstick","Sarkasm","Ordvitsar"],
    },
    {
      category: "humor",
      question: "Tål du skämt om dig själv?",
      answers: ["Ja, jag skrattar hårdast åt mig själv","Ibland, om det inte går för långt","Inte riktigt, jag är känslig","Jag gör sport av det"],
    },
    {
      category: "sports",
      question: "Vilken sport tittar du helst på?",
      answers: ["Fotboll","Ishockey","Tennis","Jag tittar inte på sport"],
    },
    {
      category: "sports",
      question: "Gym, löpning eller simning?",
      answers: ["Gym — pumpa järn","Löpning — vara ute","Simning — lugnt och effektivt","Inget av dessa"],
    },
    {
      category: "technology",
      question: "iPhone eller Android?",
      answers: ["iPhone, alltid","Android, mer frihet","Spelar ingen roll","Jag byter regelbundet"],
    },
    {
      category: "technology",
      question: "Hur teknikintresserad är du?",
      answers: ["Väldigt — jag älskar prylar","Medel — jag klarar mig","Inte så — jag ber om hjälp","Jag jobbar inom tech"],
    },
    {
      category: "fun",
      question: "Om du kunde ha en superkraft, vilken?",
      answers: ["Flyga","Läsa tankar","Tidsresa","Osynlighet"],
    },
    {
      category: "fun",
      question: "Du vinner på lotto. Vad gör du först?",
      answers: ["Bokar en världsresa","Köper hus","Investerar allt","Bjuder alla på fest"],
    },
  ],
  hi: [
    {
      category: "personality",
      question: "पहली डेट पर सबसे ज़्यादा क्या इम्प्रेस करेगा?",
      answers: ["एक छुपी हुई रूफटॉप कैफे","किताबों की दुकान में घूमना","मरीन ड्राइव पर सैर","म्यूज़ियम की रात की सैर"],
    },
    {
      category: "personality",
      question: "थकान भरे हफ्ते के बाद कैसे रिचार्ज करते हो?",
      answers: ["Netflix मैराथन","दोस्तों के साथ बाहर","लंबी सैर या हाइकिंग","कुछ स्पेशल बनाना"],
    },
    {
      category: "lifestyle",
      question: "परफेक्ट संडे मॉर्निंग?",
      answers: ["गरमा गरम पराठे और चाय","दोपहर तक सोना","सुबह की दौड़","कैफे में ब्रेकफास्ट"],
    },
    {
      category: "lifestyle",
      question: "ऑफिस के बाद क्या करते हो?",
      answers: ["जिम जाता हूं","सोफे पर आराम","दोस्तों से मिलना","कुछ नया ट्राई करना"],
    },
    {
      category: "travel",
      question: "डेट के लिए भारत में कहां जाओगे?",
      answers: ["गोवा – बीच और सनसेट","जयपुर – महलों का शहर","मनाली – पहाड़ों में रोमांस","पॉन्डिचेरी – फ्रेंच विब"],
    },
    {
      category: "travel",
      question: "किसी खास के साथ ड्रीम वेकेशन?",
      answers: ["पेरिस – प्यार का शहर","मालदीव – ओवरवॉटर विला","स्विट्ज़रलैंड – बर्फीले पहाड़","बाली – ट्रॉपिकल पैराडाइज़"],
    },
    {
      category: "food",
      question: "सबसे पसंदीदा स्ट्रीट फूड?",
      answers: ["पानी पूरी/गोलगप्पे","वड़ा पाव","चाट","मोमोज़"],
    },
    {
      category: "food",
      question: "कम्फर्ट फूड क्या है?",
      answers: ["दाल चावल","मां के हाथ का खाना","बिरयानी","मैगी"],
    },
    {
      category: "music",
      question: "कौन सा म्यूज़िक फेस्टिवल जाना चाहोगे?",
      answers: ["NH7 Weekender","Sunburn","Magnetic Fields","Ziro Festival"],
    },
    {
      category: "music",
      question: "कौन सा गाना सुनकर तुरंत नाचने लगते हो?",
      answers: ["कोई बॉलीवुड हिट","पंजाबी बीट","EDM ड्रॉप","रीट्रो क्लासिक"],
    },
    {
      category: "film",
      question: "गिल्टी प्लेज़र बॉलीवुड फिल्म?",
      answers: ["DDLJ – हर बार","3 Idiots","Hera Pheri","Dil Chahta Hai"],
    },
    {
      category: "film",
      question: "कडल नाइट के लिए कौन सा जॉनर?",
      answers: ["रोमांटिक कॉमेडी","थ्रिलर","साइ-फाई","डॉक्यूमेंट्री"],
    },
    {
      category: "hobby",
      question: "डेट पर कौन सी हॉबी शेयर करोगे?",
      answers: ["साथ में कुकिंग","बोर्ड गेम नाइट","हाइकिंग","कॉन्सर्ट जाना"],
    },
    {
      category: "hobby",
      question: "करना चाहते हो पर हिम्मत नहीं?",
      answers: ["स्काईडाइविंग","स्टैंड-अप कॉमेडी ट्राई करना","कोई इंस्ट्रूमेंट सीखना","पेंटिंग"],
    },
    {
      category: "humor",
      question: "तुम्हारा ह्यूमर टाइप क्या है?",
      answers: ["ड्राई सरकैज़म","स्लैपस्टिक और मस्ती","पन और वर्डप्ले","डार्क ह्यूमर"],
    },
    {
      category: "humor",
      question: "तुम्हें हंसाने का गारंटीड तरीका?",
      answers: ["अचानक का जोक","सटीक टिप्पणी","फनी फेस","सेल्फ-डेप्रिकेटिंग ह्यूमर"],
    },
    {
      category: "sports",
      question: "डेट पर कौन सा स्पोर्ट करोगे?",
      answers: ["बोलिंग","बैडमिंटन","साइकलिंग","ट्रेकिंग"],
    },
    {
      category: "sports",
      question: "सबसे ज़्यादा कौन सा स्पोर्ट खेलते हो?",
      answers: ["क्रिकेट – क्लासिक","फुटबॉल","बैडमिंटन","रनिंग और जिम"],
    },
    {
      category: "technology",
      question: "टेक्नोलॉजी तुम्हारी ज़िंदगी में कितनी ज़रूरी है?",
      answers: ["फोन के बिना नहीं जी सकता","यूज़ करता हूं पर ज़्यादा नहीं","डिजिटल डीटॉक्स चाहिए","गैजेट्स का दीवाना"],
    },
    {
      category: "technology",
      question: "iPhone या Android?",
      answers: ["iPhone – बिल्कुल","Android – ज़्यादा फ्रीडम","कोई फर्क नहीं","बदलता रहता हूं"],
    },
    {
      category: "fun",
      question: "एक दिन के लिए कौन सी सुपरपावर चाहिए?",
      answers: ["दिमाग पढ़ना","उड़ना","टाइम ट्रैवल","इनविजिबल होना"],
    },
    {
      category: "fun",
      question: "अगर जानवर होते तो क्या?",
      answers: ["बाज – आज़ाद और ताकतवर","बिल्ली – आज़ाद","डॉल्फिन – खिलाड़ी","शेर – राजा"],
    },
  ],
};
