export interface HowToStep {
  nameKey: string;
  names: Record<string, string>;
  textKey: string;
  texts: Record<string, string>;
}

export interface HowToGuide {
  slug: string;
  emoji: string;
  publishedAt: string;
  titles: Record<string, string>;
  descriptions: Record<string, string>;
  keywords: string[];
  /** ISO 8601 duration string (e.g. "PT5M" for 5 minutes) */
  totalTime: string;
  steps: HowToStep[];
}

/**
 * How-to guides — all 16 site locales are filled in for every localized map
 * (titles, descriptions, step names, step texts). The detail page emits HowTo
 * JSON-LD with `inLanguage: locale`, so a missing locale would publish English
 * instructions labelled as another language. Never add a locale to
 * src/lib/i18n/config.ts without adding it here too.
 *
 * Claim rules applied here (see also the brand note in the blog content files):
 *  - Qulo is the only dating app named anywhere on this site.
 *  - No statistic without its source named in the same sentence — this file
 *    therefore carries no percentages at all.
 *  - Only mechanics the app actually has: each member writes 2-4 multiple-
 *    choice questions with four options (up to 10 on a paid plan) and marks the
 *    correct answer; the other person matches only by getting every question
 *    right; paid hints exist for
 *    solving. No verification, screening or "first/only" claim.
 */
export const HOW_TO_GUIDES: HowToGuide[] = [
  {
    slug: "create-first-qulo-profile",
    emoji: "👤",
    publishedAt: "2026-04-16",
    titles: {
      tr: "İlk Qulo Profilinizi Nasıl Oluşturursunuz: 5 Adımda Rehber",
      en: "How to Create Your First Qulo Profile: A 5-Step Guide",
      de: "So erstellen Sie Ihr erstes Qulo-Profil: 5-Schritt-Anleitung",
      fr: "Comment créer votre premier profil Qulo : guide en 5 étapes",
      es: "Cómo crear tu primer perfil de Qulo: guía de 5 pasos",
      ar: "كيف تنشئ ملفك الشخصي الأول على Qulo: دليل من 5 خطوات",
      ru: "Как создать первый профиль в Qulo: руководство из 5 шагов",
      pt: "Como criar seu primeiro perfil no Qulo: guia de 5 passos",
      it: "Come creare il tuo primo profilo Qulo: guida in 5 passi",
      ja: "Quloで最初のプロフィールをつくる方法：5ステップガイド",
      ko: "Qulo 첫 프로필 만드는 법: 5단계 가이드",
      zh: "如何创建你的第一个 Qulo 个人资料：5 步指南",
      nl: "Je eerste Qulo-profiel maken: gids in 5 stappen",
      pl: "Jak stworzyć pierwszy profil w Qulo: przewodnik w 5 krokach",
      sv: "Så skapar du din första Qulo-profil: guide i 5 steg",
      hi: "अपनी पहली Qulo प्रोफ़ाइल कैसे बनाएं: 5 चरणों की गाइड",
    },
    descriptions: {
      tr: "Qulo'da eksiksiz bir profil oluşturmanın 5 adımı. Fotoğraf seçiminden bio yazmaya ve ilk sorularınızı hazırlamaya kadar her şey.",
      en: "The 5 steps to a complete Qulo profile. Everything from choosing photos to writing your bio and preparing your first questions.",
      de: "Die 5 Schritte zu einem vollständigen Qulo-Profil. Von der Fotoauswahl über die Bio bis zu Ihren ersten Fragen.",
      fr: "Les 5 étapes d'un profil Qulo complet. Du choix des photos à la bio, jusqu'à la préparation de vos premières questions.",
      es: "Los 5 pasos para un perfil de Qulo completo. Desde la elección de fotos hasta la bio y tus primeras preguntas.",
      ar: "خمس خطوات لملف شخصي مكتمل على Qulo: من اختيار الصور إلى كتابة نبذتك وإعداد أسئلتك الأولى.",
      ru: "5 шагов к полному профилю в Qulo. От выбора фотографий до текста о себе и первых вопросов.",
      pt: "Os 5 passos para um perfil completo no Qulo. Da escolha das fotos à bio e às suas primeiras perguntas.",
      it: "I 5 passi per un profilo Qulo completo. Dalla scelta delle foto alla bio, fino alle tue prime domande.",
      ja: "Quloのプロフィールを完成させる5つのステップ。写真選びから自己紹介文、最初の質問づくりまで。",
      ko: "Qulo 프로필을 완성하는 5단계. 사진 고르기부터 소개글 작성, 첫 질문 만들기까지.",
      zh: "完成 Qulo 个人资料的 5 个步骤：从挑选照片、撰写简介，到创建你的第一批问题。",
      nl: "De 5 stappen naar een compleet Qulo-profiel. Van foto's kiezen tot je bio schrijven en je eerste vragen maken.",
      pl: "5 kroków do kompletnego profilu w Qulo. Od wyboru zdjęć po opis i pierwsze pytania.",
      sv: "De 5 stegen till en komplett Qulo-profil. Från att välja bilder till att skriva din bio och dina första frågor.",
      hi: "Qulo पर पूरी प्रोफ़ाइल बनाने के 5 चरण। फ़ोटो चुनने से लेकर बायो लिखने और अपने पहले सवाल बनाने तक।",
    },
    keywords: [
      "how to create qulo profile",
      "qulo profil oluşturma",
      "dating profile setup",
      "how to make dating profile",
    ],
    totalTime: "PT5M",
    steps: [
      {
        nameKey: "download",
        names: {
          tr: "Qulo'yu İndirin",
          en: "Download Qulo",
          de: "Qulo herunterladen",
          fr: "Téléchargez Qulo",
          es: "Descarga Qulo",
          ar: "حمّل Qulo",
          ru: "Скачайте Qulo",
          pt: "Baixe o Qulo",
          it: "Scarica Qulo",
          ja: "Quloをダウンロード",
          ko: "Qulo 다운로드",
          zh: "下载 Qulo",
          nl: "Download Qulo",
          pl: "Pobierz Qulo",
          sv: "Ladda ner Qulo",
          hi: "Qulo डाउनलोड करें",
        },
        textKey: "download_text",
        texts: {
          tr: "App Store veya Google Play'den Qulo uygulamasını ücretsiz indirin. iOS ve Android destekleniyor.",
          en: "Download Qulo free from the App Store or Google Play. Both iOS and Android are supported.",
          de: "Laden Sie Qulo kostenlos aus dem App Store oder von Google Play herunter. iOS und Android werden unterstützt.",
          fr: "Téléchargez Qulo gratuitement depuis l'App Store ou Google Play. iOS et Android sont pris en charge.",
          es: "Descarga Qulo gratis desde la App Store o Google Play. Es compatible con iOS y Android.",
          ar: "حمّل تطبيق Qulo مجانًا من App Store أو Google Play. التطبيق متاح على iOS وAndroid.",
          ru: "Скачайте Qulo бесплатно в App Store или Google Play. Поддерживаются iOS и Android.",
          pt: "Baixe o Qulo gratuitamente na App Store ou no Google Play. Funciona em iOS e Android.",
          it: "Scarica Qulo gratuitamente dall'App Store o da Google Play. È disponibile per iOS e Android.",
          ja: "App StoreまたはGoogle PlayからQuloを無料でダウンロードします。iOSとAndroidの両方に対応しています。",
          ko: "App Store 또는 Google Play에서 Qulo를 무료로 내려받으세요. iOS와 Android를 모두 지원합니다.",
          zh: "在 App Store 或 Google Play 免费下载 Qulo。iOS 和 Android 都支持。",
          nl: "Download Qulo gratis in de App Store of Google Play. Zowel iOS als Android worden ondersteund.",
          pl: "Pobierz Qulo za darmo z App Store lub Google Play. Aplikacja działa na iOS i Androidzie.",
          sv: "Ladda ner Qulo gratis från App Store eller Google Play. Både iOS och Android stöds.",
          hi: "App Store या Google Play से Qulo मुफ़्त डाउनलोड करें। यह iOS और Android दोनों पर उपलब्ध है।",
        },
      },
      {
        nameKey: "signup",
        names: {
          tr: "Hesap Oluşturun",
          en: "Sign Up",
          de: "Registrieren",
          fr: "Inscrivez-vous",
          es: "Regístrate",
          ar: "أنشئ حسابك",
          ru: "Создайте аккаунт",
          pt: "Crie sua conta",
          it: "Crea un account",
          ja: "アカウントを作成",
          ko: "계정 만들기",
          zh: "注册账号",
          nl: "Maak een account",
          pl: "Załóż konto",
          sv: "Skapa ett konto",
          hi: "अकाउंट बनाएं",
        },
        textKey: "signup_text",
        texts: {
          tr: "E-posta ya da Apple/Google ile hızlıca kaydolun. Ardından yaşınızı ve cinsiyetinizi girin.",
          en: "Sign up quickly with your email or with Apple/Google. Then enter your age and gender.",
          de: "Registrieren Sie sich schnell per E-Mail oder mit Apple/Google. Geben Sie anschließend Alter und Geschlecht an.",
          fr: "Inscrivez-vous rapidement par e-mail ou avec Apple/Google. Indiquez ensuite votre âge et votre genre.",
          es: "Regístrate rápidamente con tu correo o con Apple/Google. Después indica tu edad y tu género.",
          ar: "سجّل بسرعة بالبريد الإلكتروني أو عبر Apple/Google، ثم أدخل عمرك وجنسك.",
          ru: "Быстро зарегистрируйтесь по электронной почте или через Apple/Google. Затем укажите возраст и пол.",
          pt: "Cadastre-se rapidamente com e-mail ou com Apple/Google. Depois informe sua idade e seu gênero.",
          it: "Registrati rapidamente con l'e-mail oppure con Apple/Google. Poi indica la tua età e il tuo genere.",
          ja: "メールアドレス、またはApple/Googleアカウントですぐに登録できます。続けて年齢と性別を入力します。",
          ko: "이메일 또는 Apple/Google 계정으로 빠르게 가입하세요. 이어서 나이와 성별을 입력합니다.",
          zh: "用邮箱或 Apple/Google 账号快速注册，然后填写年龄和性别。",
          nl: "Meld je snel aan met je e-mailadres of met Apple/Google. Vul daarna je leeftijd en geslacht in.",
          pl: "Zarejestruj się szybko przez e-mail albo konto Apple/Google. Następnie podaj wiek i płeć.",
          sv: "Registrera dig snabbt med e-post eller med Apple/Google. Ange sedan ålder och kön.",
          hi: "ईमेल या Apple/Google से झटपट साइन अप करें। फिर अपनी उम्र और लिंग भरें।",
        },
      },
      {
        nameKey: "photos",
        names: {
          tr: "Fotoğraflarınızı Yükleyin",
          en: "Upload Your Photos",
          de: "Fotos hochladen",
          fr: "Téléchargez vos photos",
          es: "Sube tus fotos",
          ar: "ارفع صورك",
          ru: "Загрузите фотографии",
          pt: "Envie suas fotos",
          it: "Carica le tue foto",
          ja: "写真をアップロード",
          ko: "사진 올리기",
          zh: "上传照片",
          nl: "Upload je foto's",
          pl: "Dodaj zdjęcia",
          sv: "Ladda upp dina bilder",
          hi: "अपनी फ़ोटो अपलोड करें",
        },
        textKey: "photos_text",
        texts: {
          tr: "En az 3, en fazla 6 fotoğraf yükleyin. Bir tanesi net bir yüz fotoğrafı olsun, kalanlar gerçekten ne yaptığınızı göstersin.",
          en: "Upload between 3 and 6 photos — 6 is the maximum. Make one a clear face photo and let the rest show what you actually do.",
          de: "Laden Sie 3 bis 6 Fotos hoch, mehr als 6 sind nicht möglich. Eines sollte ein klares Gesichtsfoto sein, die übrigen zeigen Ihren Alltag.",
          fr: "Téléchargez de 3 à 6 photos, 6 au maximum. Que l'une soit un portrait net et que les autres montrent ce que vous faites vraiment.",
          es: "Sube entre 3 y 6 fotos, con 6 como máximo. Que una sea un retrato nítido y que el resto muestre lo que haces de verdad.",
          ar: "ارفع من 3 إلى 6 صور، و6 هو الحد الأقصى. اجعل إحداها صورة وجه واضحة، ودع البقية تُظهر ما تفعله فعلًا.",
          ru: "Загрузите от 3 до 6 фотографий — 6 это максимум. Пусть одна будет чётким портретом, а остальные показывают, чем вы занимаетесь.",
          pt: "Envie de 3 a 6 fotos, sendo 6 o máximo. Que uma seja um retrato nítido e que as outras mostrem o que você realmente faz.",
          it: "Carica da 3 a 6 foto, con 6 come massimo. Una sia un ritratto nitido, le altre mostrino quello che fai davvero.",
          ja: "写真は3〜6枚アップロードします（上限は6枚）。1枚は顔がはっきり写ったものにし、残りは普段していることが伝わる写真にしましょう。",
          ko: "사진은 3~6장 올리세요. 최대 6장까지 가능합니다. 한 장은 얼굴이 또렷한 사진으로 하고, 나머지는 평소 무엇을 하는지 보여 주세요.",
          zh: "上传 3 到 6 张照片，最多 6 张。其中一张要清晰露脸，其余展示你平时真正在做的事。",
          nl: "Upload 3 tot 6 foto's — 6 is het maximum. Maak er één een duidelijke gezichtsfoto en laat de rest zien wat je echt doet.",
          pl: "Dodaj od 3 do 6 zdjęć, przy czym 6 to maksimum. Jedno niech będzie wyraźnym zdjęciem twarzy, reszta niech pokazuje, czym się zajmujesz.",
          sv: "Ladda upp 3 till 6 bilder — 6 är max. Låt en vara ett tydligt ansiktsfoto och resten visa vad du faktiskt gör.",
          hi: "3 से 6 फ़ोटो अपलोड करें — ज़्यादा से ज़्यादा 6। एक में चेहरा साफ़ दिखे, बाक़ी में वह दिखे जो आप सचमुच करते हैं।",
        },
      },
      {
        nameKey: "bio",
        names: {
          tr: "Bio Yazın",
          en: "Write Your Bio",
          de: "Bio schreiben",
          fr: "Écrivez votre bio",
          es: "Escribe tu bio",
          ar: "اكتب نبذتك",
          ru: "Напишите о себе",
          pt: "Escreva sua bio",
          it: "Scrivi la tua bio",
          ja: "自己紹介を書く",
          ko: "소개글 쓰기",
          zh: "撰写个人简介",
          nl: "Schrijf je bio",
          pl: "Napisz opis",
          sv: "Skriv din bio",
          hi: "अपना बायो लिखें",
        },
        textKey: "bio_text",
        texts: {
          tr: "150-300 karakter arası samimi bir bio yazın. Genel sıfatlar yerine somut ilgi alanlarınızı ve haftanızın nasıl geçtiğini anlatın.",
          en: "Write a sincere bio of 150 to 300 characters. Name concrete interests and how you spend your week instead of generic adjectives.",
          de: "Schreiben Sie eine ehrliche Bio mit 150 bis 300 Zeichen. Nennen Sie konkrete Interessen und Ihren Alltag statt allgemeiner Adjektive.",
          fr: "Écrivez une bio sincère de 150 à 300 caractères. Citez des centres d'intérêt concrets et votre quotidien plutôt que des adjectifs passe-partout.",
          es: "Escribe una bio sincera de 150 a 300 caracteres. Menciona intereses concretos y cómo pasas la semana en lugar de adjetivos genéricos.",
          ar: "اكتب نبذة صادقة بين 150 و300 حرف. اذكر اهتمامات محدّدة وكيف تقضي أسبوعك بدل الصفات العامة.",
          ru: "Напишите искренний текст о себе на 150-300 знаков. Называйте конкретные интересы и то, как проходит ваша неделя, вместо общих прилагательных.",
          pt: "Escreva uma bio sincera de 150 a 300 caracteres. Cite interesses concretos e como é a sua semana, em vez de adjetivos genéricos.",
          it: "Scrivi una bio sincera di 150-300 caratteri. Indica interessi concreti e come passi la settimana, invece di aggettivi generici.",
          ja: "150〜300文字くらいの率直な自己紹介を書きます。ありきたりな形容詞ではなく、具体的な趣味や普段の過ごし方を書きましょう。",
          ko: "150~300자 정도의 솔직한 소개글을 쓰세요. 뻔한 형용사 대신 구체적인 관심사와 한 주를 보내는 방식을 적습니다.",
          zh: "写一段 150 到 300 字符的真诚简介。与其堆砌形容词，不如写清楚具体的兴趣和你一周的日常。",
          nl: "Schrijf een oprechte bio van 150 tot 300 tekens. Noem concrete interesses en hoe je week eruitziet in plaats van algemene bijvoeglijke naamwoorden.",
          pl: "Napisz szczery opis liczący 150-300 znaków. Zamiast ogólników wymień konkretne zainteresowania i to, jak wygląda twój tydzień.",
          sv: "Skriv en ärlig bio på 150-300 tecken. Nämn konkreta intressen och hur din vecka ser ut i stället för allmänna adjektiv.",
          hi: "150 से 300 अक्षरों का सच्चा बायो लिखें। घिसे-पिटे विशेषणों की जगह ठोस दिलचस्पियाँ और अपने हफ़्ते की दिनचर्या लिखें।",
        },
      },
      {
        nameKey: "questions",
        names: {
          tr: "İlk Sorularınızı Hazırlayın",
          en: "Create Your First Questions",
          de: "Erste Fragen erstellen",
          fr: "Créez vos premières questions",
          es: "Crea tus primeras preguntas",
          ar: "جهّز أسئلتك الأولى",
          ru: "Создайте первые вопросы",
          pt: "Crie suas primeiras perguntas",
          it: "Crea le tue prime domande",
          ja: "最初の質問をつくる",
          ko: "첫 질문 만들기",
          zh: "创建你的第一批问题",
          nl: "Maak je eerste vragen",
          pl: "Stwórz pierwsze pytania",
          sv: "Skapa dina första frågor",
          hi: "अपने पहले सवाल बनाएं",
        },
        textKey: "questions_text",
        texts: {
          tr: "2 ila 4 soru yazın — ücretli planda 10'a kadar. Her sorunun dört şıkkı vardır ve doğru cevabı siz işaretlersiniz; karşı taraf ancak hepsini doğru bilirse sizinle eşleşir.",
          en: "Write between 2 and 4 questions — up to 10 on a paid plan. Each one has four options and you mark the correct answer; the other person matches with you only by getting every question right.",
          de: "Schreiben Sie zwischen 2 und 4 Fragen — bis zu 10 im kostenpflichtigen Tarif. Jede hat vier Antwortmöglichkeiten, und Sie markieren die richtige. Ein Match entsteht nur, wenn die andere Person alle Fragen richtig beantwortet.",
          fr: "Rédigez de 2 à 4 questions — jusqu'à 10 avec un abonnement payant. Chacune a quatre options et c'est vous qui marquez la bonne réponse : l'autre personne ne fait un match qu'en répondant juste à toutes.",
          es: "Escribe entre 2 y 4 preguntas — hasta 10 con un plan de pago. Cada una tiene cuatro opciones y tú marcas la correcta; la otra persona solo hace match si las acierta todas.",
          ar: "اكتب بين سؤالين و4 أسئلة — حتى 10 أسئلة في الخطة المدفوعة. لكل سؤال أربعة خيارات وأنت من يحدّد الإجابة الصحيحة، ولا يحدث التطابق إلا إذا أجاب الطرف الآخر عنها جميعًا إجابة صحيحة.",
          ru: "Составьте от 2 до 4 вопросов — до 10 на платном тарифе. У каждого четыре варианта ответа, правильный отмечаете вы; совпадение происходит, только если другой человек ответит верно на все.",
          pt: "Escreva de 2 a 4 perguntas — até 10 num plano pago. Cada uma tem quatro opções e é você quem marca a correta; a outra pessoa só faz match se acertar todas.",
          it: "Scrivi da 2 a 4 domande — fino a 10 con un piano a pagamento. Ognuna ha quattro opzioni e sei tu a segnare quella giusta; il match avviene solo se l'altra persona le indovina tutte.",
          ja: "質問を2〜4問（有料プランなら最大10問）つくります。それぞれ選択肢は4つで、正解はあなたが設定します。相手は全問正解したときだけマッチできます。",
          ko: "질문을 2~4개 만드세요 — 유료 플랜에서는 최대 10개까지 가능합니다. 각 질문에는 선택지가 네 개 있고 정답은 당신이 지정합니다. 상대는 모든 질문을 맞혀야만 매칭됩니다.",
          zh: "写 2 到 4 道问题，付费方案最多 10 道。每题有四个选项，正确答案由你设定；对方只有全部答对才能与你配对。",
          nl: "Schrijf 2 tot 4 vragen — tot 10 met een betaald abonnement. Elke vraag heeft vier opties en jij markeert het juiste antwoord; de ander matcht alleen door ze allemaal goed te hebben.",
          pl: "Napisz od 2 do 4 pytań — do 10 w planie płatnym. Każde ma cztery opcje, a poprawną odpowiedź zaznaczasz ty; dopasowanie następuje tylko wtedy, gdy druga osoba odpowie dobrze na wszystkie.",
          sv: "Skriv 2 till 4 frågor — upp till 10 med ett betalt abonnemang. Varje fråga har fyra alternativ och du markerar det rätta; en matchning sker bara om den andra personen svarar rätt på alla.",
          hi: "2 से 4 सवाल लिखें — भुगतान वाली योजना में 10 तक। हर सवाल में चार विकल्प होते हैं और सही जवाब आप चुनते हैं; सामने वाला तभी मैच करता है जब वह हर सवाल सही करे।",
        },
      },
    ],
  },
  {
    slug: "write-great-questions",
    emoji: "❓",
    publishedAt: "2026-04-16",
    titles: {
      tr: "Harika Qulo Soruları Nasıl Yazılır: 5 Adım",
      en: "How to Write Great Qulo Questions: 5 Steps",
      de: "So schreiben Sie großartige Qulo-Fragen: 5 Schritte",
      fr: "Comment écrire de super questions Qulo : 5 étapes",
      es: "Cómo escribir excelentes preguntas en Qulo: 5 pasos",
      ar: "كيف تكتب أسئلة Qulo ممتازة: 5 خطوات",
      ru: "Как писать отличные вопросы в Qulo: 5 шагов",
      pt: "Como escrever ótimas perguntas no Qulo: 5 passos",
      it: "Come scrivere ottime domande su Qulo: 5 passi",
      ja: "Quloで良い質問を書く方法：5つのステップ",
      ko: "Qulo에서 좋은 질문 쓰는 법: 5단계",
      zh: "如何写出出色的 Qulo 问题：5 个步骤",
      nl: "Zo schrijf je goede Qulo-vragen: 5 stappen",
      pl: "Jak pisać świetne pytania w Qulo: 5 kroków",
      sv: "Så skriver du bra Qulo-frågor: 5 steg",
      hi: "Qulo पर बेहतरीन सवाल कैसे लिखें: 5 चरण",
    },
    descriptions: {
      tr: "Eşleşme kalitenizi artıracak soru yazma sanatı. Basit bir formül, örnekler ve kaçınmanız gereken yaygın hatalar.",
      en: "The art of writing questions that improve match quality. A simple formula, examples, and the common mistakes to avoid.",
      de: "Die Kunst, Fragen zu schreiben, die die Match-Qualität verbessern. Eine einfache Formel, Beispiele und häufige Fehler.",
      fr: "L'art d'écrire des questions qui améliorent la qualité des matchs. Une formule simple, des exemples et les erreurs courantes.",
      es: "El arte de escribir preguntas que mejoran la calidad de los matches. Una fórmula sencilla, ejemplos y los errores más comunes.",
      ar: "فنّ كتابة أسئلة ترفع جودة تطابقاتك: قاعدة بسيطة وأمثلة وأخطاء شائعة يجدر تفاديها.",
      ru: "Искусство писать вопросы, которые улучшают качество совпадений. Простая формула, примеры и типичные ошибки.",
      pt: "A arte de escrever perguntas que melhoram a qualidade dos matches. Uma fórmula simples, exemplos e os erros mais comuns.",
      it: "L'arte di scrivere domande che migliorano la qualità dei match. Una formula semplice, esempi e gli errori più comuni.",
      ja: "マッチの質を上げる質問の書き方。シンプルな型と具体例、そして避けたいよくある失敗。",
      ko: "매칭의 질을 높이는 질문 작성법. 간단한 공식과 예시, 그리고 흔한 실수까지.",
      zh: "写出提升配对质量的问题：一个简单公式、具体示例，以及要避开的常见错误。",
      nl: "De kunst van vragen die de kwaliteit van je matches verbeteren. Een simpele formule, voorbeelden en veelgemaakte fouten.",
      pl: "Sztuka pisania pytań, które poprawiają jakość dopasowań. Prosty schemat, przykłady i najczęstsze błędy.",
      sv: "Konsten att skriva frågor som höjer kvaliteten på dina matchningar. En enkel formel, exempel och vanliga misstag.",
      hi: "ऐसे सवाल लिखने की कला जो मैच की क्वालिटी बढ़ाएँ। एक आसान फ़ॉर्मूला, उदाहरण और आम ग़लतियाँ।",
    },
    keywords: [
      "how to write dating questions",
      "qulo soru yazma",
      "good dating questions",
      "quiz dating questions",
    ],
    totalTime: "PT10M",
    steps: [
      {
        nameKey: "choose_topic",
        names: {
          tr: "Konu Seçin",
          en: "Choose a Topic",
          de: "Thema wählen",
          fr: "Choisissez un sujet",
          es: "Elige un tema",
          ar: "اختر موضوعًا",
          ru: "Выберите тему",
          pt: "Escolha um tema",
          it: "Scegli un argomento",
          ja: "テーマを選ぶ",
          ko: "주제 고르기",
          zh: "选择主题",
          nl: "Kies een onderwerp",
          pl: "Wybierz temat",
          sv: "Välj ett ämne",
          hi: "विषय चुनें",
        },
        textKey: "choose_topic_text",
        texts: {
          tr: "Müzik, film, yaşam felsefesi, seyahat, mizah — ilginizi gerçekten çeken çeşitli konulardan başlayın.",
          en: "Music, movies, life philosophy, travel, humour — start with varied topics you are genuinely interested in.",
          de: "Musik, Filme, Lebensphilosophie, Reisen, Humor — beginnen Sie mit vielfältigen Themen, die Sie wirklich interessieren.",
          fr: "Musique, cinéma, philosophie de vie, voyages, humour — commencez par des sujets variés qui vous intéressent vraiment.",
          es: "Música, películas, filosofía de vida, viajes, humor — empieza con temas variados que de verdad te interesen.",
          ar: "الموسيقى، السينما، فلسفة الحياة، السفر، روح الدعابة — ابدأ من موضوعات متنوّعة تهمّك فعلًا.",
          ru: "Музыка, кино, жизненная философия, путешествия, юмор — начните с разных тем, которые вам действительно интересны.",
          pt: "Música, cinema, filosofia de vida, viagens, humor — comece por temas variados que realmente lhe interessam.",
          it: "Musica, cinema, filosofia di vita, viaggi, umorismo: parti da argomenti diversi che ti interessano davvero.",
          ja: "音楽、映画、生き方、旅、ユーモア。自分が本当に関心のある、幅の広いテーマから始めましょう。",
          ko: "음악, 영화, 삶의 태도, 여행, 유머 — 실제로 관심 있는 다양한 주제에서 시작하세요.",
          zh: "音乐、电影、生活态度、旅行、幽默——从你真正感兴趣的多样主题入手。",
          nl: "Muziek, film, levensfilosofie, reizen, humor — begin met uiteenlopende onderwerpen die je echt interesseren.",
          pl: "Muzyka, filmy, podejście do życia, podróże, poczucie humoru — zacznij od różnorodnych tematów, które naprawdę cię interesują.",
          sv: "Musik, film, livssyn, resor, humor — börja med varierade ämnen som du verkligen bryr dig om.",
          hi: "संगीत, फ़िल्में, ज़िंदगी का नज़रिया, सफ़र, मज़ाक — उन अलग-अलग विषयों से शुरू करें जिनमें आपकी सचमुच दिलचस्पी है।",
        },
      },
      {
        nameKey: "balance",
        names: {
          tr: "Zorluk Dengesi",
          en: "Balance Difficulty",
          de: "Schwierigkeit ausbalancieren",
          fr: "Équilibrez la difficulté",
          es: "Equilibra la dificultad",
          ar: "وازن الصعوبة",
          ru: "Сбалансируйте сложность",
          pt: "Equilibre a dificuldade",
          it: "Bilancia la difficoltà",
          ja: "難易度を調整する",
          ko: "난이도 맞추기",
          zh: "把握难度",
          nl: "Balanceer de moeilijkheid",
          pl: "Wyważ trudność",
          sv: "Balansera svårighetsgraden",
          hi: "मुश्किल का संतुलन रखें",
        },
        textKey: "balance_text",
        texts: {
          tr: "Ne çok kolay (herkes bilir) ne de çok zor (kimse bilemez) olsun. Orta zorluk en iyi sonucu verir.",
          en: "Not too easy (everyone knows it) and not too hard (no one can answer it). Medium difficulty works best.",
          de: "Weder zu einfach (jeder weiß es) noch zu schwer (niemand kann sie beantworten). Mittlere Schwierigkeit funktioniert am besten.",
          fr: "Ni trop facile (tout le monde devine) ni trop difficile (personne ne peut répondre). La difficulté moyenne fonctionne le mieux.",
          es: "Ni muy fácil (todo el mundo lo sabe) ni muy difícil (nadie puede acertar). La dificultad media funciona mejor.",
          ar: "لا سهلًا جدًا بحيث يعرفه الجميع، ولا صعبًا جدًا بحيث لا يجيب عنه أحد. الصعوبة المتوسطة هي الأفضل.",
          ru: "Не слишком просто (догадается каждый) и не слишком сложно (не ответит никто). Лучше всего работает средняя сложность.",
          pt: "Nem fácil demais (todo mundo sabe) nem difícil demais (ninguém acerta). A dificuldade média funciona melhor.",
          it: "Né troppo facile (lo sanno tutti) né troppo difficile (non risponde nessuno). La difficoltà media funziona meglio.",
          ja: "簡単すぎても（誰でも当たる）、難しすぎても（誰も答えられない）うまくいきません。中くらいの難易度がちょうどいいです。",
          ko: "너무 쉬워도(누구나 맞힘) 너무 어려워도(아무도 못 맞힘) 안 됩니다. 중간 난이도가 가장 좋습니다.",
          zh: "太简单（谁都答得出）和太难（没人答得对）都不行。中等难度最合适。",
          nl: "Niet te makkelijk (iedereen weet het) en niet te moeilijk (niemand kan hem beantwoorden). Gemiddelde moeilijkheid werkt het best.",
          pl: "Ani za łatwo (każdy zgadnie), ani za trudno (nikt nie odpowie). Najlepiej sprawdza się średni poziom.",
          sv: "Varken för lätt (alla vet) eller för svårt (ingen kan svara). Medelsvårt fungerar bäst.",
          hi: "न इतना आसान कि हर कोई बता दे, न इतना मुश्किल कि कोई जवाब ही न दे सके। मध्यम मुश्किल सबसे बेहतर काम करती है।",
        },
      },
      {
        nameKey: "be_specific",
        names: {
          tr: "Spesifik Olun",
          en: "Be Specific",
          de: "Seien Sie spezifisch",
          fr: "Soyez spécifique",
          es: "Sé específico",
          ar: "كن محدّدًا",
          ru: "Будьте конкретны",
          pt: "Seja específico",
          it: "Sii specifico",
          ja: "具体的に書く",
          ko: "구체적으로 쓰기",
          zh: "写得具体",
          nl: "Wees specifiek",
          pl: "Bądź konkretny",
          sv: "Var specifik",
          hi: "ठोस सवाल पूछें",
        },
        textKey: "be_specific_text",
        texts: {
          tr: "'En sevdiğim film nedir?' yerine '2020'den sonra çıkan filmlerden hangisini üç kez izledim?' gibi bir soru sorun.",
          en: "Instead of 'What is my favourite movie?' ask something like 'Which film released after 2020 have I watched three times?'",
          de: "Statt 'Was ist mein Lieblingsfilm?' fragen Sie lieber: 'Welchen Film nach 2020 habe ich dreimal gesehen?'",
          fr: "Au lieu de « Quel est mon film préféré ? », demandez plutôt : « Quel film sorti après 2020 ai-je vu trois fois ? »",
          es: "En lugar de '¿cuál es mi película favorita?', pregunta algo como '¿qué película posterior a 2020 he visto tres veces?'",
          ar: "بدل «ما فيلمي المفضّل؟» اسأل مثلًا: «أي فيلم صدر بعد 2020 شاهدته ثلاث مرات؟»",
          ru: "Вместо «Какой мой любимый фильм?» спросите: «Какой фильм, вышедший после 2020 года, я смотрел три раза?»",
          pt: "Em vez de 'qual é o meu filme favorito?', pergunte algo como 'que filme lançado depois de 2020 eu já assisti três vezes?'",
          it: "Invece di «qual è il mio film preferito?» chiedi «quale film uscito dopo il 2020 ho visto tre volte?»",
          ja: "「私の好きな映画は？」ではなく、「2020年以降の映画で、私が3回観たのはどれ？」のように尋ねましょう。",
          ko: "'내가 가장 좋아하는 영화는?' 대신 '2020년 이후 영화 중 내가 세 번 본 것은?'처럼 물어보세요.",
          zh: "与其问“我最喜欢的电影是什么？”，不如问“2020 年之后的电影里，我看过三遍的是哪一部？”",
          nl: "Vraag niet 'wat is mijn lievelingsfilm?' maar 'welke film van na 2020 heb ik drie keer gezien?'",
          pl: "Zamiast „jaki jest mój ulubiony film?” zapytaj „który film z okresu po 2020 roku obejrzałem trzy razy?”",
          sv: "Fråga inte ”vilken är min favoritfilm?” utan ”vilken film från efter 2020 har jag sett tre gånger?”",
          hi: "'मेरी पसंदीदा फ़िल्म कौन-सी है?' के बजाय पूछें: '2020 के बाद आई किस फ़िल्म को मैंने तीन बार देखा है?'",
        },
      },
      {
        nameKey: "avoid_taboo",
        names: {
          tr: "Tabulardan Kaçının",
          en: "Avoid Taboos",
          de: "Vermeiden Sie Tabus",
          fr: "Évitez les tabous",
          es: "Evita los tabús",
          ar: "تجنّب المواضيع الحسّاسة",
          ru: "Избегайте острых тем",
          pt: "Evite temas delicados",
          it: "Evita i tabù",
          ja: "デリケートな話題は避ける",
          ko: "민감한 주제는 피하기",
          zh: "避开敏感话题",
          nl: "Vermijd gevoelige onderwerpen",
          pl: "Unikaj drażliwych tematów",
          sv: "Undvik känsliga ämnen",
          hi: "संवेदनशील विषयों से बचें",
        },
        textKey: "avoid_taboo_text",
        texts: {
          tr: "Politika, din, maaş gibi tartışmalı konulardan başlangıçta kaçının. Sorularınızı pozitif ve eğlenceli tutun.",
          en: "Avoid controversial topics like politics, religion or salary at the start. Keep your questions positive and fun.",
          de: "Vermeiden Sie am Anfang umstrittene Themen wie Politik, Religion oder Gehalt. Halten Sie die Fragen positiv und unterhaltsam.",
          fr: "Évitez au début les sujets clivants comme la politique, la religion ou le salaire. Gardez des questions positives et légères.",
          es: "Evita al principio temas polémicos como política, religión o salario. Mantén las preguntas positivas y divertidas.",
          ar: "تجنّب في البداية المواضيع الخلافية كالسياسة والدين والراتب. اجعل أسئلتك إيجابية وممتعة.",
          ru: "Поначалу избегайте спорных тем — политики, религии, зарплаты. Держите вопросы позитивными и лёгкими.",
          pt: "Evite no início temas polêmicos como política, religião ou salário. Mantenha as perguntas positivas e divertidas.",
          it: "All'inizio evita temi controversi come politica, religione o stipendio. Mantieni le domande positive e leggere.",
          ja: "最初のうちは政治・宗教・収入といった対立しやすい話題は避けましょう。前向きで楽しい質問にしておくのが無難です。",
          ko: "처음에는 정치, 종교, 연봉처럼 논쟁이 되는 주제는 피하세요. 질문은 긍정적이고 가볍게 유지합니다.",
          zh: "一开始先避开政治、宗教、收入这类容易引发争论的话题。把问题保持得轻松而正面。",
          nl: "Vermijd in het begin controversiële onderwerpen als politiek, religie of salaris. Houd je vragen positief en luchtig.",
          pl: "Na początku unikaj tematów spornych: polityki, religii, zarobków. Trzymaj pytania w pozytywnym, lekkim tonie.",
          sv: "Undvik i början kontroversiella ämnen som politik, religion och lön. Håll frågorna positiva och lättsamma.",
          hi: "शुरुआत में राजनीति, धर्म और तनख़्वाह जैसे विवादित विषयों से बचें। सवालों को सकारात्मक और हल्का-फुल्का रखें।",
        },
      },
      {
        nameKey: "test_refine",
        names: {
          tr: "Test Edin ve Geliştirin",
          en: "Test and Refine",
          de: "Testen und verfeinern",
          fr: "Testez et affinez",
          es: "Prueba y refina",
          ar: "اختبر وحسّن",
          ru: "Проверяйте и дорабатывайте",
          pt: "Teste e refine",
          it: "Prova e affina",
          ja: "試して手直しする",
          ko: "시험하고 다듬기",
          zh: "测试并打磨",
          nl: "Test en verfijn",
          pl: "Testuj i poprawiaj",
          sv: "Testa och finjustera",
          hi: "आज़माएँ और सुधारें",
        },
        textKey: "test_refine_text",
        texts: {
          tr: "Hangi sorularınızın doğru bilindiğini takip edin. Kimsenin doğru cevaplayamadığı bir soruyu yeniden yazın ya da bir şıkkını değiştirin; sorularınızı istediğiniz zaman düzenleyebilirsiniz.",
          en: "Watch which of your questions people actually get right. If one is never answered correctly, rewrite it or change an option — you can edit your questions at any time.",
          de: "Beobachten Sie, welche Ihrer Fragen tatsächlich richtig beantwortet werden. Wird eine nie gelöst, formulieren Sie sie neu oder tauschen Sie eine Antwortmöglichkeit aus — Fragen lassen sich jederzeit bearbeiten.",
          fr: "Observez lesquelles de vos questions trouvent vraiment la bonne réponse. Si personne n'y répond juste, reformulez-la ou changez une option : vos questions restent modifiables à tout moment.",
          es: "Fíjate en cuáles de tus preguntas se aciertan de verdad. Si nadie responde bien a una, reescríbela o cambia una opción: puedes editar tus preguntas cuando quieras.",
          ar: "راقب أي أسئلتك تُحلّ فعلًا. وإن لم يجب أحد عن سؤال إجابة صحيحة، أعد صياغته أو غيّر أحد خياراته — يمكنك تعديل أسئلتك في أي وقت.",
          ru: "Следите, на какие ваши вопросы действительно отвечают верно. Если на какой-то никто не отвечает правильно, перепишите его или замените вариант — вопросы можно править в любой момент.",
          pt: "Acompanhe quais das suas perguntas as pessoas realmente acertam. Se ninguém acerta uma delas, reescreva-a ou troque uma opção: dá para editar suas perguntas quando quiser.",
          it: "Osserva quali tue domande vengono davvero indovinate. Se a una non risponde correttamente nessuno, riscrivila o cambia un'opzione: puoi modificare le domande quando vuoi.",
          ja: "どの質問が実際に正解されているかを見てみましょう。誰も正解できない質問は、書き直すか選択肢を差し替えます。質問はいつでも編集できます。",
          ko: "어떤 질문이 실제로 맞혀지는지 살펴보세요. 아무도 맞히지 못하는 질문은 다시 쓰거나 선택지를 바꾸면 됩니다. 질문은 언제든 수정할 수 있습니다.",
          zh: "留意哪些问题真的被答对了。如果某道题从来没人答对，就重写它或换掉一个选项——问题随时都可以修改。",
          nl: "Kijk welke van je vragen daadwerkelijk goed beantwoord worden. Wordt er één nooit goed beantwoord, herschrijf hem of vervang een optie — je vragen zijn altijd aan te passen.",
          pl: "Sprawdzaj, na które twoje pytania ludzie faktycznie odpowiadają poprawnie. Jeśli na któreś nikt nie trafia, przepisz je albo zmień jedną z opcji — pytania możesz edytować w każdej chwili.",
          sv: "Håll koll på vilka av dina frågor som faktiskt besvaras rätt. Om ingen klarar en fråga, skriv om den eller byt ut ett alternativ — du kan redigera dina frågor när som helst.",
          hi: "देखिए कि आपके कौन-से सवाल सचमुच सही हल हो रहे हैं। जिस सवाल का जवाब कोई सही नहीं दे पाता, उसे दोबारा लिखें या कोई विकल्प बदल दें — सवाल कभी भी संपादित किए जा सकते हैं।",
        },
      },
    ],
  },
  {
    slug: "get-more-matches",
    emoji: "💕",
    publishedAt: "2026-04-16",
    titles: {
      tr: "Qulo'da Daha Fazla Eşleşme Nasıl Alınır: 5 Strateji",
      en: "How to Get More Matches on Qulo: 5 Practical Strategies",
      de: "Wie Sie mehr Matches auf Qulo bekommen: 5 Strategien",
      fr: "Comment obtenir plus de matchs sur Qulo : 5 stratégies",
      es: "Cómo obtener más matches en Qulo: 5 estrategias",
      ar: "كيف تحصل على تطابقات أكثر على Qulo: 5 استراتيجيات",
      ru: "Как получать больше совпадений в Qulo: 5 стратегий",
      pt: "Como conseguir mais matches no Qulo: 5 estratégias",
      it: "Come ottenere più match su Qulo: 5 strategie",
      ja: "Quloでマッチを増やす方法：5つの戦略",
      ko: "Qulo에서 매칭을 늘리는 법: 5가지 전략",
      zh: "如何在 Qulo 上获得更多配对：5 个策略",
      nl: "Meer matches krijgen op Qulo: 5 strategieën",
      pl: "Jak zdobyć więcej dopasowań w Qulo: 5 strategii",
      sv: "Så får du fler matchningar på Qulo: 5 strategier",
      hi: "Qulo पर ज़्यादा मैच कैसे पाएँ: 5 रणनीतियाँ",
    },
    descriptions: {
      tr: "Eşleşme sayınızı artırmak için pratik stratejiler. Profil optimizasyonu, düzenli kullanım ve doğru soru seçimi.",
      en: "Practical strategies to increase your matches. Profile optimisation, regular use, and choosing the right questions.",
      de: "Praktische Strategien für mehr Matches. Profiloptimierung, regelmäßige Nutzung und die richtige Fragenauswahl.",
      fr: "Des stratégies concrètes pour plus de matchs. Optimisation du profil, usage régulier et choix des bonnes questions.",
      es: "Estrategias prácticas para conseguir más matches. Optimización del perfil, uso regular y elección de las preguntas correctas.",
      ar: "استراتيجيات عملية لزيادة تطابقاتك: تحسين الملف الشخصي، والاستخدام المنتظم، واختيار الأسئلة المناسبة.",
      ru: "Практические стратегии, чтобы получать больше совпадений: настройка профиля, регулярное использование и выбор правильных вопросов.",
      pt: "Estratégias práticas para aumentar seus matches. Otimização do perfil, uso regular e escolha das perguntas certas.",
      it: "Strategie pratiche per aumentare i tuoi match. Ottimizzazione del profilo, uso regolare e scelta delle domande giuste.",
      ja: "マッチを増やすための実践的な方法。プロフィールの見直し、こまめな利用、そして質問選びまで。",
      ko: "매칭을 늘리는 실전 전략. 프로필 다듬기, 꾸준한 사용, 그리고 질문 고르기.",
      zh: "增加配对的实用策略：优化个人资料、保持使用频率，以及挑对问题。",
      nl: "Praktische strategieën voor meer matches. Je profiel optimaliseren, regelmatig gebruik en de juiste vragen kiezen.",
      pl: "Praktyczne strategie na więcej dopasowań. Dopracowanie profilu, regularne korzystanie i dobór właściwych pytań.",
      sv: "Praktiska strategier för fler matchningar. Optimera profilen, använd appen regelbundet och välj rätt frågor.",
      hi: "ज़्यादा मैच पाने की व्यावहारिक रणनीतियाँ। प्रोफ़ाइल सुधारना, नियमित इस्तेमाल और सही सवाल चुनना।",
    },
    keywords: [
      "how to get matches dating app",
      "more matches qulo",
      "dating app tips",
      "qulo eşleşme artırma",
    ],
    totalTime: "PT15M",
    steps: [
      {
        nameKey: "optimize_profile",
        names: {
          tr: "Profilinizi Optimize Edin",
          en: "Optimise Your Profile",
          de: "Profil optimieren",
          fr: "Optimisez votre profil",
          es: "Optimiza tu perfil",
          ar: "حسّن ملفك الشخصي",
          ru: "Доработайте профиль",
          pt: "Otimize seu perfil",
          it: "Ottimizza il profilo",
          ja: "プロフィールを見直す",
          ko: "프로필 다듬기",
          zh: "优化个人资料",
          nl: "Optimaliseer je profiel",
          pl: "Dopracuj profil",
          sv: "Optimera din profil",
          hi: "प्रोफ़ाइल बेहतर करें",
        },
        textKey: "optimize_profile_text",
        texts: {
          tr: "Ana fotoğrafınız net olsun. Bio bölümünüzde genel ifadeler yerine spesifik ilgi alanları bulunsun.",
          en: "Make sure your main photo is clear. Put specific interests in your bio instead of generic phrases.",
          de: "Achten Sie darauf, dass Ihr Hauptfoto scharf ist. Nennen Sie in der Bio konkrete Interessen statt allgemeiner Floskeln.",
          fr: "Assurez-vous que votre photo principale est nette. Mettez des centres d'intérêt précis dans votre bio, pas des formules toutes faites.",
          es: "Comprueba que tu foto principal sea nítida. Pon intereses concretos en la bio en lugar de frases genéricas.",
          ar: "احرص أن تكون صورتك الرئيسية واضحة، وضع في نبذتك اهتمامات محدّدة بدل العبارات العامة.",
          ru: "Пусть главное фото будет чётким. В тексте о себе называйте конкретные интересы вместо общих фраз.",
          pt: "Garanta que sua foto principal esteja nítida. Coloque interesses específicos na bio em vez de frases genéricas.",
          it: "Assicurati che la foto principale sia nitida. Nella bio metti interessi specifici invece di frasi generiche.",
          ja: "メイン写真は鮮明なものにしましょう。自己紹介には決まり文句ではなく、具体的な関心を書きます。",
          ko: "대표 사진은 선명한 것으로 두세요. 소개글에는 뻔한 문구 대신 구체적인 관심사를 적습니다.",
          zh: "确保主照片清晰。简介里写具体的兴趣，而不是套话。",
          nl: "Zorg dat je hoofdfoto scherp is. Zet specifieke interesses in je bio in plaats van standaardzinnen.",
          pl: "Zadbaj, by główne zdjęcie było wyraźne. W opisie wpisz konkretne zainteresowania zamiast ogólników.",
          sv: "Se till att huvudbilden är skarp. Skriv specifika intressen i din bio i stället för allmänna fraser.",
          hi: "मुख्य फ़ोटो साफ़ रखें। बायो में घिसे-पिटे वाक्यों की जगह ठोस दिलचस्पियाँ लिखें।",
        },
      },
      {
        nameKey: "be_active",
        names: {
          tr: "Aktif Kalın",
          en: "Stay Active",
          de: "Aktiv bleiben",
          fr: "Restez actif",
          es: "Mantente activo",
          ar: "ابقَ نشطًا",
          ru: "Будьте активны",
          pt: "Seja ativo",
          it: "Resta attivo",
          ja: "こまめに開く",
          ko: "꾸준히 접속하기",
          zh: "保持活跃",
          nl: "Blijf actief",
          pl: "Bądź aktywny",
          sv: "Var aktiv",
          hi: "सक्रिय रहें",
        },
        textKey: "be_active_text",
        texts: {
          tr: "Haftada birkaç gün uygulamayı açın. Keşfet sıralamasında yakın zamanda aktif olan profillere ağırlık verilir, uzun süre girilmeyen profil daha az görünür.",
          en: "Open the app a few days a week. Discover gives weight to recently active profiles, so a dormant one is shown less often.",
          de: "Öffnen Sie die App an mehreren Tagen pro Woche. In der Entdecken-Ansicht zählen kürzlich aktive Profile mehr, ein ruhendes Profil wird seltener gezeigt.",
          fr: "Ouvrez l'application quelques jours par semaine. La section Découvrir accorde du poids aux profils récemment actifs ; un profil en sommeil apparaît moins.",
          es: "Abre la app varios días a la semana. Descubrir da peso a los perfiles activos recientemente, así que un perfil dormido se muestra menos.",
          ar: "افتح التطبيق بضعة أيام في الأسبوع. تمنح صفحة الاكتشاف وزنًا أكبر للملفات النشطة حديثًا، فالملف الخامل يظهر أقل.",
          ru: "Заходите в приложение несколько дней в неделю. В разделе «Обнаружение» недавно активные профили получают больший вес, а спящие показываются реже.",
          pt: "Abra o app alguns dias por semana. O Descobrir dá peso a perfis ativos recentemente, então um perfil parado aparece menos.",
          it: "Apri l'app qualche giorno alla settimana. La sezione Scopri dà più peso ai profili attivi di recente, quindi un profilo fermo compare meno.",
          ja: "週に数日はアプリを開きましょう。ディスカバーでは最近活動したプロフィールが重視されるため、放置したプロフィールは表示されにくくなります。",
          ko: "일주일에 며칠은 앱을 열어 보세요. 디스커버는 최근에 활동한 프로필에 가중치를 두기 때문에, 오래 방치된 프로필은 덜 노출됩니다.",
          zh: "每周打开应用几次。发现页会更看重近期活跃的资料，长期不上线的资料出现得更少。",
          nl: "Open de app een paar dagen per week. Ontdekken geeft gewicht aan recent actieve profielen, dus een slapend profiel wordt minder getoond.",
          pl: "Otwieraj aplikację kilka dni w tygodniu. Odkrywanie premiuje profile aktywne ostatnio, więc uśpiony profil pokazuje się rzadziej.",
          sv: "Öppna appen några dagar i veckan. Utforska väger in profiler som varit aktiva nyligen, så en vilande profil visas mer sällan.",
          hi: "हफ़्ते में कुछ दिन ऐप ज़रूर खोलें। डिस्कवर हाल ही में सक्रिय प्रोफ़ाइलों को ज़्यादा तवज्जो देता है, इसलिए ठंडी पड़ी प्रोफ़ाइल कम दिखती है।",
        },
      },
      {
        nameKey: "solve_questions",
        names: {
          tr: "Soruları Çözün",
          en: "Solve Questions",
          de: "Fragen lösen",
          fr: "Résolvez les questions",
          es: "Resuelve preguntas",
          ar: "حلّ أسئلة الآخرين",
          ru: "Решайте вопросы",
          pt: "Resolva perguntas",
          it: "Risolvi le domande",
          ja: "相手の質問を解く",
          ko: "질문 풀기",
          zh: "去解答问题",
          nl: "Los vragen op",
          pl: "Rozwiązuj pytania",
          sv: "Lös frågor",
          hi: "सवाल हल करें",
        },
        textKey: "solve_questions_text",
        texts: {
          tr: "Sadece profilinizin bulunmasını beklemeyin; Keşfet'e girip başkalarının sorularını çözerek eşleşmeyi kendiniz başlatın.",
          en: "Don't just wait to be found — go into Discover and solve other people's questions to start matches yourself.",
          de: "Warten Sie nicht nur darauf, gefunden zu werden — lösen Sie in der Entdecken-Ansicht die Fragen anderer und stoßen Sie Matches selbst an.",
          fr: "N'attendez pas seulement qu'on vous trouve : dans Découvrir, résolvez les questions des autres pour déclencher vous-même des matchs.",
          es: "No esperes solo a que te encuentren: entra en Descubrir y resuelve las preguntas de otras personas para iniciar matches tú mismo.",
          ar: "لا تنتظر أن يعثر عليك أحد فقط؛ ادخل إلى الاكتشاف وحُلّ أسئلة الآخرين لتبدأ التطابق بنفسك.",
          ru: "Не ждите только, что найдут вас: заходите в «Обнаружение» и решайте вопросы других, чтобы создавать совпадения самостоятельно.",
          pt: "Não espere só ser encontrado: entre no Descobrir e resolva as perguntas dos outros para criar matches você mesmo.",
          it: "Non aspettare solo di essere trovato: entra in Scopri e risolvi le domande degli altri per far partire tu i match.",
          ja: "見つけてもらうのを待つだけにせず、ディスカバーで相手の質問を解いて自分からマッチを起こしましょう。",
          ko: "누군가 찾아오기만 기다리지 말고, 디스커버에서 다른 사람의 질문을 풀어 직접 매칭을 만들어 보세요.",
          zh: "别只等着被发现——去发现页解答别人的问题，主动促成配对。",
          nl: "Wacht niet alleen tot je gevonden wordt: ga naar Ontdekken en los vragen van anderen op om zelf matches te starten.",
          pl: "Nie czekaj tylko, aż ktoś cię znajdzie — wejdź w Odkrywanie i rozwiązuj pytania innych, żeby samemu tworzyć dopasowania.",
          sv: "Vänta inte bara på att bli hittad — gå in i Utforska och lös andras frågor för att själv skapa matchningar.",
          hi: "सिर्फ़ इंतज़ार मत कीजिए कि कोई आपको ढूँढे — डिस्कवर में जाकर दूसरों के सवाल हल करें और ख़ुद मैच बनाएँ।",
        },
      },
      {
        nameKey: "right_questions",
        names: {
          tr: "Doğru Soruları Seçin",
          en: "Choose the Right Questions",
          de: "Die richtigen Fragen wählen",
          fr: "Choisissez les bonnes questions",
          es: "Elige las preguntas correctas",
          ar: "اختر الأسئلة المناسبة",
          ru: "Выбирайте правильные вопросы",
          pt: "Escolha as perguntas certas",
          it: "Scegli le domande giuste",
          ja: "適切な質問を選ぶ",
          ko: "알맞은 질문 고르기",
          zh: "挑对问题",
          nl: "Kies de juiste vragen",
          pl: "Dobierz właściwe pytania",
          sv: "Välj rätt frågor",
          hi: "सही सवाल चुनें",
        },
        textKey: "right_questions_text",
        texts: {
          tr: "Eşleşme için soruların hepsinin doğru bilinmesi gerekir; kimsenin cevaplayamadığı tek bir soru kapıyı tamamen kapatır. Dört şıktan en az biri, profilinizi okuyan birinin makul şekilde tahmin edebileceği bir seçenek olsun.",
          en: "Matching requires every question to be right, so one impossible question closes the door completely. Keep at least one of the four options a fair guess for someone who has read your profile.",
          de: "Für ein Match müssen alle Fragen richtig sein — eine einzige unlösbare Frage schließt die Tür vollständig. Sorgen Sie dafür, dass mindestens eine der vier Antwortmöglichkeiten für jemanden, der Ihr Profil gelesen hat, plausibel ist.",
          fr: "Un match exige que toutes les questions soient justes : une seule question impossible ferme complètement la porte. Faites en sorte qu'au moins une des quatre options soit devinable par quelqu'un qui a lu votre profil.",
          es: "Para hacer match hay que acertar todas las preguntas, así que una sola pregunta imposible cierra la puerta del todo. Deja que al menos una de las cuatro opciones sea deducible para quien haya leído tu perfil.",
          ar: "يتطلّب التطابق الإجابة الصحيحة عن كل الأسئلة، فسؤال واحد مستحيل يغلق الباب تمامًا. اجعل واحدًا على الأقل من الخيارات الأربعة قابلًا للتخمين لمن قرأ ملفك الشخصي.",
          ru: "Для совпадения нужно ответить верно на все вопросы, поэтому один невозможный вопрос закрывает дверь полностью. Пусть хотя бы один из четырёх вариантов будет разумной догадкой для того, кто прочитал ваш профиль.",
          pt: "O match exige acertar todas as perguntas, então uma única pergunta impossível fecha a porta por completo. Deixe pelo menos uma das quatro opções ao alcance de quem leu o seu perfil.",
          it: "Il match richiede di indovinare tutte le domande, quindi una sola domanda impossibile chiude la porta del tutto. Fai in modo che almeno una delle quattro opzioni sia intuibile per chi ha letto il tuo profilo.",
          ja: "マッチには全問正解が必要なので、答えようのない質問が1つあるだけで道が閉ざされます。4つの選択肢のうち少なくとも1つは、プロフィールを読んだ人なら見当がつくものにしておきましょう。",
          ko: "매칭은 모든 질문을 맞혀야 성립하므로, 답이 불가능한 질문 하나가 문을 완전히 닫아 버립니다. 네 개의 선택지 중 최소 하나는 프로필을 읽은 사람이 짐작할 수 있게 두세요.",
          zh: "配对要求每道题都答对，所以一道无解的问题就会彻底堵死机会。四个选项里至少留一个，让读过你资料的人能合理猜到。",
          nl: "Voor een match moeten álle vragen goed zijn, dus één onmogelijke vraag sluit de deur volledig. Houd minstens één van de vier opties raadbaar voor wie je profiel heeft gelezen.",
          pl: "Do dopasowania trzeba odpowiedzieć dobrze na wszystkie pytania, więc jedno niemożliwe pytanie zamyka drzwi całkowicie. Niech przynajmniej jedna z czterech opcji będzie do odgadnięcia dla kogoś, kto przeczytał twój profil.",
          sv: "En matchning kräver att alla frågor blir rätt, så en enda omöjlig fråga stänger dörren helt. Låt minst ett av de fyra alternativen vara gissningsbart för någon som läst din profil.",
          hi: "मैच के लिए हर सवाल सही होना ज़रूरी है, इसलिए एक भी नामुमकिन सवाल रास्ता पूरी तरह बंद कर देता है। चार विकल्पों में से कम से कम एक ऐसा रखें जिसे आपकी प्रोफ़ाइल पढ़ने वाला अंदाज़ा लगा सके।",
        },
      },
      {
        nameKey: "location_times",
        names: {
          tr: "Konum ve Zamanlama",
          en: "Location and Timing",
          de: "Standort und Zeitpunkt",
          fr: "Localisation et moment",
          es: "Ubicación y momento",
          ar: "الموقع والتوقيت",
          ru: "Местоположение и время",
          pt: "Localização e horário",
          it: "Posizione e tempistica",
          ja: "位置情報とタイミング",
          ko: "위치와 타이밍",
          zh: "位置与时机",
          nl: "Locatie en timing",
          pl: "Lokalizacja i pora",
          sv: "Plats och tidpunkt",
          hi: "लोकेशन और समय",
        },
        textKey: "location_times_text",
        texts: {
          tr: "Konum iznini açık tutun; Keşfet yakınınızdaki kişileri gösterir ve izin olmadan çalışmaz. Konum yalnızca uygulama açıkken okunur, bu yüzden gerçekten cevap verebileceğiniz saatlerde girin.",
          en: "Keep location permission on — Discover shows people near you and won't work without it. Location is only read while the app is open, so use it at hours when you can actually reply.",
          de: "Lassen Sie die Standortberechtigung aktiv — Entdecken zeigt Menschen in Ihrer Nähe und funktioniert ohne sie nicht. Der Standort wird nur bei geöffneter App gelesen, nutzen Sie sie also zu Zeiten, in denen Sie auch antworten können.",
          fr: "Gardez l'autorisation de localisation active : Découvrir montre les personnes proches et ne fonctionne pas sans elle. La position n'est lue que lorsque l'application est ouverte, alors utilisez-la aux heures où vous pouvez vraiment répondre.",
          es: "Mantén activado el permiso de ubicación: Descubrir muestra a personas cercanas y no funciona sin él. La ubicación solo se lee con la app abierta, así que úsala a horas en las que puedas responder.",
          ar: "أبقِ إذن الموقع مفعّلًا؛ فالاكتشاف يعرض من هم قريبون منك ولا يعمل بدونه. لا يُقرأ الموقع إلا والتطبيق مفتوح، لذا استخدمه في أوقات تستطيع فيها الردّ فعلًا.",
          ru: "Держите разрешение на геолокацию включённым: «Обнаружение» показывает людей рядом и без него не работает. Местоположение считывается только при открытом приложении, поэтому заходите в часы, когда действительно можете ответить.",
          pt: "Mantenha a permissão de localização ligada: o Descobrir mostra pessoas perto de você e não funciona sem ela. A localização só é lida com o app aberto, então use em horários em que você consiga responder.",
          it: "Tieni attivo il permesso di posizione: Scopri mostra le persone vicine e senza di esso non funziona. La posizione viene letta solo ad app aperta, quindi usala negli orari in cui puoi davvero rispondere.",
          ja: "位置情報の許可はオンのままにしておきましょう。ディスカバーは近くの人を表示する機能なので、許可がないと動きません。位置はアプリを開いている間だけ読み取られるため、返信できる時間帯に開くのがおすすめです。",
          ko: "위치 권한은 켜 두세요. 디스커버는 근처 사람을 보여 주는 기능이라 권한 없이는 작동하지 않습니다. 위치는 앱이 열려 있을 때만 읽으므로, 실제로 답할 수 있는 시간대에 접속하세요.",
          zh: "保持位置权限开启——发现页展示的是你附近的人，没有权限就无法使用。位置只在应用打开时读取，所以尽量在你能及时回复的时段使用。",
          nl: "Laat de locatietoestemming aan staan: Ontdekken toont mensen bij jou in de buurt en werkt er niet zonder. Je locatie wordt alleen gelezen als de app openstaat, dus gebruik hem op momenten dat je echt kunt reageren.",
          pl: "Zostaw włączone uprawnienie lokalizacji — Odkrywanie pokazuje osoby w pobliżu i bez niego nie zadziała. Lokalizacja odczytywana jest tylko przy otwartej aplikacji, więc korzystaj z niej wtedy, gdy naprawdę możesz odpisać.",
          sv: "Låt platsbehörigheten vara på — Utforska visar personer nära dig och fungerar inte utan den. Platsen läses bara när appen är öppen, så använd den när du faktiskt kan svara.",
          hi: "लोकेशन की अनुमति चालू रखें — डिस्कवर आपके आसपास के लोग दिखाता है और बिना अनुमति के काम नहीं करता। लोकेशन सिर्फ़ ऐप खुली होने पर पढ़ी जाती है, इसलिए उन घंटों में इस्तेमाल करें जब आप वाकई जवाब दे सकें।",
        },
      },
    ],
  },
  {
    slug: "first-chat-tips",
    emoji: "💬",
    publishedAt: "2026-04-16",
    titles: {
      tr: "Eşleştikten Sonra İlk Sohbet Nasıl Başlar: 5 Altın Kural",
      en: "How to Start a Great First Chat After Matching: 5 Golden Rules",
      de: "Nach dem Match gut ins Gespräch kommen: 5 goldene Regeln",
      fr: "Bien démarrer la conversation après un match : 5 règles d'or",
      es: "Cómo iniciar bien el primer chat tras un match: 5 reglas de oro",
      ar: "كيف تبدأ محادثة أولى جيدة بعد التطابق: 5 قواعد ذهبية",
      ru: "Как начать первый разговор после совпадения: 5 золотых правил",
      pt: "Como começar bem a primeira conversa após o match: 5 regras de ouro",
      it: "Come iniziare bene la prima chat dopo un match: 5 regole d'oro",
      ja: "マッチ後の最初の会話を始める方法：5つの黄金律",
      ko: "매칭 후 첫 대화를 잘 시작하는 법: 5가지 황금률",
      zh: "配对之后如何开启第一次对话：5 条黄金法则",
      nl: "Zo begin je na een match een goed eerste gesprek: 5 gouden regels",
      pl: "Jak dobrze zacząć pierwszą rozmowę po dopasowaniu: 5 złotych zasad",
      sv: "Så inleder du det första samtalet efter en match: 5 gyllene regler",
      hi: "मैच के बाद पहली बातचीत कैसे शुरू करें: 5 सुनहरे नियम",
    },
    descriptions: {
      tr: "Eşleştikten sonraki ilk mesaj sohbetin yönünü belirler. Karşı tarafın cevaplamak isteyeceği bir başlangıç nasıl yazılır?",
      en: "The first message after a match sets the tone. How to open a conversation that the other person actually wants to answer.",
      de: "Die erste Nachricht nach dem Match bestimmt den Ton. So schreiben Sie einen Einstieg, auf den die andere Person antworten möchte.",
      fr: "Le premier message après un match donne le ton. Comment écrire une ouverture à laquelle l'autre a envie de répondre.",
      es: "El primer mensaje tras un match marca el tono. Cómo escribir una apertura a la que la otra persona quiera responder.",
      ar: "الرسالة الأولى بعد التطابق تحدّد نبرة الحديث. كيف تكتب بداية يرغب الطرف الآخر في الردّ عليها؟",
      ru: "Первое сообщение после совпадения задаёт тон. Как написать начало, на которое собеседнику захочется ответить.",
      pt: "A primeira mensagem depois do match define o tom. Como escrever uma abertura que a outra pessoa queira responder.",
      it: "Il primo messaggio dopo un match dà il tono. Come scrivere un'apertura a cui l'altra persona voglia rispondere.",
      ja: "マッチ後の最初のメッセージが会話の空気を決めます。相手が返したくなる書き出しのつくり方。",
      ko: "매칭 후 첫 메시지가 대화의 분위기를 정합니다. 상대가 답하고 싶어지는 첫 문장 쓰는 법.",
      zh: "配对后的第一条消息决定了整段对话的调子。如何写出对方愿意回复的开场。",
      nl: "Het eerste bericht na een match bepaalt de toon. Zo schrijf je een opening waar de ander op wil reageren.",
      pl: "Pierwsza wiadomość po dopasowaniu nadaje ton. Jak napisać otwarcie, na które druga osoba zechce odpowiedzieć.",
      sv: "Det första meddelandet efter en match sätter tonen. Så skriver du en inledning som den andra vill svara på.",
      hi: "मैच के बाद का पहला मैसेज पूरी बातचीत का रुख़ तय करता है। ऐसी शुरुआत कैसे लिखें जिसका जवाब देने का मन करे।",
    },
    keywords: [
      "first message dating app",
      "how to start chat dating",
      "ilk mesaj dating",
      "opening line dating",
    ],
    totalTime: "PT5M",
    steps: [
      {
        nameKey: "reference_questions",
        names: {
          tr: "Sorulara Değinin",
          en: "Reference the Questions",
          de: "Auf die Fragen verweisen",
          fr: "Référencez les questions",
          es: "Menciona las preguntas",
          ar: "استند إلى الأسئلة",
          ru: "Опирайтесь на вопросы",
          pt: "Use as perguntas",
          it: "Parti dalle domande",
          ja: "質問を話の糸口にする",
          ko: "질문에서 시작하기",
          zh: "从问题聊起",
          nl: "Verwijs naar de vragen",
          pl: "Nawiąż do pytań",
          sv: "Utgå från frågorna",
          hi: "सवालों का ज़िक्र करें",
        },
        textKey: "reference_questions_text",
        texts: {
          tr: "Eşleştiğiniz anda biriniz diğerinin sorularını çoktan cevaplamış olur. Boş bir selamlama yerine o cevaplardan yola çıkarak yazın.",
          en: "By the time you match, one of you has already answered the other's questions. Start from those answers instead of a blank greeting.",
          de: "Wenn Sie matchen, hat eine Seite die Fragen der anderen bereits beantwortet. Steigen Sie über diese Antworten ein statt mit einer leeren Begrüßung.",
          fr: "Au moment du match, l'un de vous a déjà répondu aux questions de l'autre. Partez de ces réponses plutôt que d'un simple bonjour.",
          es: "Cuando hay match, una de las dos personas ya ha respondido a las preguntas de la otra. Arranca desde esas respuestas en lugar de un saludo vacío.",
          ar: "عند حدوث التطابق يكون أحدكما قد أجاب بالفعل عن أسئلة الآخر. انطلق من تلك الإجابات بدل تحية فارغة.",
          ru: "К моменту совпадения кто-то из вас уже ответил на вопросы другого. Начинайте с этих ответов, а не с пустого приветствия.",
          pt: "Quando o match acontece, uma das pessoas já respondeu às perguntas da outra. Comece por essas respostas em vez de um cumprimento vazio.",
          it: "Quando scatta il match, uno dei due ha già risposto alle domande dell'altro. Parti da quelle risposte invece che da un saluto vuoto.",
          ja: "マッチが成立した時点で、どちらかがもう相手の質問に答えています。空っぽの挨拶ではなく、その回答から書き出しましょう。",
          ko: "매칭이 된 시점에 이미 한쪽은 상대의 질문에 답한 상태입니다. 빈 인사말 대신 그 답에서 이야기를 시작하세요.",
          zh: "配对成功时，你们中已经有一方答过对方的问题。别用空洞的问候开场，就从那些答案说起。",
          nl: "Op het moment van de match heeft een van jullie de vragen van de ander al beantwoord. Begin bij die antwoorden in plaats van bij een leeg 'hoi'.",
          pl: "W chwili dopasowania jedno z was już odpowiedziało na pytania drugiego. Zacznij od tych odpowiedzi, a nie od pustego powitania.",
          sv: "När matchningen sker har en av er redan svarat på den andras frågor. Utgå från de svaren i stället för en tom hälsning.",
          hi: "मैच होने तक आप दोनों में से एक सामने वाले के सवालों का जवाब दे चुका होता है। ख़ाली अभिवादन के बजाय उन्हीं जवाबों से बात शुरू करें।",
        },
      },
      {
        nameKey: "avoid_generic",
        names: {
          tr: "Genel Mesajlardan Kaçının",
          en: "Avoid Generic Messages",
          de: "Vermeiden Sie Generisches",
          fr: "Évitez le générique",
          es: "Evita lo genérico",
          ar: "تجنّب الرسائل العامة",
          ru: "Избегайте шаблонов",
          pt: "Evite mensagens genéricas",
          it: "Evita i messaggi generici",
          ja: "ありきたりな挨拶を避ける",
          ko: "뻔한 메시지 피하기",
          zh: "别发套话",
          nl: "Vermijd standaardberichten",
          pl: "Unikaj ogólników",
          sv: "Undvik standardmeddelanden",
          hi: "घिसे-पिटे मैसेज से बचें",
        },
        textKey: "avoid_generic_text",
        texts: {
          tr: "'Merhaba', 'Nasılsın?' gibi genel mesajlar dikkat çekmez. Bunun yerine profildeki spesifik bir detay hakkında yorum yapın.",
          en: "Generic messages like 'Hi' or 'How are you?' don't get anyone's attention. Comment on a specific detail from the profile instead.",
          de: "Generische Nachrichten wie 'Hi' oder 'Wie geht's?' fallen niemandem auf. Kommentieren Sie stattdessen ein konkretes Detail aus dem Profil.",
          fr: "Des messages passe-partout comme « salut » ou « ça va ? » ne retiennent l'attention de personne. Commentez plutôt un détail précis du profil.",
          es: "Mensajes genéricos como 'hola' o '¿qué tal?' no llaman la atención de nadie. Comenta mejor un detalle concreto del perfil.",
          ar: "رسائل مثل «مرحبًا» أو «كيف حالك؟» لا تلفت انتباه أحد. علّق بدلًا منها على تفصيل محدّد في الملف الشخصي.",
          ru: "Сообщения вроде «привет» или «как дела?» никого не цепляют. Прокомментируйте вместо этого конкретную деталь профиля.",
          pt: "Mensagens genéricas como 'oi' ou 'tudo bem?' não chamam a atenção de ninguém. Comente antes um detalhe concreto do perfil.",
          it: "Messaggi come «ciao» o «come va?» non attirano l'attenzione di nessuno. Commenta piuttosto un dettaglio preciso del profilo.",
          ja: "「こんにちは」「元気ですか？」といった定型文は誰の目にも留まりません。プロフィールの具体的な一点について触れましょう。",
          ko: "'안녕하세요', '잘 지내세요?' 같은 뻔한 인사는 눈에 띄지 않습니다. 대신 프로필의 구체적인 한 가지에 대해 말해 보세요.",
          zh: "“你好”“最近怎么样”这类套话谁都不会留意。不如就资料里的某个具体细节说两句。",
          nl: "Standaardberichten als 'hoi' of 'hoe gaat het?' vallen bij niemand op. Reageer liever op een concreet detail uit het profiel.",
          pl: "Wiadomości w stylu „cześć” czy „co słychać?” nikogo nie zatrzymują. Skomentuj zamiast tego konkretny szczegół z profilu.",
          sv: "Standardmeddelanden som ”hej” eller ”hur mår du?” fastnar inte hos någon. Kommentera hellre en konkret detalj i profilen.",
          hi: "'हाय' या 'कैसे हो?' जैसे घिसे-पिटे मैसेज किसी का ध्यान नहीं खींचते। इसके बजाय प्रोफ़ाइल की किसी ठोस बात पर बात कीजिए।",
        },
      },
      {
        nameKey: "ask_open_ended",
        names: {
          tr: "Açık Uçlu Sorular Sorun",
          en: "Ask Open-Ended Questions",
          de: "Offene Fragen stellen",
          fr: "Posez des questions ouvertes",
          es: "Haz preguntas abiertas",
          ar: "اطرح أسئلة مفتوحة",
          ru: "Задавайте открытые вопросы",
          pt: "Faça perguntas abertas",
          it: "Fai domande aperte",
          ja: "開かれた質問をする",
          ko: "열린 질문 하기",
          zh: "问开放式问题",
          nl: "Stel open vragen",
          pl: "Zadawaj otwarte pytania",
          sv: "Ställ öppna frågor",
          hi: "खुले सवाल पूछें",
        },
        textKey: "ask_open_ended_text",
        texts: {
          tr: "'Evet/hayır' soruları sohbeti öldürür. Bunun yerine '...hakkında ne düşünüyorsun?' gibi açık uçlu sorular sorun.",
          en: "'Yes/no' questions kill the conversation. Ask open-ended questions instead, like 'What do you actually think about…?'",
          de: "Ja/Nein-Fragen töten das Gespräch. Fragen Sie stattdessen offen, etwa 'Was hältst du eigentlich von …?'",
          fr: "Les questions fermées tuent la conversation. Posez plutôt des questions ouvertes du type « qu'est-ce que tu penses de… ? »",
          es: "Las preguntas de sí o no matan la conversación. Haz preguntas abiertas del tipo '¿qué opinas de…?'",
          ar: "أسئلة «نعم/لا» تقتل الحديث. اطرح بدلًا منها أسئلة مفتوحة مثل: «ما رأيك في…؟»",
          ru: "Вопросы с ответом «да/нет» убивают разговор. Спрашивайте открыто: «А что ты думаешь о…?»",
          pt: "Perguntas de sim ou não matam a conversa. Prefira perguntas abertas do tipo 'o que você acha de…?'",
          it: "Le domande da sì o no uccidono la conversazione. Meglio domande aperte come «tu che ne pensi di…?»",
          ja: "「はい/いいえ」で終わる質問は会話を止めます。「〜についてどう思う？」のように開かれた聞き方をしましょう。",
          ko: "'예/아니오'로 끝나는 질문은 대화를 끊습니다. '…에 대해 어떻게 생각해요?'처럼 열린 질문을 던지세요.",
          zh: "只能回答“是”或“不是”的问题会让对话卡住。改问“你怎么看……？”这样的开放式问题。",
          nl: "Ja-neevragen doden het gesprek. Stel liever open vragen als 'wat vind jij eigenlijk van…?'",
          pl: "Pytania na tak/nie zabijają rozmowę. Pytaj otwarcie, na przykład „a co ty sądzisz o…?”",
          sv: "Ja/nej-frågor dödar samtalet. Ställ hellre öppna frågor som ”vad tycker du egentligen om …?”",
          hi: "'हाँ/ना' वाले सवाल बातचीत ख़त्म कर देते हैं। इसके बजाय पूछिए, '…के बारे में आपका क्या ख़याल है?'",
        },
      },
      {
        nameKey: "be_authentic",
        names: {
          tr: "Kendiniz Olun",
          en: "Be Authentic",
          de: "Seien Sie authentisch",
          fr: "Soyez authentique",
          es: "Sé auténtico",
          ar: "كن على طبيعتك",
          ru: "Будьте собой",
          pt: "Seja você mesmo",
          it: "Sii te stesso",
          ja: "自分のままでいる",
          ko: "있는 그대로 하기",
          zh: "做你自己",
          nl: "Wees jezelf",
          pl: "Bądź sobą",
          sv: "Var dig själv",
          hi: "ख़ुद बने रहें",
        },
        textKey: "be_authentic_text",
        texts: {
          tr: "Rol yapmayın. Doğal, samimi ve özgün olun; karşı tarafın sizi gerçekten tanımasına izin verin.",
          en: "Don't play a part. Be natural, sincere and genuine, and let the other person get to know the real you.",
          de: "Spielen Sie keine Rolle. Bleiben Sie natürlich, aufrichtig und echt, und lassen Sie die andere Person Sie wirklich kennenlernen.",
          fr: "Ne jouez pas un rôle. Restez naturel, sincère et authentique, et laissez l'autre vous connaître pour de vrai.",
          es: "No interpretes un papel. Sé natural, sincero y auténtico, y deja que la otra persona te conozca de verdad.",
          ar: "لا تؤدِّ دورًا. كن طبيعيًا وصادقًا وحقيقيًا، ودع الطرف الآخر يتعرّف إليك فعلًا.",
          ru: "Не играйте роль. Будьте естественны, искренни и настоящи — и позвольте человеку узнать вас по-настоящему.",
          pt: "Não faça personagem. Seja natural, sincero e autêntico, e deixe a outra pessoa conhecer você de verdade.",
          it: "Non recitare una parte. Sii naturale, sincero e autentico, e lascia che l'altra persona ti conosca davvero.",
          ja: "役を演じないこと。自然に、正直に、自分のままで。相手に本当のあなたを知ってもらいましょう。",
          ko: "역할을 연기하지 마세요. 자연스럽고 솔직하게, 있는 그대로 대하면서 상대가 진짜 당신을 알게 하세요.",
          zh: "别演角色。保持自然、坦诚、真实，让对方认识真正的你。",
          nl: "Speel geen rol. Blijf natuurlijk, oprecht en echt, en laat de ander je werkelijk leren kennen.",
          pl: "Nie odgrywaj roli. Bądź naturalny, szczery i prawdziwy — pozwól drugiej osobie poznać cię naprawdę.",
          sv: "Spela ingen roll. Var naturlig, uppriktig och äkta, och låt den andra lära känna dig på riktigt.",
          hi: "कोई किरदार मत निभाइए। सहज, सच्चे और असली रहिए, और सामने वाले को अपना असली रूप जानने दीजिए।",
        },
      },
      {
        nameKey: "suggest_meeting",
        names: {
          tr: "Tanışma Önerin",
          en: "Suggest Meeting",
          de: "Treffen vorschlagen",
          fr: "Suggérez une rencontre",
          es: "Sugiere un encuentro",
          ar: "اقترح اللقاء",
          ru: "Предложите встретиться",
          pt: "Sugira um encontro",
          it: "Proponi di vedervi",
          ja: "会う提案をする",
          ko: "만남 제안하기",
          zh: "提出见面",
          nl: "Stel een afspraak voor",
          pl: "Zaproponuj spotkanie",
          sv: "Föreslå att ni ses",
          hi: "मिलने का सुझाव दें",
        },
        textKey: "suggest_meeting_text",
        texts: {
          tr: "Birkaç günlük sohbetten sonra buluşma önerin. Mesajlaşma uzadıkça buluşma ihtimali azalır.",
          en: "Suggest meeting after a few days of chatting. The longer it stays in text, the less likely the meeting becomes.",
          de: "Schlagen Sie nach ein paar Tagen Chat ein Treffen vor. Je länger Sie nur schreiben, desto unwahrscheinlicher wird die Begegnung.",
          fr: "Proposez de vous voir après quelques jours d'échanges. Plus la conversation s'étire par écrit, moins la rencontre a de chances d'arriver.",
          es: "Propón un encuentro después de unos días de conversación. Cuanto más se alarga el chat, menos probable es que ese encuentro llegue a pasar.",
          ar: "اقترح اللقاء بعد بضعة أيام من المحادثة. فكلما طالت الرسائل قلّت فرصة أن يحدث اللقاء.",
          ru: "Предложите встретиться после нескольких дней переписки. Чем дольше вы только пишете, тем меньше шансов, что встреча состоится.",
          pt: "Sugira um encontro depois de alguns dias de conversa. Quanto mais a troca de mensagens se estende, menor a chance de o encontro acontecer.",
          it: "Proponi di vedervi dopo qualche giorno di chat. Più le chiacchiere si allungano, meno è probabile che l'incontro avvenga.",
          ja: "数日やり取りしたら、会う提案をしてみましょう。メッセージだけの期間が長引くほど、実際に会う可能性は下がります。",
          ko: "며칠 대화를 나눴다면 만남을 제안해 보세요. 메시지만 오래 주고받을수록 실제로 만날 가능성은 줄어듭니다.",
          zh: "聊上几天后就提议见一面。只停留在文字上的时间越长，真正见面的可能性越小。",
          nl: "Stel na een paar dagen chatten voor om af te spreken. Hoe langer het bij berichten blijft, hoe kleiner de kans dat je elkaar echt ziet.",
          pl: "Po kilku dniach rozmowy zaproponuj spotkanie. Im dłużej zostajecie przy pisaniu, tym mniejsza szansa, że do spotkania dojdzie.",
          sv: "Föreslå att ni ses efter några dagars chattande. Ju längre det stannar vid meddelanden, desto mindre sannolikt blir mötet.",
          hi: "कुछ दिन बातचीत के बाद मिलने का सुझाव दीजिए। जितनी देर बात सिर्फ़ मैसेज तक सिमटी रहेगी, असल में मिलने की संभावना उतनी घटती जाएगी।",
        },
      },
    ],
  },
];
