export const SITE_URL = "https://quloapp.com";
export const SITE_NAME = "Qulo";

export const SEO: Record<string, { title: string; description: string }> = {
  tr: {
    title: "Qulo — Sorularla Tanış | AI Dating Uygulaması",
    description:
      "Soru hazırla, paylaş, doğru cevaplayan kişiyle eşleş. AI destekli yeni nesil tanışma uygulaması.",
  },
  en: {
    title: "Qulo — Meet Through Questions | AI Dating App",
    description:
      "Create questions, share them, match with the person who answers correctly. AI-powered next-gen dating app.",
  },
  de: {
    title: "Qulo — Kennenlernen durch Fragen | AI Dating App",
    description:
      "Erstelle Fragen, teile sie und matche mit der Person, die richtig antwortet. KI-gestützte Dating-App der nächsten Generation.",
  },
  fr: {
    title: "Qulo — Rencontrez par les Questions | App de Dating IA",
    description:
      "Créez des questions, partagez-les, matchez avec la personne qui répond correctement. App de rencontre nouvelle génération propulsée par l'IA.",
  },
  es: {
    title: "Qulo — Conoce a Través de Preguntas | App de Citas con IA",
    description:
      "Crea preguntas, compártelas, haz match con quien responda correctamente. App de citas de nueva generación con IA.",
  },
  ar: {
    title: "Qulo — تعارف من خلال الأسئلة | تطبيق مواعدة بالذكاء الاصطناعي",
    description:
      "أنشئ أسئلة، شاركها، وتطابق مع من يجيب بشكل صحيح. تطبيق مواعدة من الجيل الجديد مدعوم بالذكاء الاصطناعي.",
  },
  ja: {
    title: "Qulo — 質問で出会う | AI マッチングアプリ",
    description:
      "質問を作成し、共有し、正しく答えた人とマッチ。AI搭載の次世代マッチングアプリ。",
  },
  ko: {
    title: "Qulo — 질문으로 만남 | AI 데이팅 앱",
    description:
      "질문을 만들고, 공유하고, 정답을 맞힌 사람과 매칭하세요. AI 기반 차세대 데이팅 앱.",
  },
  zh: {
    title: "Qulo — 通过问题认识 | AI 约会应用",
    description:
      "创建问题、分享问题、与答对的人匹配。AI驱动的新一代约会应用。",
  },
  ru: {
    title: "Qulo — Знакомства через вопросы | AI приложение для знакомств",
    description:
      "Создавайте вопросы, делитесь ими и находите пару с тем, кто ответит правильно. Приложение для знакомств нового поколения на базе ИИ.",
  },
  pt: {
    title: "Qulo — Conheça Através de Perguntas | App de Namoro com IA",
    description:
      "Crie perguntas, compartilhe e combine com quem responder corretamente. App de namoro de nova geração com IA.",
  },
  it: {
    title: "Qulo — Incontra Attraverso le Domande | App di Incontri con IA",
    description:
      "Crea domande, condividile e fai match con chi risponde correttamente. App di incontri di nuova generazione con IA.",
  },
  nl: {
    title: "Qulo — Ontmoet Via Vragen | AI Dating App",
    description:
      "Maak vragen, deel ze en match met degene die correct antwoordt. AI-gestuurde dating-app van de nieuwe generatie.",
  },
  pl: {
    title: "Qulo — Poznawaj Przez Pytania | Aplikacja Randkowa z AI",
    description:
      "Twórz pytania, udostępniaj je i dopasowuj się z osobą, która odpowie poprawnie. Aplikacja randkowa nowej generacji z AI.",
  },
  sv: {
    title: "Qulo — Träffas Genom Frågor | AI Dejtingapp",
    description:
      "Skapa frågor, dela dem och matcha med den som svarar rätt. AI-driven dejtingapp av nästa generation.",
  },
  hi: {
    title: "Qulo — सवालों से मिलें | AI डेटिंग ऐप",
    description:
      "सवाल बनाएं, शेयर करें, सही जवाब देने वाले से मैच करें। AI-संचालित अगली पीढ़ी का डेटिंग ऐप।",
  },
};

/** FAQ data for FAQPage structured data — Google rich snippets */
export const FAQ_DATA: Record<string, { q: string; a: string }[]> = {
  tr: [
    { q: "Qulo nasıl çalışır?", a: "Sorular hazırlarsın, diğer kullanıcılar bu soruları çözer. Tüm sorularını doğru cevaplayan kişiyle eşleşirsin. Swipe yok, quiz var!" },
    { q: "Qulo ücretsiz mi?", a: "Evet, Qulo ücretsiz olarak kullanılabilir. Ek özellikler için Plus ve Premium abonelik seçenekleri de mevcuttur." },
    { q: "Qulo diğer dating uygulamalarından ne farkı var?", a: "Qulo swipe tabanlı değil, soru-cevap tabanlı bir eşleşme sistemi kullanır. Bu sayede yüzeysel değil, derinlikli eşleşmeler oluşur." },
    { q: "Qulo güvenli mi?", a: "Evet. Verileriniz şifrelenerek korunur, profil doğrulama sistemi mevcuttur ve istenmeyen kullanıcıları engelleme özelliği vardır." },
    { q: "Hangi ülkelerde kullanılabilir?", a: "Qulo dünya genelinde kullanılabilir. 16 farklı dilde destek sunuyoruz." },
  ],
  en: [
    { q: "How does Qulo work?", a: "You create questions, other users solve them. You match with the person who answers all your questions correctly. No swiping, just quizzing!" },
    { q: "Is Qulo free?", a: "Yes, Qulo is free to use. Plus and Premium subscription options are available for additional features." },
    { q: "How is Qulo different from other dating apps?", a: "Qulo uses a question-and-answer matching system instead of swiping. This creates deeper, more meaningful matches." },
    { q: "Is Qulo safe?", a: "Yes. Your data is encrypted, profile verification is available, and you can block unwanted users." },
    { q: "Which countries is Qulo available in?", a: "Qulo is available worldwide. We support 16 different languages." },
  ],
  de: [
    { q: "Wie funktioniert Qulo?", a: "Du erstellst Fragen, andere Nutzer lösen sie. Du matchst mit der Person, die alle deine Fragen richtig beantwortet. Kein Swipen, nur Quizzen!" },
    { q: "Ist Qulo kostenlos?", a: "Ja, Qulo ist kostenlos nutzbar. Für zusätzliche Funktionen gibt es Plus- und Premium-Abonnements." },
    { q: "Was unterscheidet Qulo von anderen Dating-Apps?", a: "Qulo nutzt ein Frage-Antwort-System statt Swipen. So entstehen tiefere, bedeutungsvollere Matches." },
    { q: "Ist Qulo sicher?", a: "Ja. Deine Daten werden verschlüsselt, Profilverifizierung ist verfügbar und du kannst unerwünschte Nutzer blockieren." },
    { q: "In welchen Ländern ist Qulo verfügbar?", a: "Qulo ist weltweit verfügbar. Wir unterstützen 16 verschiedene Sprachen." },
  ],
  fr: [
    { q: "Comment fonctionne Qulo ?", a: "Vous créez des questions, d'autres utilisateurs les résolvent. Vous matchez avec la personne qui répond correctement à toutes vos questions. Pas de swipe, juste du quiz !" },
    { q: "Qulo est-il gratuit ?", a: "Oui, Qulo est gratuit. Des abonnements Plus et Premium sont disponibles pour des fonctionnalités supplémentaires." },
    { q: "En quoi Qulo est-il différent des autres applications de rencontre ?", a: "Qulo utilise un système de matching basé sur les questions-réponses plutôt que sur le swipe. Cela crée des matchs plus profonds et plus authentiques." },
    { q: "Qulo est-il sûr ?", a: "Oui. Vos données sont chiffrées, la vérification de profil est disponible et vous pouvez bloquer les utilisateurs indésirables." },
    { q: "Dans quels pays Qulo est-il disponible ?", a: "Qulo est disponible dans le monde entier. Nous prenons en charge 16 langues différentes." },
  ],
  es: [
    { q: "¿Cómo funciona Qulo?", a: "Creas preguntas, otros usuarios las resuelven. Haces match con quien responda correctamente a todas tus preguntas. ¡Sin deslizar, solo cuestionarios!" },
    { q: "¿Es Qulo gratis?", a: "Sí, Qulo es gratuito. Hay suscripciones Plus y Premium para funciones adicionales." },
    { q: "¿En qué se diferencia Qulo de otras apps de citas?", a: "Qulo utiliza un sistema de emparejamiento basado en preguntas y respuestas en lugar del deslizamiento. Así surgen matches más profundos y significativos." },
    { q: "¿Es Qulo seguro?", a: "Sí. Tus datos están encriptados, la verificación de perfil está disponible y puedes bloquear usuarios no deseados." },
    { q: "¿En qué países está disponible Qulo?", a: "Qulo está disponible en todo el mundo. Damos soporte a 16 idiomas diferentes." },
  ],
  ar: [
    { q: "كيف يعمل Qulo؟", a: "تنشئ أسئلة، ويحلها المستخدمون الآخرون. تتطابق مع الشخص الذي يجيب على جميع أسئلتك بشكل صحيح. لا تمرير، فقط اختبارات!" },
    { q: "هل Qulo مجاني؟", a: "نعم، Qulo مجاني. تتوفر اشتراكات Plus وPremium لميزات إضافية." },
    { q: "ما الذي يميز Qulo عن تطبيقات المواعدة الأخرى؟", a: "يستخدم Qulo نظام مطابقة قائمًا على الأسئلة والأجوبة بدلًا من التمرير. وهكذا تنشأ تطابقات أعمق وأكثر معنى." },
    { q: "هل Qulo آمن؟", a: "نعم. بياناتك مشفّرة، وخدمة التحقق من الملف الشخصي متاحة، ويمكنك حظر المستخدمين غير المرغوب فيهم." },
    { q: "في أي البلدان يتوفر Qulo؟", a: "يتوفر Qulo في جميع أنحاء العالم. ندعم 16 لغة مختلفة." },
  ],
  ja: [
    { q: "Quloはどう使いますか？", a: "質問を作成し、他のユーザーが解きます。すべての質問に正しく答えた人とマッチします。スワイプなし、クイズだけ！" },
    { q: "Quloは無料ですか？", a: "はい、Quloは無料で利用できます。追加機能にはPlusとPremiumのサブスクリプションがあります。" },
    { q: "Quloは他のマッチングアプリと何が違いますか？", a: "Quloはスワイプではなく、質問と回答によるマッチングシステムを採用しています。だからこそ、より深く意味のあるマッチが生まれます。" },
    { q: "Quloは安全ですか？", a: "はい。データは暗号化して保護され、プロフィール認証が利用でき、望まないユーザーをブロックできます。" },
    { q: "どの国で利用できますか？", a: "Quloは世界中で利用できます。16の言語に対応しています。" },
  ],
  ko: [
    { q: "Qulo는 어떻게 작동하나요?", a: "질문을 만들고 다른 사용자가 풀어요. 모든 질문에 정확하게 답한 사람과 매칭됩니다. 스와이프 없이, 퀴즈로!" },
    { q: "Qulo는 무료인가요?", a: "네, Qulo는 무료입니다. 추가 기능을 위한 Plus 및 Premium 구독이 있습니다." },
    { q: "Qulo는 다른 데이팅 앱과 무엇이 다른가요?", a: "Qulo는 스와이프 대신 질문과 답변 기반의 매칭 시스템을 사용합니다. 덕분에 더 깊고 의미 있는 매칭이 이루어집니다." },
    { q: "Qulo는 안전한가요?", a: "네. 데이터는 암호화되어 보호되고, 프로필 인증 기능이 있으며, 원하지 않는 사용자를 차단할 수 있습니다." },
    { q: "어느 나라에서 이용할 수 있나요?", a: "Qulo는 전 세계에서 이용할 수 있습니다. 16개 언어를 지원합니다." },
  ],
  zh: [
    { q: "Qulo如何运作？", a: "你创建问题，其他用户来解答。与正确回答你所有问题的人匹配。没有滑动，只有问答！" },
    { q: "Qulo免费吗？", a: "是的，Qulo免费使用。还有Plus和Premium订阅提供额外功能。" },
    { q: "Qulo与其他约会应用有什么不同？", a: "Qulo采用问答匹配系统，而不是滑动。因此能建立更深入、更有意义的匹配。" },
    { q: "Qulo安全吗？", a: "是的。你的数据经过加密保护，提供个人资料验证功能，你也可以屏蔽不想接触的用户。" },
    { q: "哪些国家可以使用？", a: "Qulo在全球范围内均可使用。我们支持16种不同的语言。" },
  ],
  ru: [
    { q: "Как работает Qulo?", a: "Вы создаёте вопросы, другие пользователи их решают. Вы матчитесь с тем, кто правильно ответит на все ваши вопросы. Никаких свайпов, только викторины!" },
    { q: "Qulo бесплатный?", a: "Да, Qulo можно использовать бесплатно. Для дополнительных функций доступны подписки Plus и Premium." },
    { q: "Чем Qulo отличается от других приложений для знакомств?", a: "Qulo использует систему подбора на основе вопросов и ответов вместо свайпов. Благодаря этому пары получаются более глубокими и осмысленными." },
    { q: "Qulo безопасен?", a: "Да. Ваши данные шифруются, доступна верификация профиля, а нежелательных пользователей можно заблокировать." },
    { q: "В каких странах доступен Qulo?", a: "Qulo доступен по всему миру. Мы поддерживаем 16 разных языков." },
  ],
  pt: [
    { q: "Como o Qulo funciona?", a: "Você cria perguntas, outros usuários resolvem. Você combina com quem responder corretamente a todas as suas perguntas. Sem deslizar, só quiz!" },
    { q: "O Qulo é grátis?", a: "Sim, o Qulo é gratuito. Assinaturas Plus e Premium estão disponíveis para recursos adicionais." },
    { q: "O que diferencia o Qulo de outros apps de namoro?", a: "O Qulo usa um sistema de combinação baseado em perguntas e respostas em vez de deslizar. Assim surgem combinações mais profundas e significativas." },
    { q: "O Qulo é seguro?", a: "Sim. Seus dados são criptografados, a verificação de perfil está disponível e você pode bloquear usuários indesejados." },
    { q: "Em quais países o Qulo está disponível?", a: "O Qulo está disponível no mundo todo. Oferecemos suporte a 16 idiomas diferentes." },
  ],
  it: [
    { q: "Come funziona Qulo?", a: "Crei domande, altri utenti le risolvono. Fai match con chi risponde correttamente a tutte le tue domande. Niente swipe, solo quiz!" },
    { q: "Qulo è gratuito?", a: "Sì, Qulo è gratuito. Sono disponibili abbonamenti Plus e Premium per funzionalità aggiuntive." },
    { q: "In cosa Qulo è diverso dalle altre app di incontri?", a: "Qulo usa un sistema di abbinamento basato su domande e risposte invece dello swipe. Così nascono match più profondi e significativi." },
    { q: "Qulo è sicuro?", a: "Sì. I tuoi dati sono crittografati, la verifica del profilo è disponibile e puoi bloccare gli utenti indesiderati." },
    { q: "In quali paesi è disponibile Qulo?", a: "Qulo è disponibile in tutto il mondo. Supportiamo 16 lingue diverse." },
  ],
  nl: [
    { q: "Hoe werkt Qulo?", a: "Jij maakt vragen, andere gebruikers lossen ze op. Je matcht met degene die al jouw vragen correct beantwoordt. Geen geswipe, alleen quizzen!" },
    { q: "Is Qulo gratis?", a: "Ja, Qulo is gratis te gebruiken. Voor extra functies zijn Plus- en Premium-abonnementen beschikbaar." },
    { q: "Wat maakt Qulo anders dan andere dating-apps?", a: "Qulo gebruikt een matchingsysteem op basis van vragen en antwoorden in plaats van swipen. Zo ontstaan er diepere en betekenisvollere matches." },
    { q: "Is Qulo veilig?", a: "Ja. Je gegevens worden versleuteld, profielverificatie is beschikbaar en je kunt ongewenste gebruikers blokkeren." },
    { q: "In welke landen is Qulo beschikbaar?", a: "Qulo is wereldwijd beschikbaar. We ondersteunen 16 verschillende talen." },
  ],
  pl: [
    { q: "Jak działa Qulo?", a: "Tworzysz pytania, a inni użytkownicy je rozwiązują. Dopasowujesz się do osoby, która poprawnie odpowie na wszystkie twoje pytania. Żadnego przesuwania, tylko quizy!" },
    { q: "Czy Qulo jest darmowe?", a: "Tak, z Qulo można korzystać za darmo. Dla dodatkowych funkcji dostępne są subskrypcje Plus i Premium." },
    { q: "Czym Qulo różni się od innych aplikacji randkowych?", a: "Qulo wykorzystuje system dopasowania oparty na pytaniach i odpowiedziach zamiast przesuwania. Dzięki temu powstają głębsze i bardziej wartościowe dopasowania." },
    { q: "Czy Qulo jest bezpieczne?", a: "Tak. Twoje dane są szyfrowane, dostępna jest weryfikacja profilu, a niechcianych użytkowników możesz zablokować." },
    { q: "W jakich krajach Qulo jest dostępne?", a: "Qulo jest dostępne na całym świecie. Obsługujemy 16 różnych języków." },
  ],
  sv: [
    { q: "Hur fungerar Qulo?", a: "Du skapar frågor och andra användare löser dem. Du matchar med den som svarar rätt på alla dina frågor. Inget swipande, bara quiz!" },
    { q: "Är Qulo gratis?", a: "Ja, Qulo är gratis att använda. Prenumerationerna Plus och Premium finns för extra funktioner." },
    { q: "Hur skiljer sig Qulo från andra dejtingappar?", a: "Qulo använder ett matchningssystem baserat på frågor och svar i stället för swipande. Det skapar djupare och mer meningsfulla matchningar." },
    { q: "Är Qulo säkert?", a: "Ja. Dina uppgifter krypteras, profilverifiering finns tillgänglig och du kan blockera oönskade användare." },
    { q: "I vilka länder finns Qulo?", a: "Qulo finns tillgängligt över hela världen. Vi stöder 16 olika språk." },
  ],
  hi: [
    { q: "Qulo कैसे काम करता है?", a: "आप सवाल बनाते हैं और दूसरे उपयोगकर्ता उन्हें हल करते हैं। जो व्यक्ति आपके सभी सवालों के सही जवाब देता है, उसी से आपका मैच होता है। कोई स्वाइप नहीं, सिर्फ़ क्विज़!" },
    { q: "क्या Qulo मुफ़्त है?", a: "हाँ, Qulo मुफ़्त में इस्तेमाल किया जा सकता है। अतिरिक्त सुविधाओं के लिए Plus और Premium सदस्यता भी उपलब्ध है।" },
    { q: "Qulo दूसरे डेटिंग ऐप्स से कैसे अलग है?", a: "Qulo स्वाइप की जगह सवाल-जवाब पर आधारित मैचिंग सिस्टम इस्तेमाल करता है। इससे ज़्यादा गहरे और सार्थक मैच बनते हैं।" },
    { q: "क्या Qulo सुरक्षित है?", a: "हाँ। आपका डेटा एन्क्रिप्ट करके सुरक्षित रखा जाता है, प्रोफ़ाइल सत्यापन उपलब्ध है और आप अनचाहे उपयोगकर्ताओं को ब्लॉक कर सकते हैं।" },
    { q: "यह किन देशों में उपलब्ध है?", a: "Qulo दुनिया भर में उपलब्ध है। हम 16 अलग-अलग भाषाओं का समर्थन करते हैं।" },
  ],
};

/** Per-page SEO metadata for sub-pages */
export const PAGE_SEO: Record<string, Record<string, { title: string; description: string }>> = {
  privacy: {
    tr: { title: "Gizlilik Politikası — Qulo", description: "Qulo gizlilik politikası. Verilerinizin nasıl toplandığını, kullanıldığını ve korunduğunu öğrenin." },
    en: { title: "Privacy Policy — Qulo", description: "Qulo privacy policy. Learn how your data is collected, used, and protected." },
    de: { title: "Datenschutzrichtlinie — Qulo", description: "Qulo Datenschutzrichtlinie. Erfahren Sie, wie Ihre Daten erhoben, verwendet und geschützt werden." },
    fr: { title: "Politique de Confidentialité — Qulo", description: "Politique de confidentialité de Qulo. Découvrez comment vos données sont collectées, utilisées et protégées." },
    es: { title: "Política de Privacidad — Qulo", description: "Política de privacidad de Qulo. Descubre cómo se recopilan, usan y protegen tus datos." },
    ar: { title: "سياسة الخصوصية — Qulo", description: "سياسة خصوصية Qulo. تعرف على كيفية جمع بياناتك واستخدامها وحمايتها." },
    ja: { title: "プライバシーポリシー — Qulo", description: "Quloのプライバシーポリシー。データの収集、使用、保護について。" },
    ko: { title: "개인정보 처리방침 — Qulo", description: "Qulo 개인정보 처리방침. 데이터 수집, 사용 및 보호에 대해 알아보세요." },
    zh: { title: "隐私政策 — Qulo", description: "Qulo隐私政策。了解您的数据如何被收集、使用和保护。" },
    ru: { title: "Политика конфиденциальности — Qulo", description: "Политика конфиденциальности Qulo. Узнайте, как собираются, используются и защищаются ваши данные." },
    pt: { title: "Política de Privacidade — Qulo", description: "Política de privacidade do Qulo. Saiba como seus dados são coletados, usados e protegidos." },
    it: { title: "Informativa sulla Privacy — Qulo", description: "Informativa sulla privacy di Qulo. Scopri come vengono raccolti, utilizzati e protetti i tuoi dati." },
  },
  terms: {
    tr: { title: "Kullanım Koşulları — Qulo", description: "Qulo kullanım koşulları ve hizmet şartları. Uygulamayı kullanmadan önce okuyun." },
    en: { title: "Terms of Service — Qulo", description: "Qulo terms of service. Read before using the app." },
    de: { title: "Nutzungsbedingungen — Qulo", description: "Qulo Nutzungsbedingungen. Bitte lesen Sie diese vor der Nutzung der App." },
    fr: { title: "Conditions d'Utilisation — Qulo", description: "Conditions d'utilisation de Qulo. Lisez avant d'utiliser l'application." },
    es: { title: "Términos de Servicio — Qulo", description: "Términos de servicio de Qulo. Lee antes de usar la aplicación." },
    ar: { title: "شروط الاستخدام — Qulo", description: "شروط خدمة Qulo. اقرأها قبل استخدام التطبيق." },
    ja: { title: "利用規約 — Qulo", description: "Quloの利用規約。アプリを使用する前にお読みください。" },
    ko: { title: "이용약관 — Qulo", description: "Qulo 이용약관. 앱 사용 전 읽어주세요." },
    zh: { title: "服务条款 — Qulo", description: "Qulo服务条款。使用应用前请阅读。" },
    ru: { title: "Условия использования — Qulo", description: "Условия использования Qulo. Прочтите перед использованием приложения." },
    pt: { title: "Termos de Serviço — Qulo", description: "Termos de serviço do Qulo. Leia antes de usar o aplicativo." },
    it: { title: "Termini di Servizio — Qulo", description: "Termini di servizio di Qulo. Leggere prima di utilizzare l'app." },
  },
  help: {
    tr: { title: "Yardım & SSS — Qulo", description: "Qulo hakkında sık sorulan sorular ve yardım merkezi. Nasıl çalışır, hesap yönetimi ve daha fazlası." },
    en: { title: "Help & FAQ — Qulo", description: "Frequently asked questions and help center for Qulo. How it works, account management and more." },
    de: { title: "Hilfe & FAQ — Qulo", description: "Häufig gestellte Fragen und Hilfezentrum für Qulo." },
    fr: { title: "Aide & FAQ — Qulo", description: "Questions fréquemment posées et centre d'aide pour Qulo." },
    es: { title: "Ayuda y Preguntas Frecuentes — Qulo", description: "Preguntas frecuentes y centro de ayuda de Qulo." },
  },
  blog: {
    tr: { title: "Blog — Qulo | Dating, İlişkiler ve Uyumluluk", description: "Qulo blog: dating trendleri, ilişki ipuçları, swipe yorgunluğu, quiz dating ve daha fazlası." },
    en: { title: "Blog — Qulo | Dating, Relationships & Compatibility", description: "Qulo blog: dating trends, relationship tips, swipe fatigue, quiz dating and more." },
    de: { title: "Blog — Qulo | Dating, Beziehungen & Kompatibilität", description: "Qulo Blog: Dating-Trends, Beziehungstipps und mehr." },
    fr: { title: "Blog — Qulo | Dating, Relations & Compatibilité", description: "Blog Qulo : tendances dating, conseils relations et plus." },
    es: { title: "Blog — Qulo | Citas, Relaciones y Compatibilidad", description: "Blog Qulo: tendencias de citas, consejos de relaciones y más." },
    ar: { title: "مدونة — Qulo | المواعدة والعلاقات", description: "مدونة Qulo: اتجاهات المواعدة ونصائح العلاقات والمزيد." },
    ja: { title: "ブログ — Qulo | デート・恋愛・相性", description: "Quloブログ：デートトレンド、恋愛のヒントなど。" },
    ko: { title: "블로그 — Qulo | 데이팅, 관계 & 호환성", description: "Qulo 블로그: 데이팅 트렌드, 관계 팁 등." },
    zh: { title: "博客 — Qulo | 约会、关系与兼容性", description: "Qulo博客：约会趋势、关系建议等。" },
    ru: { title: "Блог — Qulo | Свидания, Отношения и Совместимость", description: "Блог Qulo: тренды знакомств, советы по отношениям и многое другое." },
    pt: { title: "Blog — Qulo | Namoro, Relacionamentos e Compatibilidade", description: "Blog Qulo: tendências de namoro, dicas de relacionamento e mais." },
    it: { title: "Blog — Qulo | Incontri, Relazioni e Compatibilità", description: "Blog Qulo: tendenze degli incontri, consigli sulle relazioni e altro." },
    nl: { title: "Blog — Qulo | Dating, Relaties & Compatibiliteit", description: "Qulo Blog: datingtrends, relatietips en meer." },
    pl: { title: "Blog — Qulo | Randki, Związki i Kompatybilność", description: "Blog Qulo: trendy randkowe, porady dotyczące związków i więcej." },
    sv: { title: "Blogg — Qulo | Dejting, Relationer & Kompatibilitet", description: "Qulo Blogg: dejtingtrender, relationstips och mer." },
    hi: { title: "ब्लॉग — Qulo | डेटिंग, रिश्ते और अनुकूलता", description: "Qulo ब्लॉग: डेटिंग ट्रेंड, रिश्ते की सलाह और बहुत कुछ।" },
  },
  dating: {
    tr: { title: "Sehirlerde Dating — Qulo", description: "Dunyanin en buyuk sehirlerinde Qulo ile tanisin. Sorularla eslesin, anlamli baglantilar kurun." },
    en: { title: "Dating in Cities — Qulo", description: "Meet people with Qulo in the world's biggest cities. Match through questions, build meaningful connections." },
    de: { title: "Dating in Stadten — Qulo", description: "Treffen Sie Menschen mit Qulo in den grossten Stadten der Welt. Matchen Sie durch Fragen." },
    fr: { title: "Dating dans les villes — Qulo", description: "Rencontrez des gens avec Qulo dans les plus grandes villes du monde. Matchez par questions." },
    es: { title: "Citas en ciudades — Qulo", description: "Conoce gente con Qulo en las ciudades mas grandes del mundo. Haz match con preguntas." },
    ar: { title: "المواعدة في المدن — Qulo", description: "تعرف على أشخاص مع Qulo في أكبر مدن العالم. تطابق من خلال الأسئلة." },
    ru: { title: "Знакомства в городах — Qulo", description: "Встречайте людей с Qulo в крупнейших городах мира. Знакомьтесь через вопросы." },
    pt: { title: "Namoro em cidades — Qulo", description: "Conheca pessoas com Qulo nas maiores cidades do mundo. Combine por perguntas." },
    it: { title: "Incontri nelle citta — Qulo", description: "Incontra persone con Qulo nelle piu grandi citta del mondo. Fai match con domande." },
    ja: { title: "都市でデート — Qulo", description: "世界の大都市でQuloと出会いましょう。質問でマッチング。" },
    ko: { title: "도시에서 데이팅 — Qulo", description: "세계 최대 도시에서 Qulo로 사람들을 만나세요. 질문으로 매칭." },
    zh: { title: "城市约会 — Qulo", description: "在世界最大的城市用Qulo认识人。通过问题匹配。" },
    nl: { title: "Dating in steden — Qulo", description: "Ontmoet mensen met Qulo in de grootste steden ter wereld. Match via vragen." },
    pl: { title: "Randki w miastach — Qulo", description: "Poznaj ludzi z Qulo w najwiekszych miastach swiata. Dopasowuj sie przez pytania." },
    sv: { title: "Dejting i stader — Qulo", description: "Traffa manniskor med Qulo i varldens storsta stader. Matcha genom fragor." },
    hi: { title: "शहरों में डेटिंग — Qulo", description: "दुनिया के सबसे बड़े शहरों में Qulo से लोगों से मिलें। सवालों से मैच करें।" },
  },
  country: {
    tr: { title: "Ulkelerde Dating — Qulo", description: "Dunya capinda ulkelerde Qulo ile tanisin. Turkiye, Almanya, Fransa, Ispanya ve daha fazlasi." },
    en: { title: "Dating by Country — Qulo", description: "Meet people with Qulo in countries worldwide. Turkey, Germany, France, Spain and more." },
    de: { title: "Dating nach Land — Qulo", description: "Treffen Sie Menschen mit Qulo in Landern weltweit. Turkei, Deutschland, Frankreich, Spanien und mehr." },
    fr: { title: "Dating par pays — Qulo", description: "Rencontrez des gens avec Qulo dans les pays du monde entier. Turquie, Allemagne, France, Espagne et plus." },
    es: { title: "Citas por pais — Qulo", description: "Conoce gente con Qulo en paises de todo el mundo. Turquia, Alemania, Francia, Espana y mas." },
    ar: { title: "المواعدة حسب الدولة — Qulo", description: "تعرف على أشخاص مع Qulo في دول حول العالم. تركيا، ألمانيا، فرنسا، إسبانيا والمزيد." },
    ru: { title: "Знакомства по странам — Qulo", description: "Встречайте людей с Qulo в странах по всему миру. Турция, Германия, Франция, Испания и другие." },
    pt: { title: "Namoro por pais — Qulo", description: "Conheca pessoas com Qulo em paises ao redor do mundo. Turquia, Alemanha, Franca, Espanha e mais." },
    it: { title: "Incontri per paese — Qulo", description: "Incontra persone con Qulo nei paesi di tutto il mondo. Turchia, Germania, Francia, Spagna e altro." },
    ja: { title: "国別デート — Qulo", description: "世界中の国でQuloと出会いましょう。トルコ、ドイツ、フランス、スペインなど。" },
    ko: { title: "국가별 데이팅 — Qulo", description: "전 세계 국가에서 Qulo로 사람들을 만나세요. 터키, 독일, 프랑스, 스페인 등." },
    zh: { title: "按国家约会 — Qulo", description: "在世界各国用Qulo认识人。土耳其、德国、法国、西班牙等。" },
    nl: { title: "Dating per land — Qulo", description: "Ontmoet mensen met Qulo in landen wereldwijd. Turkije, Duitsland, Frankrijk, Spanje en meer." },
    pl: { title: "Randki wedlug kraju — Qulo", description: "Poznaj ludzi z Qulo w krajach na calym swiecie. Turcja, Niemcy, Francja, Hiszpania i wiecej." },
    sv: { title: "Dejting efter land — Qulo", description: "Traffa manniskor med Qulo i lander varlden over. Turkiet, Tyskland, Frankrike, Spanien och mer." },
    hi: { title: "देश के अनुसार डेटिंग — Qulo", description: "दुनिया भर के देशों में Qulo से लोगों से मिलें। तुर्की, जर्मनी, फ्रांस, स्पेन और अधिक।" },
  },
  features: {
    tr: { title: "Ozellikler — Qulo | Quiz Dating App", description: "Qulo'nun benzersiz ozellikleri: quiz dating, kisilik eslestirme, AI soru onerileri ve daha fazlasi." },
    en: { title: "Features — Qulo | Quiz Dating App", description: "Qulo's unique features: quiz dating, personality matching, AI question suggestions and more." },
    de: { title: "Funktionen — Qulo | Quiz Dating App", description: "Qulos einzigartige Funktionen: Quiz-Dating, Personlichkeits-Matching, KI-Fragenvorschlage und mehr." },
    fr: { title: "Fonctionnalites — Qulo | Quiz Dating App", description: "Les fonctionnalites uniques de Qulo : quiz dating, matching de personnalite, suggestions de questions IA et plus." },
    es: { title: "Caracteristicas — Qulo | Quiz Dating App", description: "Caracteristicas unicas de Qulo: quiz dating, matching de personalidad, sugerencias de preguntas con IA y mas." },
  },
  glossary: {
    tr: { title: "Dating S\u00F6zl\u00FC\u011F\u00FC \u2014 A'dan Z'ye Dating Terimleri | Qulo", description: "Ghosting, catfishing, swipe fatigue ve daha fazlas\u0131. Online dating d\u00FCnyas\u0131n\u0131n t\u00FCm terimlerini \u00F6\u011Frenin." },
    en: { title: "Dating Glossary \u2014 A to Z Dating Terms | Qulo", description: "Ghosting, catfishing, swipe fatigue and more. Learn all the terms of the online dating world." },
    de: { title: "Dating-Glossar \u2014 Dating-Begriffe von A bis Z | Qulo", description: "Ghosting, Catfishing, Swipe-M\u00FCdigkeit und mehr. Lernen Sie alle Begriffe der Online-Dating-Welt." },
    fr: { title: "Glossaire du Dating \u2014 Termes de A \u00E0 Z | Qulo", description: "Ghosting, catfishing, fatigue du swipe et plus encore. D\u00E9couvrez tous les termes du dating en ligne." },
    es: { title: "Glosario de Citas \u2014 T\u00E9rminos de la A a la Z | Qulo", description: "Ghosting, catfishing, cansancio del swipe y m\u00E1s. Aprende todos los t\u00E9rminos del mundo de las citas online." },
    ar: { title: "\u0642\u0627\u0645\u0648\u0633 \u0627\u0644\u0645\u0648\u0627\u0639\u062F\u0629 \u2014 \u0645\u0635\u0637\u0644\u062D\u0627\u062A \u0645\u0646 \u0627\u0644\u0623\u0644\u0641 \u0625\u0644\u0649 \u0627\u0644\u064A\u0627\u0621 | Qulo", description: "Ghosting \u0648catfishing \u0648\u0625\u0631\u0647\u0627\u0642 \u0627\u0644\u062A\u0645\u0631\u064A\u0631 \u0648\u0627\u0644\u0645\u0632\u064A\u062F. \u062A\u0639\u0644\u0645 \u062C\u0645\u064A\u0639 \u0645\u0635\u0637\u0644\u062D\u0627\u062A \u0639\u0627\u0644\u0645 \u0627\u0644\u0645\u0648\u0627\u0639\u062F\u0629." },
    ja: { title: "\u30C7\u30FC\u30C8\u7528\u8A9E\u96C6 \u2014 A\u304B\u3089Z\u307E\u3067\u306E\u30C7\u30FC\u30C8\u7528\u8A9E | Qulo", description: "\u30B4\u30FC\u30B9\u30C6\u30A3\u30F3\u30B0\u3001\u30AD\u30E3\u30C3\u30C8\u30D5\u30A3\u30C3\u30B7\u30F3\u30B0\u306A\u3069\u3002\u30AA\u30F3\u30E9\u30A4\u30F3\u30C7\u30FC\u30C8\u306E\u5168\u7528\u8A9E\u3092\u5B66\u3073\u307E\u3057\u3087\u3046\u3002" },
    ko: { title: "\uB370\uC774\uD305 \uC6A9\uC5B4\uC9D1 \u2014 A\uBD80\uD130 Z\uAE4C\uC9C0 | Qulo", description: "\uACE0\uC2A4\uD305, \uCEBF\uD53C\uC2DC\uADF8 \uB4F1. \uC628\uB77C\uC778 \uB370\uC774\uD305 \uC138\uACC4\uC758 \uBAA8\uB4E0 \uC6A9\uC5B4\uB97C \uBC30\uC6B0\uC138\uC694." },
    zh: { title: "\u7EA6\u4F1A\u672F\u8BED\u8868 \u2014 A\u5230Z\u7EA6\u4F1A\u672F\u8BED | Qulo", description: "Ghosting\u3001catfishing\u3001\u6ED1\u52A8\u75B2\u52B3\u7B49\u3002\u5B66\u4E60\u5728\u7EBF\u7EA6\u4F1A\u4E16\u754C\u7684\u6240\u6709\u672F\u8BED\u3002" },
    ru: { title: "\u0413\u043B\u043E\u0441\u0441\u0430\u0440\u0438\u0439 \u0437\u043D\u0430\u043A\u043E\u043C\u0441\u0442\u0432 \u2014 \u0422\u0435\u0440\u043C\u0438\u043D\u044B \u043E\u0442 \u0410 \u0434\u043E \u042F | Qulo", description: "\u0413\u043E\u0441\u0442\u0438\u043D\u0433, \u043A\u044D\u0442\u0444\u0438\u0448\u0438\u043D\u0433, \u0443\u0441\u0442\u0430\u043B\u043E\u0441\u0442\u044C \u043E\u0442 \u0441\u0432\u0430\u0439\u043F\u043E\u0432 \u0438 \u043C\u043D\u043E\u0433\u043E\u0435 \u0434\u0440\u0443\u0433\u043E\u0435." },
    pt: { title: "Gloss\u00E1rio de Namoro \u2014 Termos de A a Z | Qulo", description: "Ghosting, catfishing, fadiga do swipe e mais. Aprenda todos os termos do mundo do namoro online." },
    it: { title: "Glossario del Dating \u2014 Termini dalla A alla Z | Qulo", description: "Ghosting, catfishing, stanchezza da swipe e altro. Scopri tutti i termini del mondo degli incontri online." },
    nl: { title: "Dating Woordenlijst \u2014 Dating Termen van A tot Z | Qulo", description: "Ghosting, catfishing, swipe-moeheid en meer. Leer alle termen van de online datingwereld." },
    pl: { title: "S\u0142owniczek Randkowy \u2014 Terminy od A do Z | Qulo", description: "Ghosting, catfishing, zm\u0119czenie swipe'owaniem i wi\u0119cej. Poznaj wszystkie terminy \u015Bwiata randk\u00F3w online." },
    sv: { title: "Dejting Ordlista \u2014 Dejtingtermer fr\u00E5n A till \u00D6 | Qulo", description: "Ghosting, catfishing, swipe-tr\u00F6tthet och mer. L\u00E4r dig alla termer i online-dejtingv\u00E4rlden." },
    hi: { title: "\u0921\u0947\u091F\u093F\u0902\u0917 \u0936\u092C\u094D\u0926\u093E\u0935\u0932\u0940 \u2014 A \u0938\u0947 Z \u0924\u0915 \u0921\u0947\u091F\u093F\u0902\u0917 \u0936\u092C\u094D\u0926 | Qulo", description: "\u0917\u094B\u0938\u094D\u091F\u093F\u0902\u0917, \u0915\u0948\u091F\u092B\u093F\u0936\u093F\u0902\u0917 \u0914\u0930 \u0905\u0927\u093F\u0915\u0964 \u0911\u0928\u0932\u093E\u0907\u0928 \u0921\u0947\u091F\u093F\u0902\u0917 \u0926\u0941\u0928\u093F\u092F\u093E \u0915\u0947 \u0938\u092D\u0940 \u0936\u092C\u094D\u0926 \u0938\u0940\u0916\u0947\u0902\u0964" },
  },
  statistics: {
    tr: { title: "Dating İstatistikleri 2026 — Veri Raporu | Qulo", description: "Online dating dünyasının en güncel istatistikleri. Swipe yorgunluğu, eşleşme oranları, demografik veriler ve 2026 trendleri. Kapsamlı veri raporu." },
    en: { title: "Dating Statistics 2026 — Data Report | Qulo", description: "The most current statistics from the online dating world. Swipe fatigue, match rates, demographics and 2026 trends. Comprehensive data report." },
    de: { title: "Dating-Statistiken 2026 — Datenbericht | Qulo", description: "Aktuellste Statistiken aus der Online-Dating-Welt. Swipe-Müdigkeit, Match-Raten, Demografie und 2026-Trends." },
    fr: { title: "Statistiques Dating 2026 — Rapport de données | Qulo", description: "Statistiques les plus récentes du monde du dating en ligne. Fatigue du swipe, taux de match, démographie et tendances 2026." },
    es: { title: "Estadísticas de Citas 2026 — Informe de Datos | Qulo", description: "Estadísticas más recientes del mundo de las citas online. Cansancio del swipe, tasas de match, demografía y tendencias 2026." },
    ar: { title: "إحصائيات المواعدة 2026 — تقرير البيانات | Qulo", description: "أحدث الإحصائيات من عالم المواعدة عبر الإنترنت. إرهاق التمرير، معدلات التطابق، الديموغرافيا واتجاهات 2026." },
    ja: { title: "デート統計 2026 — データレポート | Qulo", description: "オンラインデート業界の最新統計。スワイプ疲れ、マッチ率、人口統計、2026年トレンド。" },
    ko: { title: "데이팅 통계 2026 — 데이터 리포트 | Qulo", description: "온라인 데이팅 세계의 최신 통계. 스와이프 피로, 매칭률, 인구통계 및 2026년 트렌드." },
    zh: { title: "约会统计 2026 — 数据报告 | Qulo", description: "在线约会世界最新统计数据。滑动疲劳、匹配率、人口统计和2026年趋势。" },
    ru: { title: "Статистика знакомств 2026 — Отчёт | Qulo", description: "Самые актуальные статистические данные из мира онлайн-знакомств. Усталость от свайпов, показатели совпадений, демография и тренды 2026." },
    pt: { title: "Estatísticas de Namoro 2026 — Relatório de Dados | Qulo", description: "Estatísticas mais recentes do mundo do namoro online. Fadiga do swipe, taxas de match, demografia e tendências 2026." },
    it: { title: "Statistiche Dating 2026 — Report sui Dati | Qulo", description: "Statistiche più recenti del mondo degli incontri online. Stanchezza da swipe, tassi di match, demografia e trend 2026." },
    nl: { title: "Dating Statistieken 2026 — Datarapport | Qulo", description: "Meest actuele statistieken uit de online datingwereld. Swipe-moeheid, matchpercentages, demografie en 2026 trends." },
    pl: { title: "Statystyki Randkowe 2026 — Raport Danych | Qulo", description: "Najnowsze statystyki ze świata randek online. Zmęczenie swipe, wskaźniki dopasowań, demografia i trendy 2026." },
    sv: { title: "Dejtingstatistik 2026 — Datarapport | Qulo", description: "De senaste statistiken från online-dejtingvärlden. Swipe-trötthet, matchningsfrekvens, demografi och 2026-trender." },
    hi: { title: "डेटिंग आंकड़े 2026 — डेटा रिपोर्ट | Qulo", description: "ऑनलाइन डेटिंग दुनिया से सबसे ताज़ा आंकड़े। स्वाइप थकान, मैच दरें, जनसांख्यिकी और 2026 के रुझान।" },
  },
  press: {
    tr: { title: "Basın Kiti — Qulo | Medya, Logo, Brand Assets", description: "Qulo basın kiti. Logo, marka renkleri, founder bilgisi, fact sheet ve medya iletişim. Gazeteciler ve bloggerlar için." },
    en: { title: "Press Kit — Qulo | Media, Logo, Brand Assets", description: "Qulo press kit. Logos, brand colors, founder info, fact sheet and media contact. For journalists and bloggers." },
    de: { title: "Pressekit — Qulo | Medien, Logo, Brand Assets", description: "Qulo Pressekit. Logos, Markenfarben, Gründer-Info, Fact Sheet und Medienkontakt." },
    fr: { title: "Kit Presse — Qulo | Médias, Logo, Brand Assets", description: "Kit presse Qulo. Logos, couleurs de marque, info fondateur, fact sheet et contact média." },
    es: { title: "Kit de Prensa — Qulo | Medios, Logo, Brand Assets", description: "Kit de prensa Qulo. Logos, colores de marca, info del fundador, fact sheet y contacto media." },
    ar: { title: "ملف الصحافة — Qulo | الإعلام، الشعار، أصول العلامة", description: "ملف صحافة Qulo. الشعارات وألوان العلامة ومعلومات المؤسس وورقة الحقائق وجهة الاتصال الإعلامية." },
    ru: { title: "Пресс-кит — Qulo | Медиа, Логотип, Brand Assets", description: "Пресс-кит Qulo. Логотипы, фирменные цвета, информация об основателе, факт-лист и медиаконтакт." },
    pt: { title: "Kit de Imprensa — Qulo | Mídia, Logo, Brand Assets", description: "Kit de imprensa do Qulo. Logos, cores da marca, info do fundador, fact sheet e contato de mídia." },
    it: { title: "Kit Stampa — Qulo | Media, Logo, Brand Assets", description: "Kit stampa Qulo. Loghi, colori del marchio, info fondatore, fact sheet e contatto media." },
    ja: { title: "プレスキット — Qulo | メディア、ロゴ、ブランド資産", description: "Qulo プレスキット。ロゴ、ブランドカラー、創業者情報、ファクトシート、メディア連絡先。" },
    ko: { title: "프레스 키트 — Qulo | 미디어, 로고, 브랜드 자산", description: "Qulo 프레스 키트. 로고, 브랜드 컬러, 창업자 정보, 팩트 시트 및 미디어 연락처." },
    zh: { title: "媒体资料 — Qulo | 媒体、Logo、品牌资产", description: "Qulo 媒体资料包。Logo、品牌色、创始人信息、事实表和媒体联系方式。" },
    nl: { title: "Perskit — Qulo | Media, Logo, Brand Assets", description: "Qulo perskit. Logo's, merkkleuren, oprichtersinfo, fact sheet en mediacontact." },
    pl: { title: "Materiały Prasowe — Qulo | Media, Logo, Brand Assets", description: "Materiały prasowe Qulo. Logo, kolory marki, info o założycielu, fact sheet i kontakt medialny." },
    sv: { title: "Presskit — Qulo | Media, Logo, Brand Assets", description: "Qulo presskit. Logotyper, varumärkesfärger, grundarinfo, faktablad och mediekontakt." },
    hi: { title: "प्रेस किट — Qulo | मीडिया, लोगो, ब्रांड एसेट्स", description: "Qulo प्रेस किट। लोगो, ब्रांड रंग, संस्थापक जानकारी, फैक्ट शीट और मीडिया संपर्क।" },
  },
  howto: {
    tr: { title: "Qulo Nasıl Kullanılır — Rehberler | Qulo", description: "Qulo uygulamasını nasıl kullanacağınıza dair adım adım rehberler. Profil oluşturma, soru yazma, eşleşme alma ve sohbet ipuçları." },
    en: { title: "How to Use Qulo — Guides | Qulo", description: "Step-by-step guides on how to use the Qulo app. Profile creation, writing questions, getting matches and chat tips." },
    de: { title: "Wie man Qulo benutzt — Anleitungen | Qulo", description: "Schritt-für-Schritt-Anleitungen zur Qulo-App. Profilerstellung, Fragen schreiben, Matches bekommen und Chat-Tipps." },
    fr: { title: "Comment utiliser Qulo — Guides | Qulo", description: "Guides étape par étape pour utiliser l'app Qulo. Création de profil, écrire des questions, obtenir des matchs." },
    es: { title: "Cómo usar Qulo — Guías | Qulo", description: "Guías paso a paso para usar la app Qulo. Creación de perfil, escribir preguntas, conseguir matches y consejos de chat." },
    ar: { title: "كيفية استخدام Qulo — أدلة | Qulo", description: "أدلة خطوة بخطوة لاستخدام تطبيق Qulo. إنشاء الملف الشخصي، كتابة الأسئلة، الحصول على تطابقات." },
    ru: { title: "Как пользоваться Qulo — Руководства | Qulo", description: "Пошаговые руководства по использованию приложения Qulo. Создание профиля, написание вопросов и получение пар." },
    pt: { title: "Como usar o Qulo — Guias | Qulo", description: "Guias passo a passo para usar o app Qulo. Criação de perfil, escrever perguntas, conseguir matches." },
    it: { title: "Come usare Qulo — Guide | Qulo", description: "Guide passo passo per usare l'app Qulo. Creazione del profilo, scrivere domande, ottenere match." },
    ja: { title: "Quloの使い方 — ガイド | Qulo", description: "Quloアプリの使い方ステップバイステップガイド。プロフィール作成、質問作成、マッチ獲得。" },
    ko: { title: "Qulo 사용 방법 — 가이드 | Qulo", description: "Qulo 앱 사용을 위한 단계별 가이드. 프로필 생성, 질문 작성, 매칭 얻기." },
    zh: { title: "Qulo 使用指南 — 指南 | Qulo", description: "Qulo 应用使用的分步指南。个人资料创建、撰写问题、获得匹配。" },
    nl: { title: "Hoe Qulo te gebruiken — Gidsen | Qulo", description: "Stap-voor-stap gidsen voor het gebruik van de Qulo-app. Profiel maken, vragen schrijven, matches krijgen." },
    pl: { title: "Jak używać Qulo — Poradniki | Qulo", description: "Przewodniki krok po kroku dotyczące korzystania z aplikacji Qulo. Tworzenie profilu, pisanie pytań, zdobywanie dopasowań." },
    sv: { title: "Hur man använder Qulo — Guider | Qulo", description: "Steg-för-steg-guider för hur man använder Qulo-appen. Profilskapande, skriva frågor, få matcher." },
    hi: { title: "Qulo कैसे इस्तेमाल करें — गाइड | Qulo", description: "Qulo ऐप का उपयोग करने के लिए चरण-दर-चरण गाइड। प्रोफ़ाइल बनाना, प्रश्न लिखना, मैच प्राप्त करना।" },
  },
  advice: {
    tr: { title: "Dating Tavsiyeleri — Qulo | İlişki, Profil, Güvenlik Rehberi", description: "Dating, ilişki ve online tanışma için uzman tavsiyeleri. İlk buluşma, profil yazma, red flag'ler ve uzak mesafe ilişkiler." },
    en: { title: "Dating Advice — Qulo | Relationship, Profile, Safety Guides", description: "Expert advice for dating, relationships and online meeting. First dates, profile writing, red flags and long distance relationships." },
    de: { title: "Dating-Ratgeber — Qulo | Beziehung, Profil, Sicherheit", description: "Expertenratgeber für Dating, Beziehungen und Online-Kennenlernen. Erste Dates, Profilgestaltung, Warnsignale und Fernbeziehungen." },
    fr: { title: "Conseils Dating — Qulo | Relations, Profil, Sécurité", description: "Conseils d'experts pour le dating, les relations et les rencontres en ligne. Premiers rendez-vous, création de profil, drapeaux rouges." },
    es: { title: "Consejos de Citas — Qulo | Relaciones, Perfil, Seguridad", description: "Consejos expertos para citas, relaciones y encuentros online. Primeras citas, escribir perfil, banderas rojas y relaciones a distancia." },
    ar: { title: "نصائح المواعدة — Qulo | دليل العلاقات والملف والأمان", description: "نصائح الخبراء للمواعدة والعلاقات واللقاءات عبر الإنترنت. المواعيد الأولى، كتابة الملف الشخصي، العلامات الحمراء والعلاقات عن بُعد." },
    ru: { title: "Советы по знакомствам — Qulo", description: "Экспертные советы по знакомствам, отношениям и онлайн-общению. Первые свидания, написание профиля и отношения на расстоянии." },
    pt: { title: "Conselhos de Namoro — Qulo", description: "Conselhos especializados para namoro, relacionamentos e encontros online. Primeiros encontros, perfil e relacionamentos à distância." },
    it: { title: "Consigli sugli Incontri — Qulo", description: "Consigli esperti per incontri, relazioni e appuntamenti online. Primi appuntamenti, profilo e relazioni a distanza." },
    ja: { title: "デートアドバイス — Qulo", description: "デート、恋愛、オンラインでの出会いに関する専門的なアドバイス。初デート、プロフィール、遠距離恋愛。" },
    ko: { title: "데이팅 조언 — Qulo", description: "데이팅, 관계 및 온라인 만남에 대한 전문가 조언. 첫 데이트, 프로필 작성 및 장거리 관계." },
    zh: { title: "约会建议 — Qulo", description: "关于约会、关系和在线相识的专家建议。初次约会、个人资料撰写和异地关系。" },
    nl: { title: "Datingadvies — Qulo", description: "Expertadvies voor daten, relaties en online ontmoetingen. Eerste dates, profiel schrijven en langeafstandsrelaties." },
    pl: { title: "Porady Randkowe — Qulo", description: "Porady ekspertów dotyczące randek, związków i spotkań online. Pierwsze randki, tworzenie profilu i związki na odległość." },
    sv: { title: "Dejtingråd — Qulo", description: "Expertråd för dejting, relationer och onlinemöten. Första dejter, profilskrivning och distansförhållanden." },
    hi: { title: "डेटिंग सलाह — Qulo", description: "डेटिंग, रिश्ते और ऑनलाइन मुलाकात के लिए विशेषज्ञ सलाह। पहली डेट, प्रोफ़ाइल लेखन और दूरी के रिश्ते।" },
  },
  trends: {
    tr: { title: "Dating Trendleri 2026 — Online Tanışmanın Geleceği | Qulo", description: "2026'nın en önemli dating trendleri: quiz dating, swipe yorgunluğu, AI eşleşme, slow dating ve daha fazlası. Uzman analiz ve veri raporu." },
    en: { title: "Dating Trends 2026 — The Future of Online Dating | Qulo", description: "Top dating trends of 2026: quiz dating, swipe fatigue, AI matching, slow dating and more. Expert analysis and data report." },
    de: { title: "Dating-Trends 2026 — Die Zukunft des Online-Datings | Qulo", description: "Top-Dating-Trends 2026: Quiz-Dating, Swipe-Müdigkeit, KI-Matching, Slow Dating." },
    fr: { title: "Tendances Dating 2026 — L'Avenir du Dating en Ligne | Qulo", description: "Top tendances dating 2026: quiz dating, fatigue du swipe, matching IA." },
    es: { title: "Tendencias de Citas 2026 — El Futuro del Dating Online | Qulo", description: "Top tendencias de citas 2026: quiz dating, cansancio del swipe, matching con IA." },
    ar: { title: "اتجاهات المواعدة 2026 — مستقبل المواعدة عبر الإنترنت | Qulo", description: "أهم اتجاهات المواعدة لعام 2026: المواعدة عبر الاختبارات، إرهاق التمرير، المطابقة بالذكاء الاصطناعي، والمواعدة البطيئة." },
    ru: { title: "Тренды знакомств 2026 — Будущее онлайн-знакомств | Qulo", description: "Главные тренды знакомств 2026: quiz dating, усталость от свайпов, AI-подбор, slow dating и многое другое." },
    pt: { title: "Tendências de Namoro 2026 — O Futuro do Namoro Online | Qulo", description: "Principais tendências de namoro 2026: quiz dating, fadiga do swipe, matching com IA, slow dating e mais." },
    it: { title: "Tendenze Dating 2026 — Il Futuro degli Incontri Online | Qulo", description: "Principali tendenze dating 2026: quiz dating, stanchezza da swipe, matching AI, slow dating e altro." },
    ja: { title: "デートトレンド2026 — オンラインデートの未来 | Qulo", description: "2026年の主要デートトレンド：クイズデート、スワイプ疲れ、AIマッチング、スローデートなど。" },
    ko: { title: "데이팅 트렌드 2026 — 온라인 데이팅의 미래 | Qulo", description: "2026년 주요 데이팅 트렌드: 퀴즈 데이팅, 스와이프 피로, AI 매칭, 슬로우 데이팅 등." },
    zh: { title: "约会趋势2026 — 在线约会的未来 | Qulo", description: "2026年主要约会趋势：问答约会、滑动疲劳、AI匹配、慢约会等。" },
    nl: { title: "Datingtrends 2026 — De Toekomst van Online Daten | Qulo", description: "Belangrijkste datingtrends 2026: quiz dating, swipe-moeheid, AI-matching, slow dating en meer." },
    pl: { title: "Trendy Randkowe 2026 — Przyszłość Randek Online | Qulo", description: "Najważniejsze trendy randkowe 2026: quiz dating, zmęczenie swipe, AI matching, slow dating i więcej." },
    sv: { title: "Dejtingtrender 2026 — Framtidens Online-Dejting | Qulo", description: "Topp dejtingtrender 2026: quiz dating, swipe-trötthet, AI-matchning, slow dating och mer." },
    hi: { title: "डेटिंग रुझान 2026 — ऑनलाइन डेटिंग का भविष्य | Qulo", description: "2026 के शीर्ष डेटिंग रुझान: क्विज़ डेटिंग, स्वाइप थकान, AI मैचिंग, स्लो डेटिंग और अधिक।" },
  },
  pricing: {
    tr: { title: "Fiyatlandırma — Qulo | Free, Plus, Premium", description: "Qulo üyelik planları: Free (ücretsiz), Plus ($4.99/ay), Premium ($9.99/ay). Her zaman ücretsiz başla." },
    en: { title: "Pricing — Qulo | Free, Plus, Premium", description: "Qulo membership plans: Free, Plus ($4.99/month), Premium ($9.99/month). Always start free." },
    de: { title: "Preise — Qulo | Free, Plus, Premium", description: "Qulo Mitgliedschaftspläne: Free, Plus, Premium." },
    fr: { title: "Tarifs — Qulo | Free, Plus, Premium", description: "Plans d'adhésion Qulo: Free, Plus, Premium." },
    es: { title: "Precios — Qulo | Free, Plus, Premium", description: "Planes de membresía Qulo: Free, Plus, Premium." },
    ar: { title: "الأسعار — Qulo", description: "خطط عضوية Qulo: Free و Plus و Premium." },
    ru: { title: "Цены — Qulo", description: "Планы подписки Qulo: Free, Plus, Premium." },
    pt: { title: "Preços — Qulo", description: "Planos de assinatura Qulo: Free, Plus, Premium." },
    it: { title: "Prezzi — Qulo", description: "Piani di abbonamento Qulo: Free, Plus, Premium." },
    ja: { title: "料金 — Qulo", description: "Qulo会員プラン: Free, Plus, Premium." },
    ko: { title: "요금제 — Qulo", description: "Qulo 멤버십 플랜: Free, Plus, Premium." },
    zh: { title: "价格 — Qulo", description: "Qulo会员计划: Free, Plus, Premium." },
    nl: { title: "Prijzen — Qulo", description: "Qulo lidmaatschapsplannen: Free, Plus, Premium." },
    pl: { title: "Ceny — Qulo", description: "Plany członkowskie Qulo: Free, Plus, Premium." },
    sv: { title: "Priser — Qulo", description: "Qulo medlemskapsplaner: Free, Plus, Premium." },
    hi: { title: "कीमत — Qulo", description: "Qulo सदस्यता योजनाएं: Free, Plus, Premium।" },
  },
  sitemap: {
    tr: { title: "Site Haritası — Qulo", description: "Qulo web sitesindeki tüm sayfaların listesi." },
    en: { title: "Sitemap — Qulo", description: "All pages on the Qulo website." },
    de: { title: "Sitemap — Qulo", description: "Alle Seiten auf der Qulo-Website." },
    fr: { title: "Plan du site — Qulo", description: "Toutes les pages du site Qulo." },
    es: { title: "Mapa del sitio — Qulo", description: "Todas las páginas del sitio Qulo." },
    ar: { title: "خريطة الموقع — Qulo", description: "جميع صفحات موقع Qulo." },
    ru: { title: "Карта сайта — Qulo", description: "Все страницы сайта Qulo." },
    pt: { title: "Mapa do site — Qulo", description: "Todas as páginas do site Qulo." },
    it: { title: "Mappa del sito — Qulo", description: "Tutte le pagine del sito Qulo." },
    ja: { title: "サイトマップ — Qulo", description: "Quloウェブサイトのすべてのページ。" },
    ko: { title: "사이트맵 — Qulo", description: "Qulo 웹사이트의 모든 페이지." },
    zh: { title: "网站地图 — Qulo", description: "Qulo 网站上的所有页面。" },
    nl: { title: "Sitemap — Qulo", description: "Alle pagina's op de Qulo-website." },
    pl: { title: "Mapa strony — Qulo", description: "Wszystkie strony w serwisie Qulo." },
    sv: { title: "Webbplatskarta — Qulo", description: "Alla sidor på Qulo-webbplatsen." },
    hi: { title: "साइटमैप — Qulo", description: "Qulo वेबसाइट के सभी पृष्ठ।" },
  },
  about: {
    tr: { title: "Qulo Hakkında — Soru-Cevap Tabanlı Dating Uygulaması", description: "Qulo nedir? Swipe yerine soru-cevap ile eşleşen yeni nesil dating uygulaması. Quiz dating app ile tanışmanın yeni yolu." },
    en: { title: "About Qulo — Quiz-Based Dating App", description: "What is Qulo? A next-gen dating app that matches through questions instead of swiping. Discover the new way to date with a quiz dating app." },
    de: { title: "Über Qulo — Fragenbasierte Dating App", description: "Was ist Qulo? Eine Dating-App der nächsten Generation, die durch Fragen statt Swipen matcht." },
    fr: { title: "À propos de Qulo — App de rencontre par questions", description: "Qu'est-ce que Qulo ? Une app de rencontre nouvelle génération qui matche par les questions." },
    es: { title: "Sobre Qulo — App de Citas basada en Preguntas", description: "¿Qué es Qulo? Una app de citas de nueva generación que hace match a través de preguntas." },
    ar: { title: "عن Qulo — تطبيق مواعدة قائم على الأسئلة", description: "ما هو Qulo؟ تطبيق مواعدة من الجيل الجديد يطابق من خلال الأسئلة." },
    ja: { title: "Quloについて — クイズベースのマッチングアプリ", description: "Quloとは？スワイプではなく質問でマッチする次世代マッチングアプリ。" },
    ko: { title: "Qulo 소개 — 퀴즈 기반 데이팅 앱", description: "Qulo란? 스와이프 대신 질문으로 매칭하는 차세대 데이팅 앱." },
    zh: { title: "关于Qulo — 基于问答的约会应用", description: "Qulo是什么？通过问答而非滑动匹配的新一代约会应用。" },
    ru: { title: "О Qulo — Приложение для знакомств на основе вопросов", description: "Что такое Qulo? Приложение нового поколения, которое создаёт пары через вопросы." },
    pt: { title: "Sobre o Qulo — App de Namoro baseado em Perguntas", description: "O que é Qulo? Um app de namoro de nova geração que combina através de perguntas." },
    it: { title: "Chi è Qulo — App di Incontri basata su Domande", description: "Cos'è Qulo? Un'app di incontri di nuova generazione che fa match attraverso le domande." },
    nl: { title: "Over Qulo — Vragengebaseerde Dating App", description: "Wat is Qulo? Een dating app van de nieuwe generatie die matcht via vragen." },
    pl: { title: "O Qulo — Aplikacja randkowa oparta na pytaniach", description: "Czym jest Qulo? Aplikacja randkowa nowej generacji, która łączy przez pytania." },
    sv: { title: "Om Qulo — Frågebaserad Dejtingapp", description: "Vad är Qulo? En dejtingapp av nästa generation som matchar genom frågor." },
    hi: { title: "Qulo के बारे में — सवाल-आधारित डेटिंग ऐप", description: "Qulo क्या है? स्वाइप की जगह सवालों से मैच करने वाला अगली पीढ़ी का डेटिंग ऐप।" },
  },
};

/** Locale → OG locale mapping (BCP 47 → Open Graph format) */
export const OG_LOCALES: Record<string, string> = {
  tr: "tr_TR", en: "en_US", de: "de_DE", fr: "fr_FR", es: "es_ES",
  ar: "ar_SA", ru: "ru_RU", pt: "pt_BR", it: "it_IT", ja: "ja_JP",
  ko: "ko_KR", zh: "zh_CN", nl: "nl_NL", pl: "pl_PL", sv: "sv_SE",
  hi: "hi_IN",
};
