// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUh4WNI1-iQcmVGypaRT968ugJeKw1ltE',
    appId: '1:180673531842:android:ed53aa2fc153d55764505b',
    messagingSenderId: '180673531842',
    projectId: 'catchpad-mobile',
    storageBucket: 'catchpad-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOkcyFJp6irsUTzB8R9W1cm9wzb3bSaik',
    appId: '1:180673531842:ios:5d960519a597554664505b',
    messagingSenderId: '180673531842',
    projectId: 'catchpad-mobile',
    storageBucket: 'catchpad-mobile.appspot.com',
    androidClientId: '180673531842-0ntmf74vno3r5bu0b31a3j8vc45fv1j4.apps.googleusercontent.com',
    iosClientId: '180673531842-kme5anb4isdlit3jom5c95nrup1j0hun.apps.googleusercontent.com',
    iosBundleId: 'com.catchpad',
  );
}
