export interface Country {
  slug: string;
  names: Record<string, string>;
  emoji: string;
  population: string;
  /** City slugs that exist in cities.ts (for cross-linking) */
  quloCities: string[];
  /** Localized comma-separated list of top cities (for display) */
  topCities: Record<string, string>;
}

export const COUNTRIES: Country[] = [
  {
    slug: "turkey",
    names: { tr: "Türkiye", en: "Turkey", de: "Türkei", fr: "Turquie", es: "Turquía", ar: "تركيا", ru: "Турция", pt: "Turquia", it: "Turchia", ja: "トルコ", ko: "터키", zh: "土耳其", nl: "Turkije", pl: "Turcja", sv: "Turkiet", hi: "तुर्की" },
    emoji: "🇹🇷",
    population: "85M+",
    quloCities: ["istanbul"],
    topCities: {
      tr: "İstanbul, Ankara, İzmir, Bursa, Antalya",
      en: "Istanbul, Ankara, Izmir, Bursa, Antalya",
      de: "Istanbul, Ankara, Izmir, Bursa, Antalya",
      fr: "Istanbul, Ankara, Izmir, Bursa, Antalya",
      es: "Estambul, Ankara, Izmir, Bursa, Antalya",
      ar: "إسطنبول، أنقرة، إزمير، بورصة، أنطاليا",
      ru: "Стамбул, Анкара, Измир, Бурса, Анталия",
      pt: "Istambul, Ancara, Izmir, Bursa, Antália",
      it: "Istanbul, Ankara, Izmir, Bursa, Antalya",
      ja: "イスタンブール、アンカラ、イズミル、ブルサ、アンタルヤ",
      ko: "이스탄불, 앙카라, 이즈미르, 부르사, 안탈리아",
      zh: "伊斯坦布尔、安卡拉、伊兹密尔、布尔萨、安塔利亚",
      nl: "Istanbul, Ankara, Izmir, Bursa, Antalya",
      pl: "Stambuł, Ankara, Izmir, Bursa, Antalya",
      sv: "Istanbul, Ankara, Izmir, Bursa, Antalya",
      hi: "इस्तांबुल, अंकारा, इज़मिर, बर्सा, अंताल्या",
    },
  },
  {
    slug: "germany",
    names: { tr: "Almanya", en: "Germany", de: "Deutschland", fr: "Allemagne", es: "Alemania", ar: "ألمانيا", ru: "Германия", pt: "Alemanha", it: "Germania", ja: "ドイツ", ko: "독일", zh: "德国", nl: "Duitsland", pl: "Niemcy", sv: "Tyskland", hi: "जर्मनी" },
    emoji: "🇩🇪",
    population: "83M+",
    quloCities: ["berlin"],
    topCities: {
      tr: "Berlin, Münih, Hamburg, Köln, Frankfurt",
      en: "Berlin, Munich, Hamburg, Cologne, Frankfurt",
      de: "Berlin, München, Hamburg, Köln, Frankfurt",
      fr: "Berlin, Munich, Hambourg, Cologne, Francfort",
      es: "Berlín, Múnich, Hamburgo, Colonia, Fráncfort",
      ar: "برلين، ميونخ، هامبورغ، كولونيا، فرانكفورت",
      ru: "Берлин, Мюнхен, Гамбург, Кёльн, Франкфурт",
      pt: "Berlim, Munique, Hamburgo, Colônia, Frankfurt",
      it: "Berlino, Monaco, Amburgo, Colonia, Francoforte",
      ja: "ベルリン、ミュンヘン、ハンブルク、ケルン、フランクフルト",
      ko: "베를린, 뮌헨, 함부르크, 쾰른, 프랑크푸르트",
      zh: "柏林、慕尼黑、汉堡、科隆、法兰克福",
      nl: "Berlijn, München, Hamburg, Keulen, Frankfurt",
      pl: "Berlin, Monachium, Hamburg, Kolonia, Frankfurt",
      sv: "Berlin, München, Hamburg, Köln, Frankfurt",
      hi: "बर्लिन, म्यूनिख, हैम्बर्ग, कोलोन, फ्रैंकफर्ट",
    },
  },
  {
    slug: "france",
    names: { tr: "Fransa", en: "France", de: "Frankreich", fr: "France", es: "Francia", ar: "فرنسا", ru: "Франция", pt: "França", it: "Francia", ja: "フランス", ko: "프랑스", zh: "法国", nl: "Frankrijk", pl: "Francja", sv: "Frankrike", hi: "फ्रांस" },
    emoji: "🇫🇷",
    population: "67M+",
    quloCities: ["paris"],
    topCities: {
      tr: "Paris, Marsilya, Lyon, Toulouse, Nice",
      en: "Paris, Marseille, Lyon, Toulouse, Nice",
      de: "Paris, Marseille, Lyon, Toulouse, Nizza",
      fr: "Paris, Marseille, Lyon, Toulouse, Nice",
      es: "París, Marsella, Lyon, Toulouse, Niza",
      ar: "باريس، مرسيليا، ليون، تولوز، نيس",
      ru: "Париж, Марсель, Лион, Тулуза, Ницца",
      pt: "Paris, Marselha, Lyon, Toulouse, Nice",
      it: "Parigi, Marsiglia, Lione, Tolosa, Nizza",
      ja: "パリ、マルセイユ、リヨン、トゥールーズ、ニース",
      ko: "파리, 마르세유, 리옹, 툴루즈, 니스",
      zh: "巴黎、马赛、里昂、图卢兹、尼斯",
      nl: "Parijs, Marseille, Lyon, Toulouse, Nice",
      pl: "Paryż, Marsylia, Lyon, Tuluza, Nicea",
      sv: "Paris, Marseille, Lyon, Toulouse, Nice",
      hi: "पेरिस, मार्सिले, ल्योन, टूलूज़, नीस",
    },
  },
  {
    slug: "spain",
    names: { tr: "İspanya", en: "Spain", de: "Spanien", fr: "Espagne", es: "España", ar: "إسبانيا", ru: "Испания", pt: "Espanha", it: "Spagna", ja: "スペイン", ko: "스페인", zh: "西班牙", nl: "Spanje", pl: "Hiszpania", sv: "Spanien", hi: "स्पेन" },
    emoji: "🇪🇸",
    population: "47M+",
    quloCities: ["madrid"],
    topCities: {
      tr: "Madrid, Barcelona, Valencia, Sevilla, Málaga",
      en: "Madrid, Barcelona, Valencia, Seville, Málaga",
      de: "Madrid, Barcelona, Valencia, Sevilla, Málaga",
      fr: "Madrid, Barcelone, Valence, Séville, Malaga",
      es: "Madrid, Barcelona, Valencia, Sevilla, Málaga",
      ar: "مدريد، برشلونة، فالنسيا، إشبيلية، ملقا",
      ru: "Мадрид, Барселона, Валенсия, Севилья, Малага",
      pt: "Madrid, Barcelona, Valência, Sevilha, Málaga",
      it: "Madrid, Barcellona, Valencia, Siviglia, Malaga",
      ja: "マドリード、バルセロナ、バレンシア、セビリア、マラガ",
      ko: "마드리드, 바르셀로나, 발렌시아, 세비야, 말라가",
      zh: "马德里、巴塞罗那、瓦伦西亚、塞维利亚、马拉加",
      nl: "Madrid, Barcelona, Valencia, Sevilla, Málaga",
      pl: "Madryt, Barcelona, Walencja, Sewilla, Malaga",
      sv: "Madrid, Barcelona, Valencia, Sevilla, Málaga",
      hi: "मैड्रिड, बार्सिलोना, वेलेंसिया, सेविले, मलागा",
    },
  },
  {
    slug: "united-kingdom",
    names: { tr: "Birleşik Krallık", en: "United Kingdom", de: "Vereinigtes Königreich", fr: "Royaume-Uni", es: "Reino Unido", ar: "المملكة المتحدة", ru: "Великобритания", pt: "Reino Unido", it: "Regno Unito", ja: "イギリス", ko: "영국", zh: "英国", nl: "Verenigd Koninkrijk", pl: "Wielka Brytania", sv: "Storbritannien", hi: "यूनाइटेड किंगडम" },
    emoji: "🇬🇧",
    population: "67M+",
    quloCities: ["london"],
    topCities: {
      tr: "Londra, Manchester, Birmingham, Glasgow, Liverpool",
      en: "London, Manchester, Birmingham, Glasgow, Liverpool",
      de: "London, Manchester, Birmingham, Glasgow, Liverpool",
      fr: "Londres, Manchester, Birmingham, Glasgow, Liverpool",
      es: "Londres, Manchester, Birmingham, Glasgow, Liverpool",
      ar: "لندن، مانشستر، برمنغهام، غلاسكو، ليفربول",
      ru: "Лондон, Манчестер, Бирмингем, Глазго, Ливерпуль",
      pt: "Londres, Manchester, Birmingham, Glasgow, Liverpool",
      it: "Londra, Manchester, Birmingham, Glasgow, Liverpool",
      ja: "ロンドン、マンチェスター、バーミンガム、グラスゴー、リバプール",
      ko: "런던, 맨체스터, 버밍엄, 글래스고, 리버풀",
      zh: "伦敦、曼彻斯特、伯明翰、格拉斯哥、利物浦",
      nl: "Londen, Manchester, Birmingham, Glasgow, Liverpool",
      pl: "Londyn, Manchester, Birmingham, Glasgow, Liverpool",
      sv: "London, Manchester, Birmingham, Glasgow, Liverpool",
      hi: "लंदन, मैनचेस्टर, बर्मिंघम, ग्लासगो, लिवरपूल",
    },
  },
  {
    slug: "united-states",
    names: { tr: "Amerika Birleşik Devletleri", en: "United States", de: "Vereinigte Staaten", fr: "États-Unis", es: "Estados Unidos", ar: "الولايات المتحدة", ru: "США", pt: "Estados Unidos", it: "Stati Uniti", ja: "アメリカ合衆国", ko: "미국", zh: "美国", nl: "Verenigde Staten", pl: "Stany Zjednoczone", sv: "USA", hi: "संयुक्त राज्य" },
    emoji: "🇺🇸",
    population: "333M+",
    quloCities: ["new-york"],
    topCities: {
      tr: "New York, Los Angeles, Chicago, Houston, Miami",
      en: "New York, Los Angeles, Chicago, Houston, Miami",
      de: "New York, Los Angeles, Chicago, Houston, Miami",
      fr: "New York, Los Angeles, Chicago, Houston, Miami",
      es: "Nueva York, Los Ángeles, Chicago, Houston, Miami",
      ar: "نيويورك، لوس أنجلوس، شيكاغو، هيوستن، ميامي",
      ru: "Нью-Йорк, Лос-Анджелес, Чикаго, Хьюстон, Майами",
      pt: "Nova York, Los Angeles, Chicago, Houston, Miami",
      it: "New York, Los Angeles, Chicago, Houston, Miami",
      ja: "ニューヨーク、ロサンゼルス、シカゴ、ヒューストン、マイアミ",
      ko: "뉴욕, 로스앤젤레스, 시카고, 휴스턴, 마이애미",
      zh: "纽约、洛杉矶、芝加哥、休斯顿、迈阿密",
      nl: "New York, Los Angeles, Chicago, Houston, Miami",
      pl: "Nowy Jork, Los Angeles, Chicago, Houston, Miami",
      sv: "New York, Los Angeles, Chicago, Houston, Miami",
      hi: "न्यूयॉर्क, लॉस एंजिल्स, शिकागो, ह्यूस्टन, मियामी",
    },
  },
  {
    slug: "japan",
    names: { tr: "Japonya", en: "Japan", de: "Japan", fr: "Japon", es: "Japón", ar: "اليابان", ru: "Япония", pt: "Japão", it: "Giappone", ja: "日本", ko: "일본", zh: "日本", nl: "Japan", pl: "Japonia", sv: "Japan", hi: "जापान" },
    emoji: "🇯🇵",
    population: "125M+",
    quloCities: ["tokyo"],
    topCities: {
      tr: "Tokyo, Osaka, Kyoto, Yokohama, Nagoya",
      en: "Tokyo, Osaka, Kyoto, Yokohama, Nagoya",
      de: "Tokio, Osaka, Kyoto, Yokohama, Nagoya",
      fr: "Tokyo, Osaka, Kyoto, Yokohama, Nagoya",
      es: "Tokio, Osaka, Kioto, Yokohama, Nagoya",
      ar: "طوكيو، أوساكا، كيوتو، يوكوهاما، ناغويا",
      ru: "Токио, Осака, Киото, Йокогама, Нагоя",
      pt: "Tóquio, Osaka, Kyoto, Yokohama, Nagoya",
      it: "Tokyo, Osaka, Kyoto, Yokohama, Nagoya",
      ja: "東京、大阪、京都、横浜、名古屋",
      ko: "도쿄, 오사카, 교토, 요코하마, 나고야",
      zh: "东京、大阪、京都、横滨、名古屋",
      nl: "Tokio, Osaka, Kyoto, Yokohama, Nagoya",
      pl: "Tokio, Osaka, Kioto, Jokohama, Nagoja",
      sv: "Tokyo, Osaka, Kyoto, Yokohama, Nagoya",
      hi: "टोक्यो, ओसाका, क्योटो, योकोहामा, नागोया",
    },
  },
  {
    slug: "brazil",
    names: { tr: "Brezilya", en: "Brazil", de: "Brasilien", fr: "Brésil", es: "Brasil", ar: "البرازيل", ru: "Бразилия", pt: "Brasil", it: "Brasile", ja: "ブラジル", ko: "브라질", zh: "巴西", nl: "Brazilië", pl: "Brazylia", sv: "Brasilien", hi: "ब्राज़ील" },
    emoji: "🇧🇷",
    population: "215M+",
    quloCities: ["sao-paulo"],
    topCities: {
      tr: "São Paulo, Rio de Janeiro, Brasília, Salvador, Fortaleza",
      en: "São Paulo, Rio de Janeiro, Brasília, Salvador, Fortaleza",
      de: "São Paulo, Rio de Janeiro, Brasília, Salvador, Fortaleza",
      fr: "São Paulo, Rio de Janeiro, Brasília, Salvador, Fortaleza",
      es: "São Paulo, Río de Janeiro, Brasilia, Salvador, Fortaleza",
      ar: "ساو باولو، ريو دي جانيرو، برازيليا، سلفادور، فورتاليزا",
      ru: "Сан-Паулу, Рио-де-Жанейро, Бразилиа, Салвадор, Форталеза",
      pt: "São Paulo, Rio de Janeiro, Brasília, Salvador, Fortaleza",
      it: "San Paolo, Rio de Janeiro, Brasilia, Salvador, Fortaleza",
      ja: "サンパウロ、リオデジャネイロ、ブラジリア、サルバドール、フォルタレザ",
      ko: "상파울루, 리우데자네이루, 브라질리아, 살바도르, 포르탈레자",
      zh: "圣保罗、里约热内卢、巴西利亚、萨尔瓦多、福塔莱萨",
      nl: "São Paulo, Rio de Janeiro, Brasília, Salvador, Fortaleza",
      pl: "São Paulo, Rio de Janeiro, Brasília, Salvador, Fortaleza",
      sv: "São Paulo, Rio de Janeiro, Brasília, Salvador, Fortaleza",
      hi: "साओ पाउलो, रियो डी जनेरियो, ब्रासीलिया, साल्वाडोर, फोर्टालेज़ा",
    },
  },
  {
    slug: "russia",
    names: { tr: "Rusya", en: "Russia", de: "Russland", fr: "Russie", es: "Rusia", ar: "روسيا", ru: "Россия", pt: "Rússia", it: "Russia", ja: "ロシア", ko: "러시아", zh: "俄罗斯", nl: "Rusland", pl: "Rosja", sv: "Ryssland", hi: "रूस" },
    emoji: "🇷🇺",
    population: "144M+",
    quloCities: ["moscow"],
    topCities: {
      tr: "Moskova, St. Petersburg, Novosibirsk, Ekaterinburg, Kazan",
      en: "Moscow, St. Petersburg, Novosibirsk, Yekaterinburg, Kazan",
      de: "Moskau, St. Petersburg, Nowosibirsk, Jekaterinburg, Kasan",
      fr: "Moscou, Saint-Pétersbourg, Novossibirsk, Iekaterinbourg, Kazan",
      es: "Moscú, San Petersburgo, Novosibirsk, Ekaterimburgo, Kazán",
      ar: "موسكو، سانت بطرسبرغ، نوفوسيبيرسك، يكاترينبورغ، قازان",
      ru: "Москва, Санкт-Петербург, Новосибирск, Екатеринбург, Казань",
      pt: "Moscou, São Petersburgo, Novosibirsk, Ecaterimburgo, Kazan",
      it: "Mosca, San Pietroburgo, Novosibirsk, Ekaterinburg, Kazan",
      ja: "モスクワ、サンクトペテルブルク、ノヴォシビルスク、エカテリンブルク、カザン",
      ko: "모스크바, 상트페테르부르크, 노보시비르스크, 예카테린부르크, 카잔",
      zh: "莫斯科、圣彼得堡、新西伯利亚、叶卡捷琳堡、喀山",
      nl: "Moskou, Sint-Petersburg, Novosibirsk, Jekaterinenburg, Kazan",
      pl: "Moskwa, Sankt Petersburg, Nowosybirsk, Jekaterynburg, Kazań",
      sv: "Moskva, S:t Petersburg, Novosibirsk, Jekaterinburg, Kazan",
      hi: "मॉस्को, सेंट पीटर्सबर्ग, नोवोसिबिर्स्क, येकातेरिनबर्ग, कज़ान",
    },
  },
  {
    slug: "uae",
    names: { tr: "Birleşik Arap Emirlikleri", en: "United Arab Emirates", de: "Vereinigte Arabische Emirate", fr: "Émirats Arabes Unis", es: "Emiratos Árabes Unidos", ar: "الإمارات العربية المتحدة", ru: "ОАЭ", pt: "Emirados Árabes Unidos", it: "Emirati Arabi Uniti", ja: "アラブ首長国連邦", ko: "아랍에미리트", zh: "阿联酋", nl: "Verenigde Arabische Emiraten", pl: "Zjednoczone Emiraty Arabskie", sv: "Förenade Arabemiraten", hi: "संयुक्त अरब अमीरात" },
    emoji: "🇦🇪",
    population: "10M+",
    quloCities: ["dubai"],
    topCities: {
      tr: "Dubai, Abu Dabi, Şarika, Acman, Fujeyre",
      en: "Dubai, Abu Dhabi, Sharjah, Ajman, Fujairah",
      de: "Dubai, Abu Dhabi, Schardscha, Adschman, Fudschaira",
      fr: "Dubaï, Abou Dhabi, Charjah, Ajman, Fujaïrah",
      es: "Dubái, Abu Dabi, Sharjah, Ajmán, Fujairah",
      ar: "دبي، أبوظبي، الشارقة، عجمان، الفجيرة",
      ru: "Дубай, Абу-Даби, Шарджа, Аджман, Эль-Фуджайра",
      pt: "Dubai, Abu Dhabi, Sharjah, Ajman, Fujairah",
      it: "Dubai, Abu Dhabi, Sharjah, Ajman, Fujairah",
      ja: "ドバイ、アブダビ、シャルジャ、アジュマーン、フジャイラ",
      ko: "두바이, 아부다비, 샤르자, 아지만, 푸자이라",
      zh: "迪拜、阿布扎比、沙迦、阿吉曼、富查伊拉",
      nl: "Dubai, Abu Dhabi, Sharjah, Ajman, Fujairah",
      pl: "Dubaj, Abu Zabi, Szardża, Adżman, Fudżajra",
      sv: "Dubai, Abu Dhabi, Sharjah, Ajman, Fujairah",
      hi: "दुबई, अबू धाबी, शारजाह, अजमान, फुजैरा",
    },
  },
];
