name: test_app
publish_to: 'none'
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  catchpad:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0Z

flutter:
  uses-material-design: true